#!/usr/bin/env python
"""Challenge mode as Radical Cobblemon Trainers data: the per-player series, a second id for every trainer that has a
Challenge team, and the second spawner in every gym and on every League floor. Imported by tools/route_trainers.py,
whose pack (build/datapacks/cobblers_trainers) carries all of it; nothing here is a pack of its own.

The design and what was read for it: docs/research/RCT_PER_PLAYER_MODE.md section 5. As built:
docs/mechanics/OAK_AND_CHALLENGE.md, which also lists what an audit must check. The data: data/challenge_mode.json
(hand) and each record's modes.challenge.rct in data/trainers.json (generated by docs/story/generate_trainers.py).

  series     data/rctmod/series/cobblers_challenge.json: title, description, difficulty only, so the config's
             initialLevelCap 20 and relativeLevelCap 0 apply exactly as they do to Kanto. Oak puts a player in it once
             (tools/compile_dialogue.py effect rctmod_series); Normal players stay in Kanto, the initial series.
  bosses     for each of the thirteen upstream ids our team overrides (tools/route_trainers.py overrides()), the id
             <upstream>_challenge:
               trainers/<id>.json   the record's Challenge team, battleFormat, and identity (its own, so rctmod's
                                    uniqueness rule lets it stand beside the Normal leader)
               mobs/.../<id>.json   upstream's mob fields (data/challenge_mode.json upstream_mob), series
                                    cobblers_challenge, requiredDefeats the upstream chain suffixed
               dialogs/.../<id>     every refusal (data/trainer_refusals.json) and the battle lines: upstream's own
                                    translatable lines for a leader, our authored ones for the League
               loot_table/.../<id>  empty: the badge and TMs come from the flag's first-win reward, once
               advancement          cobblers:trainer/<id>: a Challenge win grants upstream's own defeat advancement,
                                    so the League's elevator, the League hold-off and the Champion's door, which key
                                    on it, open for a Challenge player too
             and the badge flags list the id beside the Normal one (data/progression.json trainer_ids).
  spawners   cobblers:trainers/challenge/place_<id>: the second spawner, powered from below and set into the floor,
             at each data/challenge_mode.json bosses[].spawner.at. Run from cobblers:trainers/challenge/cycle (the
             trainers clock, every 10 ticks) while a player is within NEAR, the chunk is loaded, the block is not
             already there and the two cells over it are air: no re-apply step is needed, and an export that erases it
             is repaired the next time a player comes near.
  routes     <id>_challenge for every seated trainer whose record has a Challenge team: the same files as the Normal
             seat (team from modes.challenge.rct), series cobblers_challenge. tools/route_trainers.py's cycle swaps
             the one standing entity's TrainerId to whichever mode the nearest player is in (ASSUMED, experiment E7).

  python tools/challenge_mode.py --check     load, validate and summarise; writes nothing
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NS = "cobblers"
SPAWNER = "rctmod:trainer_spawner"
# a second spawner is only set while a player is this near it: no block checks run for an empty gym, and a spawner
# spawns its trainer only for a nearby player anyway
NEAR = 48


class ChallengeError(SystemExit):
    pass


def doc():
    return json.loads((ROOT / "data" / "challenge_mode.json").read_text(encoding="utf-8"))


def suffix():
    return doc()["id_suffix"]


def challenge_id(tid):
    return tid + suffix()


def series_id():
    return doc()["series"]["id"]


def mode_tag():
    return doc()["mode"]["tag"]


def series_file():
    s = doc()["series"]
    return {"title": {"literal": s["title"]}, "description": {"literal": s["description"]},
            "difficulty": int(s["difficulty"])}


# ------------------------------------------------------------------------------------------------ bosses
def boss_ids(overrides):
    """[(record, upstream id, challenge id, data entry)] in the overrides' order. Every override has an entry and
    every entry an override: a leader with a Challenge team nobody installs, or an entry for a trainer we do not
    override, fails rather than silently thinning the series."""
    d = doc()
    bosses = d["bosses"]
    out, seen = [], set()
    for rec, upstream, _entry, _src in overrides:
        e = bosses.get(upstream)
        if e is None:
            raise ChallengeError("data/challenge_mode.json has no bosses entry for %s (%s)" % (upstream, rec["id"]))
        seen.add(upstream)
        out.append((rec, upstream, upstream + d["id_suffix"], e))
    extra = sorted(set(bosses) - seen)
    if extra:
        raise ChallengeError("data/challenge_mode.json bosses names %s, which tools/route_trainers.py does not "
                             "override" % extra)
    return out


def check_chain(bosses):
    """The Challenge chain mirrors Kanto's: every required id is one of the thirteen, and exactly one has none."""
    ups = {u for _r, u, _c, _e in bosses}
    roots = [u for _r, u, _c, e in bosses if not e.get("upstream_required")]
    if len(roots) != 1:
        raise ChallengeError("the Challenge chain needs exactly one first trainer, found %s" % roots)
    for _r, u, _c, e in bosses:
        for req in e.get("upstream_required") or []:
            if req not in ups:
                raise ChallengeError("%s requires %s, which is not one of the thirteen" % (u, req))


def challenge_rct(rec):
    """The record's Challenge payload. The level cap reproduces the Normal one only when its team tops out at the
    record's ace_level (RCT_PER_PLAYER_MODE.md section 3, condition 1): refuse otherwise rather than emit a
    relativeLevelCap nobody asked for."""
    mode = (rec.get("modes") or {}).get("challenge")
    if not mode or not mode.get("rct") or not mode["rct"].get("team"):
        raise ChallengeError("%s has no modes.challenge.rct team" % rec["id"])
    rct = mode["rct"]
    if rec.get("ace_level") is not None:
        top = max(m["level"] for m in rct["team"])
        if top != rec["ace_level"]:
            raise ChallengeError("%s's Challenge team tops out at %d, not its ace_level %d: the Challenge cap would "
                                 "differ from the Normal one" % (rec["id"], top, rec["ace_level"]))
    return rct


def boss_files(overrides, with_refusals, league_lines):
    """{pack path: content} for the thirteen Challenge ids. `league_lines(entry)` gives the authored lines of a League
    override entry, or None for a leader (whose lines are upstream's)."""
    d = doc()
    bosses = boss_ids(overrides)
    check_chain(bosses)
    sfx, sid = d["id_suffix"], d["series"]["id"]
    counts = d["upstream_battle_line_counts"]
    out = {"data/rctmod/series/%s.json" % sid: series_file()}
    for rec, upstream, cid, e in bosses:
        rct = challenge_rct(rec)
        identity = rct.get("identity")
        if not identity or identity == (rec.get("rct") or {}).get("identity"):
            raise ChallengeError("%s: the Challenge payload's identity %r is not its own, so rctmod would refuse to "
                                 "spawn it beside the Normal leader (TrainerSpawner.isUnique)" % (rec["id"], identity))
        team = {k: rct[k] for k in ("name", "ai", "battleRules", "bag", "team") if k in rct}
        team["battleFormat"] = rct.get("battleFormat", "GEN_9_SINGLES")
        team["identity"] = identity
        out["data/rctmod/trainers/%s.json" % cid] = team
        mob = dict(e["upstream_mob"])
        mob["series"] = [sid]
        req = [[r + sfx] for r in e.get("upstream_required") or []]
        if req:
            mob["requiredDefeats"] = req
        out["data/rctmod/mobs/trainers/single/%s.json" % cid] = mob
        own = league_lines(upstream)
        if own is None:
            lang = e.get("lang")
            if not lang:
                raise ChallengeError("%s: a leader with no authored lines needs `lang` (upstream's line prefix)" % upstream)
            own = {ctx: [{"translatable": "dialogs.rctmod.%s.%s.%d" % (lang, ctx, i)} for i in range(int(n))]
                   for ctx, n in counts.items() if ctx != "why"}
        lines = with_refusals(own)
        # upstream's leader and League files ask for these by their own names; ours has one line for all three
        for alias in ("missing_required_trainer_leader", "missing_required_trainer_e4", "missing_required_trainer_champ"):
            lines.setdefault(alias, lines["missing_required_trainer"])
        out["data/rctmod/dialogs/trainers/single/%s.json" % cid] = lines
        out["data/rctmod/loot_table/trainers/single/%s.json" % cid] = {"pools": []}
        out["data/%s/advancement/trainer/%s.json" % (NS, cid)] = {
            "criteria": {"won": {"trigger": "rctmod:defeat_count", "conditions": {"trainer_ids": [cid], "count": 1}}},
            "rewards": {"function": "%s:trainers/won/%s" % (NS, cid)}}
        out["data/%s/function/trainers/won/%s.mcfunction" % (NS, cid)] = [
            "# %s: this player won Challenge %s (rctmod defeat_count, winning side only): upstream's own defeat" % (cid, upstream),
            "# advancement, which the League's elevator, the League hold-off and the Champion's door key on",
            "advancement grant @s only %s" % e["advancement"]]
    out.update(spawner_files(bosses))
    return out


def spawner_files(bosses):
    """The second spawner per boss: one place function each, and the lines the trainers cycle runs."""
    out, cycle = {}, ["# the second spawners: set while a player is within %d, the chunk is loaded, the block is "
                      "missing and the two cells over it are air" % NEAR]
    for _rec, _up, cid, e in bosses:
        x, y, z = e["spawner"]["at"]
        out["data/%s/function/trainers/challenge/place_%s.mcfunction" % (NS, cid)] = [
            "# %s's spawner, set into the floor and powered from below (EXP-013 E2): %s" % (cid, e["spawner"]["why"]),
            "# chunks-loaded-by: %s:trainers/challenge/cycle (execute if loaded at the spawner's cell; the redstone "
            "block under it is the same chunk)" % NS,
            "setblock %d %d %d minecraft:redstone_block" % (x, y - 1, z),
            "setblock %d %d %d %s{TrainerIds:[\"%s\"]}" % (x, y, z, SPAWNER, cid)]
        cycle.append("execute if entity @a[x=%d,y=%d,z=%d,distance=..%d] if loaded %d %d %d unless block %d %d %d %s "
                     "if block %d %d %d minecraft:air if block %d %d %d minecraft:air "
                     "run function %s:trainers/challenge/place_%s"
                     % (x, y, z, NEAR, x, y, z, x, y, z, SPAWNER, x, y + 1, z, x, y + 2, z, NS, cid))
    out["cycle"] = cycle
    return out


def spawner_seats(overrides):
    """[(challenge id, (x, y, z), badge flag or None, upstream id)] for the hold-off lines."""
    return [(cid, tuple(e["spawner"]["at"]), None, up) for _r, up, cid, e in boss_ids(overrides)]


# ------------------------------------------------------------------------------------------------ routes
def has_challenge(rec):
    m = (rec.get("modes") or {}).get("challenge")
    return bool(m and m.get("rct") and m["rct"].get("team"))


def route_files(tid, rec, normal_mob, normal_dialog):
    """The Challenge copy of one seated trainer: the same mob and lines, its own team and series."""
    cid = challenge_id(tid)
    rct = challenge_rct(rec)
    mob = dict(normal_mob)
    mob["series"] = [series_id()]
    return cid, {
        "data/rctmod/trainers/%s.json" % cid: {k: rct[k] for k in ("name", "ai", "battleRules", "bag", "team") if k in rct},
        "data/rctmod/mobs/trainers/single/%s.json" % cid: mob,
        "data/rctmod/dialogs/trainers/single/%s.json" % cid: normal_dialog,
        "data/rctmod/loot_table/trainers/single/%s.json" % cid: {"pools": []},
    }


def swap_lines(tid, seat, near):
    """The one entity at a seat carries the mode of the nearest player within `near`: the Challenge id while that
    player has the mode tag, the Normal id otherwise and when nobody is near. Never during a battle (InBattle:0b).
    ASSUMED: a data merge of TrainerId swaps the team (RCT_PER_PLAYER_MODE.md experiment E7)."""
    cid, tag = challenge_id(tid), mode_tag()
    x, y, z = seat
    sel = lambda i: ('@e[type=rctmod:trainer,x=%d.5,y=%d,z=%d.5,distance=..24,nbt={TrainerId:"%s",InBattle:0b}]'
                     % (x, y, z, i))
    here = lambda i: '@e[type=rctmod:trainer,distance=..0.5,nbt={TrainerId:"%s",InBattle:0b},limit=1]' % i
    return [
        "# %s: the mode of the nearest player decides which team stands here" % tid,
        "execute as %s at @s as @p[distance=..%s] if entity @s[tag=%s] run data merge entity %s {TrainerId:\"%s\"}"
        % (sel(tid), near, tag, here(tid), cid),
        "execute as %s at @s as @p[distance=..%s] unless entity @s[tag=%s] run data merge entity %s {TrainerId:\"%s\"}"
        % (sel(cid), near, tag, here(cid), tid),
        "execute as %s at @s unless entity @a[distance=..%s] run data merge entity @s {TrainerId:\"%s\"}"
        % (sel(cid), near, tid),
    ]


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true", help="validate and summarise; write nothing (the default)")
    p.parse_args(argv)
    sys.path.insert(0, str(ROOT / "tools"))
    import route_trainers as RT
    over, _held = RT.overrides()
    files = boss_files(over, RT.with_refusals, RT.league_lines)
    recs, seats, _f = RT.load()
    routes = [s["id"] for s in seats if s["id"] in recs and has_challenge(recs[s["id"]])]
    print("series %s; %d Challenge bosses, %d spawners; %d seated trainers swap to a Challenge id"
          % (series_id(), len(boss_ids(over)), len(files["cycle"]) - 1, len(routes)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
