#!/usr/bin/env python
"""Challenge mode as Radical Cobblemon Trainers data: the per-player series, a second id for every trainer that has a
Challenge team, and the second spawner in every gym and on every League floor. Imported by tools/route_trainers.py,
whose pack (build/datapacks/cobblers_trainers) carries all of it; nothing here is a pack of its own.

The design and what was read for it: docs/research/RCT_PER_PLAYER_MODE.md section 5. As built:
docs/mechanics/OAK_AND_CHALLENGE.md, which also lists what an audit must check. The data: data/challenge_mode.json
(hand) and each record's modes.challenge.rct in data/trainers.json (generated by docs/story/generate_trainers.py).

  series     data/rctmod/series/cobblers_challenge.json: title, description, difficulty only, so the config's
             initialLevelCap 20 and relativeLevelCap 0 apply exactly as they do to Kanto. Oak puts a player in it once
             (tools/compile_dialogue.py effect rctmod_series); Normal players stay in Kanto, the initial series.
  bosses     for each of the thirteen upstream ids our team overrides (tools/route_trainers.py overrides()), the id
             <upstream>_challenge:
               trainers/<id>.json   the record's Challenge team, battleFormat, and identity (its own, so rctmod's
                                    uniqueness rule lets it stand beside the Normal leader)
               mobs/.../<id>.json   upstream's mob fields (data/challenge_mode.json upstream_mob), series
                                    cobblers_challenge, requiredDefeats the upstream chain suffixed
               dialogs/.../<id>     every refusal (data/trainer_refusals.json) and the battle lines: upstream's own
                                    translatable lines for a leader, our authored ones for the League
               loot_table/.../<id>  empty: the badge and TMs come from the flag's first-win reward, once
               advancement          cobblers:trainer/<id>: a Challenge win grants upstream's own defeat advancement,
                                    so the League's elevator, the League hold-off and the Champion's door, which key
                                    on it, open for a Challenge player too
             and the badge flags list the id beside the Normal one (data/progression.json trainer_ids).
  spawners   cobblers:trainers/challenge/place_<id>: the second spawner, powered from below and set into the floor,
             at each data/challenge_mode.json bosses[].spawner.at. Run from cobblers:trainers/challenge/cycle (the
             trainers clock, every 10 ticks) while a player is within NEAR, the chunk is loaded, the block is not
             already there and the two cells over it are air: no re-apply step is needed, and an export that erases it
             is repaired the next time a player comes near.
  one leader the owner's 2026-10-07 decision (docs/mechanics/ONE_LEADER_SWAP.md): a boss named in data/challenge_mode.json
             single_leader.rollout gets NO second spawner. The cycle instead swaps its ONE spawner's TrainerIds and its
             standing trainer's TrainerId to <id>_challenge while the nearest player within REACH of the spawner carries
             the mode tag, and back otherwise, never while either id is InBattle (single_lines). The second spawner a
             world already holds is removed once by cobblers:trainers/challenge/retire_<id> (reapply step R17L), at its
             recorded data position, and read back by single_leader_verify. Bosses not in the rollout: unchanged.
             A boss with single_leader.move (Lance, the owner's 2026-10-09 decision: two League storeys inside one
             swap reach, measured by tools/league_separation.py) also gets cobblers:trainers/challenge/move_<id>,
             run by R17L after its retire: the one spawner set at move.to, the old cell restored.
  routes    <id>_challenge for every seated trainer whose record has a Challenge team: the same files as the Normal
             seat (team from modes.challenge.rct), series cobblers_challenge. tools/route_trainers.py's cycle swaps
             the one standing entity's TrainerId to whichever mode the nearest player is in (ASSUMED, experiment E7).

  python tools/challenge_mode.py --check     load, validate and summarise; writes nothing
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NS = "cobblers"
SPAWNER = "rctmod:trainer_spawner"
# a second spawner is only set while a player is this near it: no block checks run for an empty gym, and a spawner
# spawns its trainer only for a nearby player anyway
NEAR = 48
RCT_CONFIG = ROOT / "modpack" / "config" / "rctmod-server.toml"
# the radius every other selector in this pack uses around a leader's seat (tools/route_trainers.py leader_cycle_lines)
SEAT_BOX = 24


class ChallengeError(SystemExit):
    pass


def doc():
    return json.loads((ROOT / "data" / "challenge_mode.json").read_text(encoding="utf-8"))


def suffix():
    return doc()["id_suffix"]


def challenge_id(tid):
    return tid + suffix()


def series_id():
    return doc()["series"]["id"]


def mode_tag():
    return doc()["mode"]["tag"]


def series_file():
    s = doc()["series"]
    return {"title": {"literal": s["title"]}, "description": {"literal": s["description"]},
            "difficulty": int(s["difficulty"])}


# ------------------------------------------------------------------------------------------------ bosses
def boss_ids(overrides):
    """[(record, upstream id, challenge id, data entry)] in the overrides' order. Every override has an entry and
    every entry an override: a leader with a Challenge team nobody installs, or an entry for a trainer we do not
    override, fails rather than silently thinning the series."""
    d = doc()
    bosses = d["bosses"]
    out, seen = [], set()
    for rec, upstream, _entry, _src in overrides:
        e = bosses.get(upstream)
        if e is None:
            raise ChallengeError("data/challenge_mode.json has no bosses entry for %s (%s)" % (upstream, rec["id"]))
        seen.add(upstream)
        out.append((rec, upstream, upstream + d["id_suffix"], e))
    extra = sorted(set(bosses) - seen)
    if extra:
        raise ChallengeError("data/challenge_mode.json bosses names %s, which tools/route_trainers.py does not "
                             "override" % extra)
    return out


def check_chain(bosses):
    """The Challenge chain mirrors Kanto's: every required id is one of the thirteen, and exactly one has none."""
    ups = {u for _r, u, _c, _e in bosses}
    roots = [u for _r, u, _c, e in bosses if not e.get("upstream_required")]
    if len(roots) != 1:
        raise ChallengeError("the Challenge chain needs exactly one first trainer, found %s" % roots)
    for _r, u, _c, e in bosses:
        for req in e.get("upstream_required") or []:
            if req not in ups:
                raise ChallengeError("%s requires %s, which is not one of the thirteen" % (u, req))


def challenge_rct(rec):
    """The record's Challenge payload. The level cap reproduces the Normal one only when its team tops out at the
    record's ace_level (RCT_PER_PLAYER_MODE.md section 3, condition 1): refuse otherwise rather than emit a
    relativeLevelCap nobody asked for."""
    mode = (rec.get("modes") or {}).get("challenge")
    if not mode or not mode.get("rct") or not mode["rct"].get("team"):
        raise ChallengeError("%s has no modes.challenge.rct team" % rec["id"])
    rct = mode["rct"]
    if rec.get("ace_level") is not None:
        top = max(m["level"] for m in rct["team"])
        if top != rec["ace_level"]:
            raise ChallengeError("%s's Challenge team tops out at %d, not its ace_level %d: the Challenge cap would "
                                 "differ from the Normal one" % (rec["id"], top, rec["ace_level"]))
    return rct


def boss_files(overrides, with_refusals, league_lines):
    """{pack path: content} for the thirteen Challenge ids. `league_lines(entry)` gives the authored lines of a League
    override entry, or None for a leader (whose lines are upstream's)."""
    d = doc()
    bosses = boss_ids(overrides)
    check_chain(bosses)
    sfx, sid = d["id_suffix"], d["series"]["id"]
    counts = d["upstream_battle_line_counts"]
    out = {"data/rctmod/series/%s.json" % sid: series_file()}
    for rec, upstream, cid, e in bosses:
        rct = challenge_rct(rec)
        identity = rct.get("identity")
        if not identity or identity == (rec.get("rct") or {}).get("identity"):
            raise ChallengeError("%s: the Challenge payload's identity %r is not its own, so rctmod would refuse to "
                                 "spawn it beside the Normal leader (TrainerSpawner.isUnique)" % (rec["id"], identity))
        team = {k: rct[k] for k in ("name", "ai", "battleRules", "bag", "team") if k in rct}
        team["battleFormat"] = rct.get("battleFormat", "GEN_9_SINGLES")
        team["identity"] = identity
        out["data/rctmod/trainers/%s.json" % cid] = team
        mob = dict(e["upstream_mob"])
        mob["series"] = [sid]
        req = [[r + sfx] for r in e.get("upstream_required") or []]
        if req:
            mob["requiredDefeats"] = req
        out["data/rctmod/mobs/trainers/single/%s.json" % cid] = mob
        own = league_lines(upstream)
        if own is None:
            lang = e.get("lang")
            if not lang:
                raise ChallengeError("%s: a leader with no authored lines needs `lang` (upstream's line prefix)" % upstream)
            own = {ctx: [{"translatable": "dialogs.rctmod.%s.%s.%d" % (lang, ctx, i)} for i in range(int(n))]
                   for ctx, n in counts.items() if ctx != "why"}
        lines = with_refusals(own)
        # upstream's leader and League files ask for these by their own names; ours has one line for all three
        for alias in ("missing_required_trainer_leader", "missing_required_trainer_e4", "missing_required_trainer_champ"):
            lines.setdefault(alias, lines["missing_required_trainer"])
        out["data/rctmod/dialogs/trainers/single/%s.json" % cid] = lines
        out["data/rctmod/loot_table/trainers/single/%s.json" % cid] = {"pools": []}
        out["data/%s/advancement/trainer/%s.json" % (NS, cid)] = {
            "criteria": {"won": {"trigger": "rctmod:defeat_count", "conditions": {"trainer_ids": [cid], "count": 1}}},
            "rewards": {"function": "%s:trainers/won/%s" % (NS, cid)}}
        out["data/%s/function/trainers/won/%s.mcfunction" % (NS, cid)] = [
            "# %s: this player won Challenge %s (rctmod defeat_count, winning side only): upstream's own defeat" % (cid, upstream),
            "# advancement, which the League's elevator, the League hold-off and the Champion's door key on",
            "advancement grant @s only %s" % e["advancement"]]
    out.update(spawner_files(bosses))
    return out


def spawner_files(bosses):
    """The second spawner per boss: one place function each, and the lines the trainers cycle runs. A boss in the
    single-leader rollout gets no place function and no place line: its swap lines and its one-shot retire function
    instead, in the same position in the cycle."""
    out, cycle = {}, ["# the second spawners: set while a player is within %d, the chunk is loaded, the block is "
                      "missing and the two cells over it are air" % NEAR]
    single = rollout()
    for _rec, up, cid, e in bosses:
        if up in single:
            seat = normal_seat(up, e)
            cycle += single_lines(up, cid, seat, reach())
            out["data/%s/function/trainers/challenge/retire_%s.mcfunction" % (NS, cid)] = retire_lines(up, cid, e)
            if move_of(up, e):
                out["data/%s/function/trainers/challenge/move_%s.mcfunction" % (NS, up)] = move_lines(up, cid, e)
            continue
        x, y, z = e["spawner"]["at"]
        out["data/%s/function/trainers/challenge/place_%s.mcfunction" % (NS, cid)] = [
            "# %s's spawner, set into the floor and powered from below (EXP-013 E2): %s" % (cid, e["spawner"]["why"]),
            "# chunks-loaded-by: %s:trainers/challenge/cycle (execute if loaded at the spawner's cell; the redstone "
            "block under it is the same chunk)" % NS,
            "setblock %d %d %d minecraft:redstone_block" % (x, y - 1, z),
            "setblock %d %d %d %s{TrainerIds:[\"%s\"]}" % (x, y, z, SPAWNER, cid)]
        cycle.append("execute if entity @a[x=%d,y=%d,z=%d,distance=..%d] if loaded %d %d %d unless block %d %d %d %s "
                     "if block %d %d %d minecraft:air if block %d %d %d minecraft:air "
                     "run function %s:trainers/challenge/place_%s"
                     % (x, y, z, NEAR, x, y, z, x, y, z, SPAWNER, x, y + 1, z, x, y + 2, z, NS, cid))
    out["cycle"] = cycle
    return out


def spawner_seats(overrides):
    """[(challenge id, (x, y, z), badge flag or None, upstream id)] for the hold-off lines: where the Challenge
    leader stands, which for a single-leader boss is its one spawner."""
    return [(cid, challenge_seat(up, e), None, up) for _r, up, cid, e in boss_ids(overrides)]


# ------------------------------------------------------------------------------------------------ one leader
def rollout():
    """The upstream ids that stand as ONE leader (data/challenge_mode.json single_leader.rollout: a list, or "all").
    An id that is not one of the bosses fails rather than silently doing nothing."""
    d = doc()
    r = (d.get("single_leader") or {}).get("rollout") or []
    if r == "all":
        return set(d["bosses"])
    if not isinstance(r, list):
        raise ChallengeError("single_leader.rollout must be a list of boss ids or \"all\", not %r" % (r,))
    unknown = sorted(set(r) - set(d["bosses"]))
    if unknown:
        raise ChallengeError("single_leader.rollout names %s, which data/challenge_mode.json bosses does not" % unknown)
    return set(r)


def _gym_leader_records():
    """{upstream id: (gym id, leader record)} from data/gym_buildings/*.json, the records that build the spawner."""
    out = {}
    for f in sorted((ROOT / "data" / "gym_buildings").glob("gym*.json")):
        g = json.loads(f.read_text(encoding="utf-8"))
        lead = g.get("leader") or {}
        if lead.get("id") and lead.get("spawner"):
            out[lead["id"]] = (g["id"], lead)
    return out


def normal_seat(up, entry):
    """The Normal leader's one spawner, from the data that builds it: data/gym_buildings leader.spawner, else
    data/gym_interiors.json expect_spawner_at (Misty's template spawner), else the entry's own
    single_leader.normal_at (the League's template spawners, which no other record carries). None of these is read
    from a world. A rollout boss with none fails: its swap would have nothing to drive."""
    gb = _gym_leader_records().get(up)
    if gb:
        return tuple(gb[1]["spawner"])
    for g in json.loads((ROOT / "data" / "gym_interiors.json").read_text(encoding="utf-8"))["gyms"]:
        lead = g.get("leader") or {}
        if g.get("built") and lead.get("id") == up and lead.get("expect_spawner_at"):
            return tuple(lead["expect_spawner_at"])
    at = (entry.get("single_leader") or {}).get("normal_at")
    if at:
        mv = move_of(up, entry)
        if mv and tuple(at) != tuple(mv["to"]):
            raise ChallengeError("%s: single_leader.normal_at %s is not move.to %s: the swap would drive a spawner the "
                                 "move never sets" % (up, tuple(at), tuple(mv["to"])))
        return tuple(at)
    raise ChallengeError("%s is in single_leader.rollout but no record gives its Normal spawner: add "
                         "bosses.%s.single_leader.normal_at, measured from its template" % (up, up))


def challenge_seat(up, entry):
    """Where the Challenge leader stands: the one spawner for a rollout boss, the second spawner otherwise."""
    return normal_seat(up, entry) if up in rollout() else tuple(entry["spawner"]["at"])


def reach():
    """How near a player must be for its mode to choose the leader: rctmod's server-wide forceBattleMaxDistance
    (modpack/config/rctmod-server.toml), the farthest a trainer starts a battle on sight, plus one -- the same
    `sight + 1` the route swap uses (tools/route_trainers.py). Within it the leader has the right id before any
    battle can start; beyond it nobody can start one, so the leader may go back to Normal. Read from the file, not a
    constant, so a config change moves it."""
    m = None
    for line in RCT_CONFIG.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("forceBattleMaxDistance") and "=" in s:
            m = float(s.split("=", 1)[1].strip())
    if m is None:
        raise ChallengeError("%s has no forceBattleMaxDistance" % RCT_CONFIG)
    return m + 1


def single_lines(up, cid, seat, near):
    """One leader per gym: the spawner's TrainerIds and its standing trainer's TrainerId follow the nearest player
    within `near` of the SPAWNER (both decided from the same point, so block and entity cannot disagree), the
    Challenge id while that player carries the mode tag, the Normal id otherwise and when nobody is near.

    Never during a battle: rctmod's documented InBattle entity tag (docs/research/notes/rct-arena-capabilities.md).
    The entity is only merged while it reads InBattle:0b, and the block is held while either id near the seat reads
    InBattle:1b, so a battle never sees its spawner change under it. If rctmod never writes that tag, the entity
    lines match nothing and the leader stays Normal (a Challenge player is refused, never mis-teamed).

    Block first, entity second, in one function run: the trainer's setTrainerId notifies its spawner
    (notifyChangeTrainerId, RCT_PER_PLAYER_MODE.md section 2), and the spawner then already holds the new id.
    ASSUMED, experiment E7: that data merge swaps the team and that the spawner accepts the merge."""
    x, y, z = seat
    tag = mode_tag()
    box = "x=%d.5,y=%d,z=%d.5,distance=..%d" % (x, y, z, SEAT_BOX)
    busy = " ".join('unless entity @e[type=rctmod:trainer,%s,nbt={TrainerId:"%s",InBattle:1b}]' % (box, i)
                    for i in (up, cid))
    head = "execute if loaded %d %d %d if block %d %d %d %s %s positioned %d.5 %d %d.5" % (
        x, y, z, x, y, z, SPAWNER, busy, x, y, z)
    holds = lambda i: 'unless block %d %d %d %s{TrainerIds:["%s"]}' % (x, y, z, SPAWNER, i)
    block = lambda i: 'run data merge block %d %d %d {TrainerIds:["%s"]}' % (x, y, z, i)
    ent = lambda i: '@e[type=rctmod:trainer,%s,nbt={TrainerId:"%s",InBattle:0b},limit=1]' % (box, i)
    entity = lambda frm, to: "run data merge entity %s {TrainerId:\"%s\"}" % (ent(frm), to)
    n = "%g" % near
    return [
        "# %s: ONE leader (single_leader.rollout). The nearest player within %s of the spawner chooses the id, never "
        "in a battle; the spawner first, then the trainer" % (up, n),
        "%s as @p[distance=..%s] if entity @s[tag=%s] %s %s" % (head, n, tag, holds(cid), block(cid)),
        "%s as @p[distance=..%s] unless entity @s[tag=%s] %s %s" % (head, n, tag, holds(up), block(up)),
        "%s unless entity @a[distance=..%s] %s %s" % (head, n, holds(up), block(up)),
        "%s as @p[distance=..%s] if entity @s[tag=%s] %s" % (head, n, tag, entity(up, cid)),
        "%s as @p[distance=..%s] unless entity @s[tag=%s] %s" % (head, n, tag, entity(cid, up)),
        "%s unless entity @a[distance=..%s] %s" % (head, n, entity(cid, up)),
    ]


def restore_blocks(up, entry):
    """(floor, under): what the second spawner and its redstone block replaced, from the record that built the
    floor. A gym_buildings gym: its own voxel model (tools/gym_buildings.py), so nothing is copied by hand. Otherwise
    (templates) the entry's single_leader.restore, or a failure naming it."""
    x, y, z = entry["spawner"]["at"]
    if entry["spawner"].get("measured_by") == "gym_buildings":
        gb = _gym_leader_records().get(up)
        if not gb:
            raise ChallengeError("%s is measured_by gym_buildings but no data/gym_buildings record has it" % up)
        sys.path.insert(0, str(ROOT / "tools"))
        import gym_buildings as GB
        e, _r, _l = GB.build_one(GB.records(gb[0])[0][1])
        nx, ny, nz = gb[1]["spawner"]
        if not e.at(nx, ny, nz).startswith('%s{TrainerIds:["%s"]}' % (SPAWNER, up)):
            raise ChallengeError("%s's gym model has %s at its spawner %s" % (up, e.at(nx, ny, nz), (nx, ny, nz)))
        return e.at(x, y, z), e.at(x, y - 1, z)
    r = (entry.get("single_leader") or {}).get("restore") or {}
    if not (r.get("floor") and r.get("under")):
        raise ChallengeError("%s is in single_leader.rollout from a template: add bosses.%s.single_leader.restore "
                             "{floor, under}, measured from its template" % (up, up))
    return r["floor"], r["under"]


def retire_lines(up, cid, entry):
    """Once, from reapply step R17L: the second spawner at its recorded position (bosses[].spawner.at) back to the
    floor it replaced, its redstone block back to what was under it, and any standing <id>_challenge trainer near it
    removed, never in a battle and never while a player is near (with nobody near the swap holds the one leader at
    the Normal id, so a Challenge-id trainer then is the second spawner's). Every line tests the block first: a
    world that never had the second spawner is left alone."""
    x, y, z = entry["spawner"]["at"]
    floor, under = restore_blocks(up, entry)
    has = 'if block %d %d %d %s{TrainerIds:["%s"]}' % (x, y, z, SPAWNER, cid)
    # The kills run FIRST and only while the second spawner still stands (`has`), so a re-run kills nothing (audit
    # P1:retire_kills). In R17L's forceload wait the trainers cycle's nobody-near line renames the old Challenge
    # trainer to the Normal id before the retire runs (audit P1:retire), so a Challenge-id-only kill can leave two
    # Normal leaders: keep the trainer nearest the one spawner and remove any other (2026-10-07 integration fix).
    # Never in a battle, never with a player near.
    nx, ny, nz = normal_seat(up, entry)
    # nobody within reach of EITHER seat: the swap follows players within reach of the one spawner, so the guard's
    # radius from the old seat is reach + the distance between the seats (A1 audit P1:retire_kills, 2026-10-07)
    gap = ((x - nx) ** 2 + (y - ny) ** 2 + (z - nz) ** 2) ** 0.5
    near = "positioned %d.5 %d %d.5 unless entity @a[distance=..%g]" % (x, y, z, reach() + math.ceil(gap))
    sel = 'type=rctmod:trainer,distance=..%d,nbt={TrainerId:"%s",InBattle:0b}'
    # The one leader is KEPT whichever id it carries (review N115 trap a, 2026-10-09): for up to one cycle (10 ticks)
    # after a Challenge player leaves reach or a battle ends, it still carries the Challenge id with nobody near, and
    # the Challenge-id kill would take it. So every trainer of either id by the one spawner is a candidate, in a
    # battle or not, the nearest is kept, and a kept leader on the Challenge id is first put back on the Normal id,
    # spawner then trainer (single_lines' order), which is what the cycle's nobody-near lines do on their next run.
    # The kills then cannot reach it: it is on the Normal id and carries the keep tag.
    cand = "cobblers_leader_candidate"
    pick = "%s %s positioned %d.5 %d %d.5 as @e[type=rctmod:trainer,distance=..%d,%%s]" % (has, near, nx, ny, nz, SEAT_BOX)
    kept = '%s %s as @e[type=rctmod:trainer,tag=cobblers_keep_leader,nbt={TrainerId:"%s",InBattle:0b},limit=1]' % (
        has, near, cid)
    return [
        "# %s: retire the second spawner at (%d, %d, %d) now that %s stands as one leader (docs/mechanics/"
        "ONE_LEADER_SWAP.md); run once by reapply step R17L with the chunks held" % (cid, x, y, z, up),
        "# chunks-loaded-by: tools/reapply.py R17L (retire_hold's forceload of the seat box)",
        "execute %s run tag @s add %s" % (pick % ('nbt={TrainerId:"%s"}' % up), cand),
        "execute %s run tag @s add %s" % (pick % ('nbt={TrainerId:"%s"}' % cid), cand),
        "execute %s run tag @s add cobblers_keep_leader" % (pick % ("tag=%s,sort=nearest,limit=1" % cand)),
        'execute %s if block %d %d %d %s{TrainerIds:["%s"]} run data merge block %d %d %d {TrainerIds:["%s"]}'
        % (kept, nx, ny, nz, SPAWNER, cid, nx, ny, nz, up),
        'execute %s run data merge entity @s {TrainerId:"%s"}' % (kept, up),
        "execute %s %s run kill @e[%s]" % (has, near, sel % (SEAT_BOX, cid)),
        "execute %s %s run kill @e[%s,tag=!cobblers_keep_leader]" % (has, near, sel % (SEAT_BOX, up)),
        "tag @e[type=rctmod:trainer,tag=cobblers_keep_leader] remove cobblers_keep_leader",
        "tag @e[type=rctmod:trainer,tag=%s] remove %s" % (cand, cand),
        # The setblocks wait for the same player guard as the kills (review N115 trap b, 2026-10-09): with a player
        # near, the kills are skipped, and a setblock that still ran would leave the old trainer standing with no
        # spawner and no later run able to reach it, since every line tests `has`. Now nothing runs, and the next
        # re-apply's R17L, with nobody near, does all of it.
        "execute %s %s if block %d %d %d minecraft:redstone_block run setblock %d %d %d %s" % (
            has, near, x, y - 1, z, x, y - 1, z, under),
        "execute %s %s run setblock %d %d %d %s" % (has, near, x, y, z, floor),
    ]


def move_of(up, entry):
    """A one-leader boss whose ONE spawner moves (data/challenge_mode.json bosses.<id>.single_leader.move): the
    owner's 2026-10-09 decision for two League storeys inside each other's swap reach, measured by
    tools/league_separation.py. None for every other boss. A move names from, to and from_restore, or fails."""
    mv = (entry.get("single_leader") or {}).get("move")
    if not mv:
        return None
    for k in ("from", "to", "from_restore"):
        if not mv.get(k):
            raise ChallengeError("%s: single_leader.move needs %s" % (up, k))
    if tuple(mv["from"]) == tuple(mv["to"]):
        raise ChallengeError("%s: single_leader.move goes nowhere" % up)
    return mv


def move_lines(up, cid, entry):
    """Once, from reapply step R17L after the boss's retire: the ONE spawner from move.from to move.to. The new
    cell gets a redstone block under it and the spawner over it with the Normal id; then the old cell gets
    move.from_restore (the template's floor there; the template's redstone block under it stays). Every line first
    tests that the old cell still holds a spawner, so a re-run, or a world that never had it, changes nothing; and
    the last line also tests that the new spawner stands, so the old one is never removed without it.

    Never with a player within reach of either cell (no battle can start with the old leader or the new one) and
    never while either id is in a battle by the old cell. Kills nothing: the old cell's standing trainer is removed
    by the retire just before, which kills the Normal-id trainers by the retired cell other than the one nearest
    the new spawner (retire_lines). NOT covered: a world with no second spawner (a fresh export) whose old spawner
    had already spawned its trainer -- the retire does nothing there, so that trainer stays, away from the swap."""
    mv = move_of(up, entry)
    ox, oy, oz = mv["from"]
    nx, ny, nz = mv["to"]
    r = "%g" % reach()
    old = "if block %d %d %d %s" % (ox, oy, oz, SPAWNER)
    busy = " ".join('unless entity @e[type=rctmod:trainer,x=%d.5,y=%d,z=%d.5,distance=..%d,nbt={TrainerId:"%s",'
                    'InBattle:1b}]' % (ox, oy, oz, SEAT_BOX, i) for i in (up, cid))
    guard = ("positioned %d.5 %d %d.5 unless entity @a[distance=..%s] positioned %d.5 %d %d.5 unless entity "
             "@a[distance=..%s] %s" % (ox, oy, oz, r, nx, ny, nz, r, busy))
    return [
        "# %s: the one spawner moves from (%d, %d, %d) to (%d, %d, %d) (data/challenge_mode.json bosses.%s."
        "single_leader.move; tools/league_separation.py); run by reapply step R17L after retire_%s" % (
            up, ox, oy, oz, nx, ny, nz, up, cid),
        "# chunks-loaded-by: tools/reapply.py R17L (retire_hold's forceload of the seat box)",
        "execute %s %s run setblock %d %d %d minecraft:redstone_block" % (old, guard, nx, ny - 1, nz),
        'execute %s %s run setblock %d %d %d %s{TrainerIds:["%s"]}' % (old, guard, nx, ny, nz, SPAWNER, up),
        'execute %s if block %d %d %d %s{TrainerIds:["%s"]} %s run setblock %d %d %d %s' % (
            old, nx, ny, nz, SPAWNER, up, guard, ox, oy, oz, mv["from_restore"]),
    ]


def retire_hold(overrides=None):
    """[(x0, z0, x1, z1)] the chunks R17L forceloads: the seat box around each rollout boss's second spawner and its
    Normal spawner (and, for a boss whose spawner moves, its old cell), so the block tests and the entity selectors
    see loaded chunks."""
    d = doc()
    out = []
    for up in sorted(rollout()):
        e = d["bosses"][up]
        xs, zs = [], []
        mv = move_of(up, e)
        for (x, _y, z) in (tuple(e["spawner"]["at"]), normal_seat(up, e)) + ((tuple(mv["from"]),) if mv else ()):
            xs += [x - SEAT_BOX, x + SEAT_BOX]
            zs += [z - SEAT_BOX, z + SEAT_BOX]
        out.append((min(xs), min(zs), max(xs), max(zs)))
    return out


def retire_functions():
    """The function ids R17L runs, in rollout order: each boss's retire, then its move if its spawner moves."""
    d, out = doc(), []
    for up in sorted(rollout()):
        out.append("%s:trainers/challenge/retire_%s" % (NS, challenge_id(up)))
        if move_of(up, d["bosses"][up]):
            out.append("%s:trainers/challenge/move_%s" % (NS, up))
    return out


def single_leader_verify(rc):
    """Read back from the world, after R17L, for each rollout boss: the second spawner gone, the one spawner present,
    no Challenge-id trainer by the old cell, and -- only while no player is near, which it reports -- the spawner
    reading the Normal id. `rc` sends one command and returns its text; `execute if` answers "Test passed" or
    "Test failed". Returns the problems."""
    d, problems = doc(), []
    for up in sorted(rollout()):
        e, cid = d["bosses"][up], challenge_id(up)
        sx, sy, sz = e["spawner"]["at"]
        nx, ny, nz = normal_seat(up, e)
        if "passed" in rc("execute if block %d %d %d %s" % (sx, sy, sz, SPAWNER)):
            problems.append("%s: the second spawner at (%d, %d, %d) is still there" % (cid, sx, sy, sz))
        mv = move_of(up, e)
        if mv and "passed" in rc("execute if block %d %d %d %s" % (tuple(mv["from"]) + (SPAWNER,))):
            problems.append("%s: the spawner has not moved: (%d, %d, %d) still holds one" % ((up,) + tuple(mv["from"])))
        if "passed" not in rc("execute if block %d %d %d %s" % (nx, ny, nz, SPAWNER)):
            problems.append("%s: no spawner at its seat (%d, %d, %d)" % (up, nx, ny, nz))
            continue
        if "passed" in rc("execute positioned %d.5 %d %d.5 if entity @a[distance=..%g]" % (nx, ny, nz, reach())):
            problems.append("%s: a player is within %g, so the Normal id with nobody near was NOT checked" % (up, reach()))
            continue
        if "passed" not in rc('execute if block %d %d %d %s{TrainerIds:["%s"]}' % (nx, ny, nz, SPAWNER, up)):
            problems.append("%s: with nobody near, the spawner at (%d, %d, %d) does not read TrainerIds [%s]"
                            % (up, nx, ny, nz, up))
        if "passed" in rc('execute if entity @e[type=rctmod:trainer,x=%d.5,y=%d,z=%d.5,distance=..%d,'
                          'nbt={TrainerId:"%s"}]' % (sx, sy, sz, SEAT_BOX, cid)):
            problems.append("%s: a trainer still carries the Challenge id with nobody near" % cid)
        # Two leaders of this boss standing at once (the rename race, audit P1:retire): `execute if entity` answers
        # "Test passed, count: N".
        both = rc('execute if entity @e[type=rctmod:trainer,x=%d.5,y=%d,z=%d.5,distance=..%d,nbt={TrainerId:"%s"}]'
                  % (nx, ny, nz, SEAT_BOX, up))
        m = re.search(r"count:\s*(\d+)", both or "")
        if m and int(m.group(1)) > 1:
            problems.append("%s: %s trainers carry the Normal id near its seat" % (up, m.group(1)))
    return problems


# ------------------------------------------------------------------------------------------------ routes
def has_challenge(rec):
    m = (rec.get("modes") or {}).get("challenge")
    return bool(m and m.get("rct") and m["rct"].get("team"))


def route_files(tid, rec, normal_mob, normal_dialog):
    """The Challenge copy of one seated trainer: the same mob and lines, its own team and series."""
    cid = challenge_id(tid)
    rct = challenge_rct(rec)
    mob = dict(normal_mob)
    mob["series"] = [series_id()]
    return cid, {
        "data/rctmod/trainers/%s.json" % cid: {k: rct[k] for k in ("name", "ai", "battleRules", "bag", "team") if k in rct},
        "data/rctmod/mobs/trainers/single/%s.json" % cid: mob,
        "data/rctmod/dialogs/trainers/single/%s.json" % cid: normal_dialog,
        "data/rctmod/loot_table/trainers/single/%s.json" % cid: {"pools": []},
    }


def swap_lines(tid, seat, near):
    """The one entity at a seat carries the mode of the nearest player within `near`: the Challenge id while that
    player has the mode tag, the Normal id otherwise and when nobody is near. Never during a battle (InBattle:0b).
    ASSUMED: a data merge of TrainerId swaps the team (RCT_PER_PLAYER_MODE.md experiment E7)."""
    cid, tag = challenge_id(tid), mode_tag()
    x, y, z = seat
    sel = lambda i: ('@e[type=rctmod:trainer,x=%d.5,y=%d,z=%d.5,distance=..24,nbt={TrainerId:"%s",InBattle:0b}]'
                     % (x, y, z, i))
    here = lambda i: '@e[type=rctmod:trainer,distance=..0.5,nbt={TrainerId:"%s",InBattle:0b},limit=1]' % i
    return [
        "# %s: the mode of the nearest player decides which team stands here" % tid,
        "execute as %s at @s as @p[distance=..%s] if entity @s[tag=%s] run data merge entity %s {TrainerId:\"%s\"}"
        % (sel(tid), near, tag, here(tid), cid),
        "execute as %s at @s as @p[distance=..%s] unless entity @s[tag=%s] run data merge entity %s {TrainerId:\"%s\"}"
        % (sel(cid), near, tag, here(cid), tid),
        "execute as %s at @s unless entity @a[distance=..%s] run data merge entity @s {TrainerId:\"%s\"}"
        % (sel(cid), near, tid),
    ]


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true", help="validate and summarise; write nothing (the default)")
    p.parse_args(argv)
    sys.path.insert(0, str(ROOT / "tools"))
    import route_trainers as RT
    over, _held = RT.overrides()
    files = boss_files(over, RT.with_refusals, RT.league_lines)
    recs, seats, _f = RT.load()
    routes = [s["id"] for s in seats if s["id"] in recs and has_challenge(recs[s["id"]])]
    places = [k for k in files if "/trainers/challenge/place_" in k]
    retires = [k for k in files if "/trainers/challenge/retire_" in k]
    print("series %s; %d Challenge bosses: %d with a second spawner, %d as one leader (%s); %d seated trainers swap "
          "to a Challenge id" % (series_id(), len(boss_ids(over)), len(places), len(retires),
                                 ", ".join(sorted(rollout())) or "none", len(routes)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
