#!/usr/bin/env python
"""The coast fringe: land on the coast that no sub-region roster reaches, given to the nearest sub-region (U61, N2).

Why: the sub-region polygons in data/regions.json were drawn to the coast of the heightmap before the water export
(tools/water_shape.py, heightmap 0d9b5f1e -> d1bc68d3), which moved coasts outward; and a polygon reaches the world
only as the 32-block cells whose CENTRE it holds (tools/subregion_boxes.py rasterise), so a polygon drawn to the
water's edge loses up to half a cell there too. Measured 2026-10-09 (`--report`, heightmap d1bc68d3): of 1,581,881
land columns within 32 blocks of open sea, 805,154 had no grounded campaign entry over them (spawn-free zones and
marine-only columns not counted); with this fringe, 1,621. Only the
owner edits polygons (docs/STATE.md file ownership), so this does not move one: it records, per sub-region, the extra
coast cells its base roster covers, and tools/compile_spawns.py lays that roster over them (coast_fringe_boxes).

The rule (no number tuned to make anything pass; every cell is on the 32-block sub-region grid of compile_spawns):
  land        a column whose ground round(h) >= the sea level (data/world.json vertical.sea_level; the same land as
              compile_spawns.marine_bands' measurement)
  open sea    round(h) < sea level, connected to the map's edge (tools/coast_measure.py open_sea on rounded ground)
  free cell   a cell no sub-region raster holds, whose centre no route corridor box covers, that no waterway or
              spawn-free zone touches and no marine band holds: the cells a sub-region roster could take without
              doubling another table's weights (the exclusions compile_subregion and marine_bands already apply)
  coast cell  a free cell holding a land column 4-adjacent to open sea
  ring        a free cell holding land, 8-adjacent to a coast cell (ring_cells 1): the land behind a strip where the
              coast moved past a cell's width. One ring is a CHOICE, recorded here with its measured effect
              (owner to review), not a derived number
  owner       each fringe cell goes to the sub-region whose polygon edge is nearest the cell's centre (ties: lowest
              id); a fringe cell gets its base roster only, never a heart

Not covered, and said so: lake shores (water not connected to the map's edge), coast cells a marine band holds (the
marine roster stays there; their land has no grounded table), and inland land no table reaches -- all measured and
reported by `--report`.

  python tools/coast_fringe.py              # write data/coast_fringe.json
  python tools/coast_fringe.py --check      # exit 1 if data/coast_fringe.json is not what today's inputs give
  python tools/coast_fringe.py --report     # the measured cover before and after, without writing

Ownership: data/coast_fringe.json is GENERATED by this tool (never hand-edit); the polygons stay the owner's.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

import coast_measure
import compile_spawns as CS
import subregion_boxes
import terrain as T

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "coast_fringe.json"
GRID = CS.SUBREGION_GRID
RING_CELLS = 1


polygons_sha = CS.polygons_sha


def load_inputs(source_root=None):
    h, world = T.load(str(ROOT / "data" / "world.json"), source_root)
    rd = lambda n: json.loads((ROOT / "data" / n).read_text(encoding="utf-8"))
    spawns, routes, regions = rd("spawns.json"), rd("routes.json"), rd("regions.json")
    wpath = ROOT / "data" / "waterways.json"
    water = CS.water_boxes_of(json.loads(wpath.read_text(encoding="utf-8"))) if wpath.is_file() else []
    return h, world, spawns, routes, regions, water


def ground_masks(h, world):
    sea = T.sea_level(world)
    g = np.round(h)
    land = g >= sea
    osea = coast_measure.open_sea(g, sea)
    adj = np.zeros_like(osea)
    adj[1:] |= osea[:-1]
    adj[:-1] |= osea[1:]
    adj[:, 1:] |= osea[:, :-1]
    adj[:, :-1] |= osea[:, 1:]
    return land, land & adj


def per_cell(mask):
    n = mask.shape[0] // GRID
    return mask[:n * GRID, :n * GRID].reshape(n, GRID, n, GRID).any(axis=(1, 3))


def free_cells(n, spawns, routes, regions, water):
    """(n, n) bool [gz, gx]: the cells a sub-region roster could take (module docstring, 'free cell')."""
    taken = np.zeros((n, n), dtype=bool)
    for sub in regions["subregions"]:
        for gx, gz in CS._grid_cells_of(sub, GRID):
            if 0 <= gx < n and 0 <= gz < n:
                taken[gz, gx] = True
    for gx, gz in CS.marine_cells(spawns, regions, routes, water, GRID):
        if 0 <= gx < n and 0 <= gz < n:
            taken[gz, gx] = True
    centre = (np.arange(n) * GRID + GRID / 2.0)
    for x0, x1, z0, z1 in subregion_boxes.route_boxes(routes):
        xs = (centre >= x0) & (centre <= x1)
        zs = (centre >= z0) & (centre <= z1)
        taken[np.ix_(zs, xs)] = True
    lo = np.arange(n) * GRID
    hi = lo + GRID - 1
    for x0, x1, z0, z1 in list(water) + CS.spawn_free_zones():
        xs = ~((x1 < lo) | (hi < x0))
        zs = ~((z1 < lo) | (hi < z0))
        taken[np.ix_(zs, xs)] = True
    return ~taken


def nearest_owner(regions, x, z):
    best = None
    for s in sorted(regions["subregions"], key=lambda s: s["id"]):
        for p in s["polygons"]:
            a = np.asarray(p, dtype=float)
            b = np.roll(a, -1, axis=0)
            ab = b - a
            ap = np.array([x, z]) - a
            t = np.clip((ap * ab).sum(1) / np.maximum((ab * ab).sum(1), 1e-12), 0.0, 1.0)
            d = float(np.hypot(*(a + ab * t[:, None] - [x, z]).T).min())
            if best is None or d < best[0]:
                best = (d, s["id"])
    return best


def plan(source_root=None):
    h, world, spawns, routes, regions, water = load_inputs(source_root)
    land, coast = ground_masks(h, world)
    n = land.shape[0] // GRID
    free = free_cells(n, spawns, routes, regions, water)
    has_land = per_cell(land)
    seed = free & per_cell(coast)
    ring = seed.copy()
    for _ in range(RING_CELLS):
        grown = ring.copy()
        grown[1:] |= ring[:-1]
        grown[:-1] |= ring[1:]
        grown[:, 1:] |= ring[:, :-1]
        grown[:, :-1] |= ring[:, 1:]
        grown[1:, 1:] |= ring[:-1, :-1]
        grown[:-1, :-1] |= ring[1:, 1:]
        grown[1:, :-1] |= ring[:-1, 1:]
        grown[:-1, 1:] |= ring[1:, :-1]
        ring = grown & free & has_land
    fringe = seed | ring
    cells, far = {}, []
    for gz, gx in zip(*np.nonzero(fringe)):
        d, sid = nearest_owner(regions, gx * GRID + GRID / 2.0, gz * GRID + GRID / 2.0)
        cells.setdefault(sid, []).append([int(gx * GRID), int(gz * GRID)])
        far.append(d)
    for v in cells.values():
        v.sort()
    stats = {"coast_cells": int(seed.sum()), "ring_cells": int((fringe & ~seed).sum()), "fringe_cells": int(fringe.sum()),
             "owner_distance_blocks_p50_p90_max": [round(float(q), 1) for q in np.percentile(far, [50, 90, 100])] if far else []}
    doc = {
        "schema": "cobblers.coast_fringe.v1",
        "generated_by": "python tools/coast_fringe.py (never hand-edit; the rule is the tool's docstring)",
        "why": "U61/N2: the sub-region polygons predate the water export, so coast land outside them had no campaign "
               "pool. Polygons are the owner's; this gives each sub-region the coast cells nearest it, base roster "
               "only (tools/compile_spawns.py coast_fringe_boxes re-applies every exclusion from today's data).",
        "grid": GRID,
        "ring_cells": RING_CELLS,
        "ring_why": "a choice, not a derived number: the land behind a coast cell where the coast moved more than a "
                    "cell's width; measured 2026-10-09 (--report) coast land (within 32 of open sea) with no grounded "
                    "table: 805,154 columns with no fringe, 125,785 with coast cells alone, 1,621 with one ring. "
                    "Owner to review.",
        "heightmap_sha256": (world.get("heightmap") or {}).get("sha256"),
        "regions_polygons_sha256": polygons_sha(regions),
        "stats": stats,
        "cells": dict(sorted(cells.items())),
    }
    return doc


def cover_report(source_root=None, doc=None):
    """Land columns within 32 blocks of open sea under no grounded box, without and with the fringe (the compiled
    sub-region, route and waterway boxes, recompiled in memory; marine boxes counted separately)."""
    h, world, spawns, routes, regions, water = load_inputs(source_root)
    land, coast = ground_masks(h, world)
    N = land.shape[0]
    sea = T.sea_level(world)
    osea = coast_measure.open_sea(np.round(h), sea)
    dist = np.full(land.shape, 999, dtype=np.int16)
    cur = osea.copy()
    dist[cur] = 0
    for i in range(1, 33):
        nxt = cur.copy()
        nxt[1:] |= cur[:-1]
        nxt[:-1] |= cur[1:]
        nxt[:, 1:] |= cur[:, :-1]
        nxt[:, :-1] |= cur[:, 1:]
        dist[nxt & ~cur] = i
        cur = nxt
    near = land & (dist >= 1) & (dist <= 32)
    out = {}
    for label, fdoc in (("without", {"grid": GRID, "cells": {}}), ("with", doc)):
        files, _, _ = CS.build(spawns, routes)
        sf, _ = CS.build_subregions(spawns, routes, regions, GRID, water, fringe_doc=fdoc)
        files.update(sf)
        wpath = ROOT / "data" / "waterways.json"
        if wpath.is_file():
            wf, _ = CS.build_waterways(spawns, json.loads(wpath.read_text(encoding="utf-8")), routes=routes)
            files.update(wf)
        mf, _ = CS.build_marine(spawns, regions, routes, water)
        grounded = np.zeros_like(land)
        marine = np.zeros_like(land)
        for rel, text in list(files.items()) + list(mf.items()):
            if "/spawn_pool_world/" not in rel:
                continue
            for s in json.loads(text)["spawns"]:
                c = s.get("condition") or {}
                if "minX" not in c:
                    continue
                # clamped to the map: a marine box past the edge (negative maxX) would otherwise slice from the end
                z0, z1 = max(0, c["minZ"]), min(N - 1, c["maxZ"])
                x0, x1 = max(0, c["minX"]), min(N - 1, c["maxX"])
                if z1 < z0 or x1 < x0:
                    continue
                sl = (slice(z0, z1 + 1), slice(x0, x1 + 1))
                if "/marine/" in rel:
                    marine[sl] = True
                elif s.get("spawnablePositionType") == "grounded":
                    grounded[sl] = True
        free = np.zeros_like(land)
        for x0, x1, z0, z1 in CS.spawn_free_zones():
            free[max(0, z0):z1 + 1, max(0, x0):x1 + 1] = True
        gap = near & ~grounded & ~free
        out[label] = {"coast_land_no_grounded_table": int((gap & ~marine).sum()),
                      "coast_land_under_marine_only": int((gap & marine).sum())}
    out["coast_land_columns"] = int(near.sum())
    return out


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--source-root", default=None)
    p.add_argument("--check", action="store_true", help="exit 1 if data/coast_fringe.json is stale")
    p.add_argument("--report", action="store_true", help="measure the coast's cover without and with the fringe")
    a = p.parse_args(argv)
    doc = plan(a.source_root)
    if a.check:
        old = json.loads(OUT.read_text(encoding="utf-8")) if OUT.is_file() else None
        if old != doc:
            print("coast_fringe: data/coast_fringe.json is stale (or missing): run python tools/coast_fringe.py")
            return 1
        print("coast_fringe: current (%d cells)" % doc["stats"]["fringe_cells"])
        return 0
    if a.report:
        print(json.dumps({"stats": doc["stats"], "cover": cover_report(a.source_root, doc)}, indent=1))
        return 0
    OUT.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8", newline="\n")
    print("coast_fringe: wrote %s: %d coast + %d ring cells to %d sub-regions; owner distance p50/p90/max %s"
          % (OUT.relative_to(ROOT), doc["stats"]["coast_cells"], doc["stats"]["ring_cells"], len(doc["cells"]),
             doc["stats"]["owner_distance_blocks_p50_p90_max"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
