#!/usr/bin/env python
"""The Night Shift dungeon's probe pack: staging-only proofs that can kill a mechanism before the engine is built.

  python tools/dungeon_probes.py                 # write build/datapacks/cobblers_dg_probes
  python tools/dungeon_probes.py --out <dir>

docs/mechanics/DUNGEONS.md section 14 lists the unknowns. This pack carries one self-contained probe for each of P1,
B1, B2, B3, R1, R2, F1, L1, L2, C1, XT1, V1, I2, LO1 and SG1 (DX1 waits for the run tag, E1). Each probe has:

  - its own functions under cobblers_dg_probes:<id>/ (setup, ready, cleanup and its own steps),
  - its own scoreboard objectives, all named dp<id>.<name>,
  - its own area in cobblers:pocket (data/dungeon_probes.json row and i2's strip), disjoint from every other probe,
    from the portals' rescue box, from Entei's band and from the dungeon slots' rows (problems() refuses an overlap),
  - its own explicit reading, in experiments/EXP-069 .. EXP-083.

STAGING ONLY. The pack is world-local and installed by hand into the staging world's datapacks/ folder. It is never in
the players' pack and never in tools/reapply.py's install lists (tests/test_dungeon_probes.py holds both). It has NO
load or tick tag: nothing runs until the session calls a probe's setup over RCON, and everything works after a plain
restart (a 12G staging server cannot /reload this build, review N111). The only things it does on its own are its
three Cobblemon callbacks, and each of them acts only on an entity carrying that probe's own tag (P1's on a Pokemon
standing inside P1's box in the pocket).

Looking before acting (review N155, tools/chunk_look.py). Every probe's setup force-loads its chunks and HOLDS them
until its cleanup, and schedules <id>/ready BLIND_TICKS (300) later. ready kills whatever tagged entities an earlier
run left (their chunks have been loaded the whole window), then opens the probe. Every function that summons refuses
until ready has run. A probe's first run has nothing saved to look for, so the blind wait is the whole look; chunk_look's
chain is not used because it releases its forceload when it is done, and a probe must keep its chunks for its life.
cleanup kills at once and again BLIND_TICKS later (chunk_look.sweep's repeat over the same window) before it releases
the chunks. After a server restart, run the probe's setup again before summoning anything: forced chunks reload and
their entities arrive late.

Ownership: data/dungeon_probes.json is the source; the pack is generated into build/ (gitignored); the tests are
tests/test_dungeon_probes.py, written to check isolation and validity only (they prove nothing about behaviour).
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import function_limits  # noqa: E402
import chunk_look  # noqa: E402  (BLIND_TICKS: the blind look's length)

DATA = ROOT / "data" / "dungeon_probes.json"
PORTALS = ROOT / "data" / "portals.json"
ENTEI = ROOT / "data" / "entei_boss.json"
BLACKOUT = ROOT / "data" / "blackout.json"
DEFAULT_OUT = ROOT / "build" / "datapacks" / "cobblers_dg_probes"
SCHEMA = "cobblers.dungeon_probes/1"
PACK_FORMAT = 48  # Minecraft 1.21.1
NS = "cobblers_dg_probes"
READY_TICKS = chunk_look.BLIND_TICKS
CALLBACK = "data/cobblemon/callbacks/%s/cobblers_dg_probes_%s.molang"
OBJ_RE = re.compile(r"^dp[a-z0-9]+\.[a-z0-9_]+$")
ENTEI_SWEEP_MARGIN = 64   # tools/entei_boss.py band_box(margin=64): the keeper ejects anyone in it
DUNGEON_ROWS_FROM_Z = 1024  # DUNGEONS.md section 1 (relayed there from DM 6): the slots' rows start at z 1,024
# the dormant dressing proven across a restart (EXP-023, EXP-046), as tools/legendaries.py DORMANT writes it
DORMANT = ('{Unbattleable:1b,NoAI:1b,NoGravity:1b,PoseType:"SLEEP",RecalculatePose:0b,HideLabel:1b,'
           'PersistenceRequired:1b,Silent:1b}')
NPC_RESOURCE = "cobblemon:standard"   # tools/compile_dialogue.py NPC_RESOURCE: renders as Cobblemon's trainer
HEAD = "# Generated by tools/dungeon_probes.py from data/dungeon_probes.json; STAGING ONLY; never edit (build/)."


class ProbeError(ValueError):
    pass


def load(path=DATA):
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    if doc.get("schema") != SCHEMA:
        raise ProbeError("%s: schema must be %s" % (path, SCHEMA))
    return doc


def _j(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def probe(doc, pid):
    for p in doc["probes"]:
        if p["id"] == pid:
            return p
    raise ProbeError("no probe %r" % pid)


# ------------------------------------------------------------------------------------------------- geometry


def row_ids(doc):
    return [p["id"] for p in doc["probes"] if p["id"] != "i2"]


def area(doc, pid):
    """(x0, z0, x1, z1): the probe's whole area. i2 has its own strip; every other probe a slot in the row."""
    if pid == "i2":
        s = probe(doc, "i2")["strip"]
        return s["x0"], s["z0"], s["x0"] + s["length"] - 1, s["z0"] + s["width"] - 1
    r = doc["row"]
    x0 = r["origin_x"] + row_ids(doc).index(pid) * r["spacing"]
    return x0, r["z_min"], x0 + r["spacing"] - 1, r["z_max"]


def origin(doc, pid):
    """The probe's working centre (ox, floor_y, oz): 32 in from the area's low-x edge, on the row's middle z."""
    x0, z0, _x1, z1 = area(doc, pid)
    return x0 + 32, doc["floor_y"], (z0 + z1 + 1) // 2


def foreign_boxes(doc, portals_doc=None, entei_doc=None):
    """{name: (x0, z0, x1, z1)} of everything a probe must stay out of, each from its own data file."""
    portals_doc = portals_doc if portals_doc is not None else _j(PORTALS)
    entei_doc = entei_doc if entei_doc is not None else _j(ENTEI)
    pp = portals_doc["pocket"]
    # tools/entei_boss.py's own check, conservative: the rescue box's whole z range, on every x
    rescue = (-10 ** 6, min(pp["bands"].values()) - pp["rescue_margin"],
              10 ** 6, max(pp["bands"].values()) + pp["rescue_margin"])
    ep, half = entei_doc["pocket"], entei_doc["room"]["half"]
    xs = [ep["origin"][0] + k * ep["spacing"] for k in range(ep["slots"])]
    m = ENTEI_SWEEP_MARGIN
    entei = (min(xs) - half - m, ep["origin"][1] - half - m, max(xs) + half + m, ep["origin"][1] + half + m)
    rows = (-10 ** 6, DUNGEON_ROWS_FROM_Z, 10 ** 6, 10 ** 6)
    return {"portals rescue box": rescue, "Entei's band": entei, "dungeon slot rows": rows}


def _meets(a, b):
    return not (a[2] < b[0] or b[2] < a[0] or a[3] < b[1] or b[3] < a[1])


def problems(doc, portals_doc=None, entei_doc=None):
    bad = []
    portals_doc = portals_doc if portals_doc is not None else _j(PORTALS)
    if doc["dimension"] != portals_doc["pocket"]["dimension"]:
        bad.append("dimension %s is not data/portals.json pocket.dimension %s"
                   % (doc["dimension"], portals_doc["pocket"]["dimension"]))
    ids = [p["id"] for p in doc["probes"]]
    if len(set(ids)) != len(ids):
        bad.append("probe ids repeat")
    want = ["p1", "b1", "b2", "b3", "r1", "r2", "f1", "l1", "l2", "c1", "xt1", "v1", "i2", "lo1", "sg1"]
    if ids != want:
        bad.append("probes must be %s in that order (the EXP numbering follows it), got %s" % (want, ids))
    for n, p in enumerate(doc["probes"]):
        if p["exp"] != "EXP-%03d" % (69 + n):
            bad.append("%s: exp %s, expected EXP-%03d" % (p["id"], p["exp"], 69 + n))
    lo, hi = doc["border"][0] + doc["border_margin"], doc["border"][1] - doc["border_margin"]
    boxes = {pid: area(doc, pid) for pid in ids}
    foreign = foreign_boxes(doc, portals_doc, entei_doc)
    for pid, b in boxes.items():
        if not (lo <= b[0] and b[2] <= hi and lo <= b[1] and b[3] <= hi):
            bad.append("%s: area %s is outside the border margin %d..%d" % (pid, b, lo, hi))
        for name, f in foreign.items():
            if _meets(b, f):
                bad.append("%s: area %s meets %s %s" % (pid, b, name, f))
    for i, a in enumerate(ids):
        for b in ids[i + 1:]:
            if _meets(boxes[a], boxes[b]):
                bad.append("areas of %s and %s overlap" % (a, b))
    return bad


# ------------------------------------------------------------------------------------------------- helpers


def F(pid, name):
    return "%s:%s/%s" % (NS, pid, name)


def O(pid, name):
    o = "dp%s.%s" % (pid, name)
    if len(o) > 16 or not OBJ_RE.match(o):
        raise ProbeError("objective %r is not a dp<id>.<name> of at most 16 characters" % o)
    return o


def fill(x0, y0, z0, x1, y1, z1, block, mode=""):
    return "fill %d %d %d %d %d %d %s%s" % (x0, y0, z0, x1, y1, z1, block, (" " + mode) if mode else "")


def setb(x, y, z, block):
    return "setblock %d %d %d %s" % (x, y, z, block)


def sel(box, extra=""):
    x0, y0, z0, x1, y1, z1 = box
    return "x=%d,y=%d,z=%d,dx=%d,dy=%d,dz=%d%s" % (x0, y0, z0, x1 - x0, y1 - y0, z1 - z0, ("," + extra) if extra else "")


def text(msg, colour="gray"):
    return json.dumps({"text": msg, "color": colour}, ensure_ascii=False)


def pen(cx, cz, half, y, floor="minecraft:smooth_stone", wall="minecraft:glass", h=3):
    """A floor of (2 half + 1)^2 at y - 1 and a wall ring h high round it: nobody walks off into the 96-block drop."""
    a, b = half + 1, y + h - 1
    lines = [fill(cx - a, y - 1, cz - a, cx + a, y - 1, cz + a, floor),
             fill(cx - a, y, cz - a, cx + a, b, cz - a, wall), fill(cx - a, y, cz + a, cx + a, b, cz + a, wall),
             fill(cx - a, y, cz - a, cx - a, b, cz + a, wall), fill(cx + a, y, cz - a, cx + a, b, cz + a, wall)]
    return lines, (cx - a, y - 1, cz - a, cx + a, b, cz + a)


def tube(x, z, y0, y1, wall="minecraft:glass"):
    """A 1 x 1 glass tube round column (x, z) from y0 to y1."""
    return [fill(x - 1, y0, z - 1, x + 1, y1, z - 1, wall), fill(x - 1, y0, z + 1, x + 1, y1, z + 1, wall),
            setb(x - 1, y0, z, wall) if y0 == y1 else fill(x - 1, y0, z, x - 1, y1, z, wall),
            setb(x + 1, y0, z, wall) if y0 == y1 else fill(x + 1, y0, z, x + 1, y1, z, wall)]


def npc_class(name, team, skill=3):
    """The shape of Heaven's Arena's classes (tools/arena_runtime.py npc_class, the probe class that passed in game on
    2026-10-03) with a "simple" party, the form Cobblemon's own data/cobblemon/npcs/standard.json uses in the 1.8.0
    jar: a list of properties strings."""
    return {"hitbox": "player", "names": [name], "resourceIdentifier": NPC_RESOURCE, "canDespawn": False,
            "isInvulnerable": True, "isMovable": False, "isLeashable": False, "allowProjectileHits": False,
            "autoHealParty": True, "battleConfiguration": {"canChallenge": False}, "skill": skill,
            "ai": [{"type": "apply_behaviours", "presets": ["cobblemon:battler", "cobblemon:looks_at_players"]}],
            "party": {"type": "simple", "pokemon": list(team)}}


def victory_callback(pid, npc_tag, won_cmd, lost_cmd):
    """battle_victory: the arena probe's callback (PASS in game 2026-10-03, docs/research/notes/
    arena-per-player-opponents.md section 7-8), keyed on this probe's own NPC tag. won_cmd / lost_cmd are command
    tails run `as` the NPC; '%P' becomes the player's username."""
    w = won_cmd.replace("%P", "' + t.w.player.username + '")
    lo = lost_cmd.replace("%P", "' + t.p.player.username + '")
    return "\n".join([
        "'Generated by tools/dungeon_probes.py (probe %s), STAGING ONLY. Acts only on an NPC tagged %s.';" % (pid.upper(), npc_tag),
        "for_each(t.l, c.scriptable_losers, { t.l.is_npc ? { for_each(t.w, c.player_winners, {",
        "  q.run_command('execute as ' + t.l.uuid + ' if entity @s[tag=%s] run %s');" % (npc_tag, w),
        "}); }; });",
        "for_each(t.w, c.scriptable_winners, { t.w.is_npc ? { for_each(t.p, c.player_losers, {",
        "  q.run_command('execute as ' + t.w.uuid + ' if entity @s[tag=%s] run %s');" % (npc_tag, lo),
        "}); }; });", ""])


class Probe:
    """What one probe adds to the common frame."""

    def __init__(self, pid):
        self.pid = pid
        self.objs = {}          # name -> criterion, beyond st, r, rx, ry, rz
        self.build = []         # block writes, in the pocket's context, inside the held chunks
        self.boxes = []         # (x0, y0, z0, x1, y1, z1) cleared to air by cleanup; their union is force-loaded
        self.arrive = None      # (x, y, z, yaw) for enter, or None: no owner leg
        self.fns = {}           # name -> lines
        self.files = {}         # pack path -> text
        self.loops = []         # function names cleanup unschedules
        self.ready_extra = []
        self.cleanup_extra = []
        self.consts = {}        # #name -> value on dp<id>.st


def union(boxes):
    return (min(b[0] for b in boxes), min(b[1] for b in boxes), min(b[2] for b in boxes),
            max(b[3] for b in boxes), max(b[4] for b in boxes), max(b[5] for b in boxes))


def chunk_rows(x0, z0, x1, z1):
    """forceload boxes for (x0..x1, z0..z1): one per run of chunks along a chunk row, each under 256 chunks."""
    out = []
    for cz in range(z0 // 16, z1 // 16 + 1):
        a = x0 // 16
        while a <= x1 // 16:
            b = min(x1 // 16, a + function_limits.FORCELOAD_CHUNK_LIMIT - 1)
            out.append((a * 16, cz * 16, b * 16 + 15, cz * 16 + 15))
            a = b + 1
    return out


def common(doc, P):
    """setup, setup_in, ready, cleanup, cleanup_in, cleanup_end, enter, leave, go for one probe."""
    pid, dim = P.pid, doc["dimension"]
    ST, R = O(pid, "st"), O(pid, "r")
    E, M = "dp%s.e" % pid, "dp%s.m" % pid
    u = union(P.boxes)
    ebox = sel((u[0], 0, u[2], u[3], 255, u[5]))
    fl = chunk_rows(u[0], u[2], u[3], u[5])
    objs = {"st": "dummy", "r": "dummy"}
    if P.arrive:
        objs.update({"rx": "dummy", "ry": "dummy", "rz": "dummy"})
    objs.update(P.objs)
    out = {}
    out["setup"] = [
        HEAD,
        "# Over RCON: function %s. Builds probe %s in %s and opens it %d ticks later (ready)." % (F(pid, "setup"), pid.upper(), dim, READY_TICKS),
        "# Run it again after any server restart before summoning anything (forced chunks reload, entities arrive late).",
        "execute in %s run function %s" % (dim, F(pid, "setup_in")),
        "return 1"]
    out["setup_in"] = [
        HEAD,
        "# in %s (setup carries it in). The chunks are force-loaded here and HELD until cleanup_end." % dim] + [
        "forceload add %d %d %d %d" % b for b in fl] + [
        "scoreboard objectives add %s %s" % (O(pid, k), v) for k, v in objs.items()] + [
        "scoreboard players set #ready %s 0" % ST] + [
        "scoreboard players set %s %s %d" % (k, ST, v) for k, v in P.consts.items()] + P.build + [
        "schedule function %s %dt replace" % (F(pid, "ready"), READY_TICKS)]
    out["ready"] = [
        HEAD,
        "# %d ticks after setup: the held chunks' saved entities are in (tools/chunk_look.py BLIND_TICKS). Kill what an" % READY_TICKS,
        "# earlier run left (every entity this probe summons carries %s), then open the probe." % E,
        "execute in %s store result score #stale %s if entity @e[tag=%s,%s]" % (dim, R, E, ebox),
        "execute in %s run kill @e[tag=%s,%s]" % (dim, E, ebox)] + P.ready_extra + [
        "scoreboard players set #ready %s 1" % ST,
        "tellraw @a[tag=%s] %s" % (M, text("Probe %s is ready." % pid.upper()))]
    out["cleanup"] = [
        HEAD,
        "# Over RCON, after the readings are taken (this removes every %s objective, and so every reading)." % ("dp" + pid),
        "# The owner should run leave first, so their way home is still stored.",
        "execute in %s run function %s" % (dim, F(pid, "cleanup_in")),
        "return 1"]
    clear = [l for b in P.boxes for l in function_limits.split_fills([fill(*b, "minecraft:air")])]
    out["cleanup_in"] = [
        HEAD,
        "# in %s; the chunks are still held from setup_in" % dim] + [
        "schedule clear %s" % F(pid, n) for n in P.loops + ["ready"]] + [
        "scoreboard players set #ready %s 0" % ST,
        "kill @e[tag=%s,%s]" % (E, ebox),
        "kill @e[type=minecraft:item,%s]" % ebox,
        "kill @e[type=minecraft:experience_orb,%s]" % ebox] + P.cleanup_extra + [
        "# chunks-loaded-by: %s" % F(pid, "setup_in")] + clear + [
        "schedule function %s %dt replace" % (F(pid, "cleanup_end"), READY_TICKS)]
    out["cleanup_end"] = [
        HEAD,
        "# %d ticks after cleanup: the kill again over the same window (tools/chunk_look.py sweep), then release." % READY_TICKS,
        "execute in %s run kill @e[tag=%s,%s]" % (dim, E, ebox),
        "tag @a remove %s" % M] + [
        "execute in %s run forceload remove %d %d %d %d" % ((dim,) + b) for b in fl] + [
        "scoreboard objectives remove %s" % O(pid, k) for k in objs]
    if P.arrive:
        ax, ay, az, yaw = P.arrive
        out["enter"] = [
            HEAD,
            "# Over RCON, as the owner standing in the overworld: execute as <owner> at @s run function %s" % F(pid, "enter"),
            "execute unless dimension minecraft:overworld run return 0",
            "execute unless score #ready %s matches 1 run return 0" % ST,
            "execute store result score @s %s run data get entity @s Pos[0]" % O(pid, "rx"),
            "execute store result score @s %s run data get entity @s Pos[1]" % O(pid, "ry"),
            "execute store result score @s %s run data get entity @s Pos[2]" % O(pid, "rz"),
            "tag @s add %s" % M,
            "execute in %s run tp @s %.1f %d %.1f %.0f 0" % (dim, ax, ay, az, yaw),
            "return 1"]
        out["leave"] = [
            HEAD,
            "# Over RCON: execute as <owner> run function %s -- back to where enter found them" % F(pid, "leave"),
            "execute unless entity @s[tag=%s] run return 0" % M,
            "tag @s remove %s" % M,
            "execute store result storage %s:%s go.x int 1 run scoreboard players get @s %s" % (NS, pid, O(pid, "rx")),
            "execute store result storage %s:%s go.y int 1 run scoreboard players get @s %s" % (NS, pid, O(pid, "ry")),
            "execute store result storage %s:%s go.z int 1 run scoreboard players get @s %s" % (NS, pid, O(pid, "rz")),
            "function %s with storage %s:%s go" % (F(pid, "go"), NS, pid),
            "return 1"]
        out["go"] = ["$execute in minecraft:overworld run tp @s $(x) $(y) $(z)"]
    return out


def require_ready(pid):
    return "execute unless score #ready %s matches 1 run return 0" % O(pid, "st")


def spawn_npc_lines(doc, pid, fn_at, x, y, z, cls, level, tags):
    """The arena's spawn (tools/arena_runtime.py venue spawn): a macro spawnnpcat at ABSOLUTE coordinates (the
    relative form spawned nothing in game, 2026-10-03), then the nearest untagged NPC within 1.5 is claimed."""
    dim, new = doc["dimension"], "dp%s.new" % pid
    return ["execute in %s run function %s {x:\"%.1f\",y:\"%d\",z:\"%.1f\",cls:\"%s:%s\",level:\"%d\"}"
            % (dim, fn_at, x, y, z, NS, cls, level),
            "execute in %s positioned %.1f %d %.1f as @e[type=cobblemon:npc,tag=!dp%s.e,distance=..1.5,sort=nearest,limit=1] run tag @s add %s"
            % (dim, x, y, z, pid, new)] + [
            "tag @e[type=cobblemon:npc,tag=%s] add %s" % (new, t) for t in tags] + [
            "tag @e[type=cobblemon:npc,tag=%s] remove %s" % (new, new)]


def start_battle_line(pid, npc_tag, owner_tag):
    """The proven start with no click (arena note section 8): runmolang as the owner, the NPC as the npc argument.
    start_battle returns the battle's UUID, or 0 when refused. Never the level argument (arena note: it rewrites a
    shared format)."""
    return ("execute as @a[tag=%s,limit=1] at @s run runmolang \"t.b = q.npc.start_battle(q.player, 'singles'); "
            "(t.b == 0) ? { q.run_command('scoreboard players add #refused %s 1'); };\" @s "
            "@e[type=cobblemon:npc,tag=%s,limit=1]" % (owner_tag, O(pid, "r"), npc_tag))


# ------------------------------------------------------------------------------------------------- the probes


def p1(doc, spec):
    P, pid, dim = Probe("p1"), "p1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    lines, box = pen(ox, oz, 8, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 4.5, 0)
    P.consts = {"#mode": 0, "#form": 1}
    inner = (ox - 8, oy, oz - 8, ox + 8, oy + 10, oz + 8)
    wx, wz = ox + 3.5, oz + 2.5
    P.fns["spawn_at"] = ["# a macro, so the mod's command is parsed when it runs (EXP-046)",
                         "$spawnpokemonat $(x) $(y) $(z) $(props)"]
    P.fns["wild"] = [
        HEAD, "# Over RCON: a wild stand-in for the discard forms (no player needed). Returns how many stand.",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.w,%s]" % (dim, pid, sel(inner)),
        "execute in %s run function %s {x:\"%.1f\",y:\"%d\",z:\"%.1f\",props:\"%s\"}" % (dim, F(pid, "spawn_at"), wx, oy, wz, spec["wild_species"]),
        "execute in %s positioned %.1f %d %.1f as @e[type=cobblemon:pokemon,tag=!dp%s.e,distance=..3,sort=nearest,limit=1] run function %s"
        % (dim, wx, oy, wz, pid, F(pid, "bind")),
        "execute in %s store result score #w %s if entity @e[tag=dp%s.w,%s]" % (dim, R, pid, sel(inner)),
        "return run scoreboard players get #w %s" % R]
    P.fns["bind"] = ["# as the stand-in: ours, kept from the despawner in the same function (datapacks rule)",
                     "tag @s add dp%s.e" % pid, "tag @s add dp%s.w" % pid,
                     "data merge entity @s {PersistenceRequired:1b}"]
    P.fns["form_entity"] = [HEAD, "scoreboard players set #form %s 1" % ST, "return 1"]
    P.fns["form_args"] = [HEAD, "scoreboard players set #form %s 2" % ST, "return 1"]
    P.fns["arm_keeper"] = [HEAD, require_ready(pid), "scoreboard players set #mode %s 1" % ST,
                           "schedule function %s 20t replace" % F(pid, "keeper"), "return 1"]
    P.fns["arm_callback"] = [HEAD, require_ready(pid), "scoreboard players set #mode %s 2" % ST,
                             "schedule clear %s" % F(pid, "keeper"), "return 1"]
    P.fns["disarm"] = [HEAD, "scoreboard players set #mode %s 0" % ST, "schedule clear %s" % F(pid, "keeper"), "return 1"]
    P.fns["keeper"] = [
        HEAD, "# DUNGEONS.md 3.4's recall sweep, every 20 ticks: every untagged cobblemon:pokemon in the box is discarded",
        "execute unless score #mode %s matches 1 run return 0" % ST,
        "scoreboard players add #passes %s 1" % R,
        "execute in %s as @e[type=cobblemon:pokemon,%s] at @s run function %s" % (dim, sel(inner, "tag=!dp%s.keep" % pid), F(pid, "discard")),
        "schedule function %s 20t replace" % F(pid, "keeper")]
    P.fns["discard"] = [
        "# as the Pokemon, at it. #form 1: q.entity is the command source (RunMolangCommand binds 'entity' to the",
        "# source entity, javap 1.8.0); #form 2: the four-argument form, the Pokemon as both npc and pokemon, so",
        "# brigadier cannot take it for the npc argument alone (the npc branch ignores a non-NPC entity)",
        "scoreboard players add #seen %s 1" % R,
        "execute if score #form %s matches 1 run runmolang \"q.entity.discard;\"" % ST,
        "execute if score #form %s matches 2 run runmolang \"q.pokemon.discard;\" @p[distance=..64] @s @s" % ST]
    P.fns["sent"] = [
        "# as a Pokemon just sent out inside the box, at it, from the pokemon_sent_post callback",
        "execute unless score #mode %s matches 2 run return 0" % ST,
        "scoreboard players add #cb %s 1" % R,
        "execute if entity @s[tag=dp%s.keep] run return 0" % pid,
        "runmolang \"q.pokemon.discard;\" @p[distance=..64] @s @s"]
    P.loops = ["keeper"]
    P.files[CALLBACK % ("pokemon_sent_post", pid)] = "\n".join([
        "'Generated by tools/dungeon_probes.py (probe P1), STAGING ONLY. Every send-out runs one command; it acts';",
        "'only on a Pokemon standing in the P1 box in cobblers:pocket, and p1/sent does nothing unless armed.';",
        "t.e = c.pokemon_entity;",
        "q.run_command('execute as ' + t.e.uuid + ' at @s if dimension %s if entity @s[%s] run function %s');"
        % (dim, sel(inner), F(pid, "sent")), ""])
    return P


def b1(doc, spec):
    P, pid = Probe("b1"), "b1"
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    bar = "%s:b1_m1" % NS
    lines, box = pen(ox, oz, 6, oy)
    P.build, P.boxes = lines + [
        "bossbar add %s %s" % (bar, text("Rift", "white")),
        "bossbar set %s max %d" % (bar, spec["clock_units"]),
        "bossbar set %s color white" % bar,
        "bossbar set %s players" % bar], [box]
    P.arrive = (ox + 0.5, oy, oz + 0.5, 0)
    for k in ("clk", "rate", "tk", "m", "s10", "s1", "rm", "rs10", "rs1"):
        P.objs[k] = "dummy"
    P.consts = {"#src": 0, "#20": 20, "#60": 60, "#80": 80, "#10": 10}
    P.cleanup_extra = ["bossbar set %s players" % bar, "bossbar remove %s" % bar]
    P.fns["arm_self"] = ["# as the member (the marker proxy or the owner): a full clock at x1.25, six taken",
                         "scoreboard players set @s %s %d" % (O(pid, "clk"), spec["clock_units"]),
                         "scoreboard players set @s %s %d" % (O(pid, "rate"), spec["rate"]),
                         "scoreboard players set @s %s 6" % O(pid, "tk")]
    P.fns["proxy"] = [
        HEAD, "# Over RCON, no player: a marker is the member and @s of the name's score components.",
        require_ready(pid),
        "execute in %s run kill @e[type=minecraft:marker,tag=dp%s.mk,%s]" % (doc["dimension"], pid, sel(box)),
        "execute in %s run summon minecraft:marker %d %d %d {Tags:[\"dp%s.e\",\"dp%s.mk\"]}" % (doc["dimension"], ox, oy, oz, pid, pid),
        "execute in %s as @e[type=minecraft:marker,tag=dp%s.mk,%s,limit=1] run function %s" % (doc["dimension"], pid, sel(box), F(pid, "arm_self")),
        "scoreboard players set #src %s 1" % ST,
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    P.fns["join"] = [
        HEAD, "# Over RCON: execute as <owner> run function %s -- the owner becomes the bar's member" % F(pid, "join"),
        require_ready(pid),
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
        "function %s" % F(pid, "arm_self"),
        "bossbar set %s players @s" % bar,
        "scoreboard players set #src %s 2" % ST,
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    P.fns["keeper"] = [
        HEAD, "# every 20 ticks: the member's clock falls by 20 x rate, and the bar is re-named and re-valued from it",
        "execute if score #src %s matches 0 run return 0" % ST,
        "scoreboard players add #passes %s 1" % R,
        "execute if score #src %s matches 1 in %s as @e[type=minecraft:marker,tag=dp%s.mk,%s,limit=1] run function %s"
        % (ST, doc["dimension"], pid, sel(box), F(pid, "pass")),
        "execute if score #src %s matches 2 as @a[tag=dp%s.m,limit=1] run function %s" % (ST, pid, F(pid, "pass")),
        "schedule function %s 20t replace" % F(pid, "keeper")]
    clk, rate = O(pid, "clk"), O(pid, "rate")
    name = ["", {"text": "Rift "}, {"score": {"name": "@s", "objective": O(pid, "m")}}, {"text": ":"},
            {"score": {"name": "@s", "objective": O(pid, "s10")}}, {"score": {"name": "@s", "objective": O(pid, "s1")}},
            {"text": " \u00b7 x1.25 \u00b7 ~"}, {"score": {"name": "@s", "objective": O(pid, "rm")}}, {"text": ":"},
            {"score": {"name": "@s", "objective": O(pid, "rs10")}}, {"score": {"name": "@s", "objective": O(pid, "rs1")}},
            {"text": " left \u00b7 taken "}, {"score": {"name": "@s", "objective": O(pid, "tk")}}]
    P.fns["pass"] = [
        "# as the member. Clock in quarter-ticks (DUNGEONS.md 2.1); the clock's own time is clk / 80 seconds, real time",
        "# left is clk / (20 x rate) seconds (2.2). Every score in the name resolves against @s when the command runs.",
        "scoreboard players operation #d %s = @s %s" % (ST, rate),
        "scoreboard players operation #d %s *= #20 %s" % (ST, ST),
        "scoreboard players operation @s %s -= #d %s" % (clk, ST),
        "execute if score @s %s matches ..-1 run scoreboard players set @s %s 0" % (clk, clk),
        "scoreboard players operation #sec %s = @s %s" % (ST, clk),
        "scoreboard players operation #sec %s /= #80 %s" % (ST, ST)] + _mmss(pid, "#sec", "m", "s10", "s1") + [
        "scoreboard players operation #sec %s = @s %s" % (ST, clk),
        "scoreboard players operation #sec %s /= #d %s" % (ST, ST)] + _mmss(pid, "#sec", "rm", "rs10", "rs1") + [
        "bossbar set %s name %s" % (bar, json.dumps(name, ensure_ascii=False)),
        "execute store result bossbar %s value run scoreboard players get @s %s" % (bar, clk),
        "execute if score @s %s matches ..4 run bossbar set %s color white" % (rate, bar),
        "execute if score @s %s matches 5..6 run bossbar set %s color yellow" % (rate, bar),
        "execute if score @s %s matches 7.. run bossbar set %s color red" % (rate, bar)]
    P.fns["clear"] = [
        HEAD, "# every end of a run (2.2): the players set emptied, then the bar removed",
        "scoreboard players set #src %s 0" % ST,
        "schedule clear %s" % F(pid, "keeper"),
        "bossbar set %s players" % bar,
        "bossbar remove %s" % bar,
        "return 1"]
    P.loops = ["keeper"]
    return P


def _mmss(pid, holder, m, s10, s1):
    ST = O(pid, "st")
    return ["scoreboard players operation @s %s = %s %s" % (O(pid, m), holder, ST),
            "scoreboard players operation @s %s /= #60 %s" % (O(pid, m), ST),
            "scoreboard players operation %s %s %%= #60 %s" % (holder, ST, ST),
            "scoreboard players operation @s %s = %s %s" % (O(pid, s10), holder, ST),
            "scoreboard players operation @s %s /= #10 %s" % (O(pid, s10), ST),
            "scoreboard players operation @s %s = %s %s" % (O(pid, s1), holder, ST),
            "scoreboard players operation @s %s %%= #10 %s" % (O(pid, s1), ST)]


def b2(doc, spec):
    P, pid, dim = Probe("b2"), "b2", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    R = O(pid, "r")
    lines, box = pen(ox, oz, 6, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 3.5, 0)
    P.objs["d"] = "deathCount"
    husk = ('{Tags:["dp%s.e","dp%s.%s"],PersistenceRequired:1b,NoAI:1b,Silent:1b,'
            'HandItems:[{},{id:"minecraft:totem_of_undying",count:1}],HandDropChances:[0.0f,0.0f]}')
    P.fns["mobs"] = [
        HEAD, "# Over RCON: two villagers holding a totem in the off hand, NoAI so they stand still (MobsBeGone removes every other vanilla mob, husks included)",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.e,%s]" % (dim, pid, sel(box)),
        "execute in %s run summon minecraft:villager %.1f %d %.1f %s" % (dim, ox + 3.5, oy, oz + 3.5, husk % (pid, pid, "kill")),
        "execute in %s run summon minecraft:villager %.1f %d %.1f %s" % (dim, ox - 2.5, oy, oz + 3.5, husk % (pid, pid, "dmg")),
        "execute in %s store result score #n %s if entity @e[tag=dp%s.e,%s]" % (dim, R, pid, sel(box)),
        "return run scoreboard players get #n %s" % R]
    P.fns["kit"] = [HEAD, "# as the owner: one totem; they move it to the off hand themselves (nothing is overwritten)",
                    "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
                    "give @s minecraft:totem_of_undying 1",
                    "scoreboard players set @s %s 0" % O(pid, "d"),
                    "return 1"]
    return P


def b3(doc, spec):
    P, pid, dim = Probe("b3"), "b3", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    lines, box = pen(ox, oz, 6, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 2.5, 0)
    P.objs["d"] = "deathCount"
    P.consts = {"#arm": 0, "#clk": 0, "#killmode": 1}
    P.files["data/%s/npcs/b3_stand.json" % NS] = json.dumps(npc_class("Rift Stand", spec["npc_team"]), indent=2) + "\n"
    inner = sel(box)
    P.fns["npc_at"] = ["$spawnnpcat $(x) $(y) $(z) $(cls) $(level)"]
    reset = ["scoreboard players set %s %s 0" % (h, R) for h in
             ("#passes", "#held", "#killed", "#zero_at", "#kill_at", "#absent", "#left", "#refused", "#t_start")]
    P.fns["proxy"] = [
        HEAD, "# Over RCON, no player: the clock runs to 0 and holds; with nobody to read, nobody is killed",
        require_ready(pid)] + reset + [
        "scoreboard players set #clk %s %d" % (ST, spec["clock_units"]),
        "scoreboard players set #arm %s 1" % ST,
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    P.fns["fight"] = [
        HEAD, "# Over RCON: execute as <owner> at @s run function %s -- the stand, the clock, the battle" % F(pid, "fight"),
        require_ready(pid),
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
        "execute in %s run kill @e[type=cobblemon:npc,tag=dp%s.e,%s]" % (dim, pid, inner)] + reset + spawn_npc_lines(
        doc, pid, F(pid, "npc_at"), ox + 0.5, oy, oz + 3.5, "b3_stand", 5, ["dp%s.e" % pid, "dp%s.npc" % pid]) + [
        "scoreboard players set #clk %s %d" % (ST, spec["clock_units"]),
        "scoreboard players set #arm %s 1" % ST,
        "scoreboard players set @s %s 0" % O(pid, "d"),
        "schedule function %s 20t replace" % F(pid, "go"),
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "execute in %s store result score #npc %s if entity @e[type=cobblemon:npc,tag=dp%s.npc,%s]" % (dim, R, pid, inner),
        "return run scoreboard players get #npc %s" % R]
    P.fns["go"] = [HEAD, "execute store result score #t_start %s run time query gametime" % R,
                   start_battle_line(pid, "dp%s.npc" % pid, "dp%s.m" % pid)]
    P.fns["keeper"] = [
        HEAD, "# every 20 ticks: the clock falls 20 ticks (80 units at x1); at 0 it holds, and the owner is killed the",
        "# first pass q.player.in_battle reads 0 (DUNGEONS.md 2.5, sudden death)",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "scoreboard players add #passes %s 1" % R,
        "execute if score #clk %s matches 1.. run scoreboard players remove #clk %s 80" % (ST, ST),
        "execute if score #clk %s matches ..0 if score #zero_at %s matches 0 run function %s" % (ST, R, F(pid, "zero")),
        "execute if score #clk %s matches ..0 run scoreboard players set #clk %s 0" % (ST, ST),
        "execute if score #clk %s matches 0 unless entity @a[tag=dp%s.m] run scoreboard players add #absent %s 1" % (ST, pid, R),
        "execute if score #clk %s matches 0 in %s unless entity @a[tag=dp%s.m,%s] if entity @a[tag=dp%s.m] run scoreboard players add #left %s 1"
        % (ST, dim, pid, inner, pid, R),
        "execute if score #clk %s matches 0 in %s as @a[tag=dp%s.m,%s,limit=1] run runmolang \"t.ib = q.player.in_battle; "
        "(t.ib == 0) ? { q.run_command('function %s'); }; (t.ib == 1) ? { q.run_command('scoreboard players add #held %s 1'); };\" @s"
        % (ST, dim, pid, inner, F(pid, "out"), R),
        "execute if score #arm %s matches 1 run schedule function %s 20t replace" % (ST, F(pid, "keeper"))]
    P.fns["zero"] = [HEAD, "execute store result score #zero_at %s run time query gametime" % R,
                     "title @a[tag=dp%s.m] actionbar %s" % (pid, text("The clock is at 0. Sudden death when the battle ends.", "red"))]
    P.fns["out"] = [
        HEAD, "# from the keeper's runmolang (queued, run as the server): in_battle read 0 with the clock at 0",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "execute unless score #clk %s matches ..0 run return 0" % ST,
        "scoreboard players set #arm %s 0" % ST,
        "execute store result score #kill_at %s run time query gametime" % R,
        "scoreboard players add #killed %s 1" % R,
        "execute if score #killmode %s matches 1 as @a[tag=dp%s.m,limit=1] run kill @s" % (ST, pid),
        "execute unless score #killmode %s matches 1 run tellraw @a[tag=dp%s.m] %s" % (ST, pid, text("(B3: the kill would land now; killmode 0)"))]
    P.fns["nokill"] = [HEAD, "scoreboard players set #killmode %s 0" % ST, "return 1"]
    P.loops = ["keeper", "go"]
    return P


def _seam(doc, spec, pid):
    """The seam face: two courses on the far wall of the pen, ores then controls."""
    ox, oy, oz = origin(doc, pid)
    blocks = list(spec["seam"]) * 3 + list(spec["control"])
    out = []
    for dy in (0, 1):
        for i, b in enumerate(blocks):
            out.append((ox - 4 + i, oy + dy, oz + 5, b))
    return out


def _pick(spec):
    preds = "{predicates:[{blocks:[%s]}]}" % ",".join('"%s"' % b for b in spec["seam"])
    return ('minecraft:iron_pickaxe[minecraft:custom_data={cobblers_dg:"pick"},minecraft:unbreakable={},'
            'minecraft:can_break=%s]' % preds)


def _seam_probe(doc, spec, pid):
    P, dim = Probe(pid), doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    lines, box = pen(ox, oz, 6, oy)
    seam = _seam(doc, spec, pid)
    P.build = lines + [setb(x, y, z, b) for x, y, z, b in seam]
    P.boxes = [box]
    P.arrive = (ox + 0.5, oy, oz - 2.5, 0)
    P.fns["kit"] = [HEAD, "# Over RCON: execute as <owner> run function %s -- adventure mode and the rift pick" % F(pid, "kit"),
                    "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
                    "gamemode adventure @s",
                    "function %s" % F(pid, "pick"),
                    "return 1"]
    P.fns["pick"] = ["# DUNGEONS.md 3.3's rift pick. Its own file: the can_break syntax is ASSUMED (R2), and a function that",
                     "# fails to parse is dropped alone at load, named in the boot log",
                     "give @s %s 1" % _pick(spec)]
    P.fns["unkit"] = [HEAD, "# as the owner: survival, and the pick taken by its component (E1 rule 7)",
                      "gamemode survival @s", "function %s" % F(pid, "take_pick"), "return 1"]
    P.fns["take_pick"] = ["# its own file: the custom_data~ predicate syntax is ASSUMED (the SG1 class)",
                          'clear @s minecraft:iron_pickaxe[minecraft:custom_data~{cobblers_dg:"pick"}]']
    kinds = {}
    for x, y, z, b in seam:
        kinds.setdefault(b, []).append((x, y, z))
    read = [HEAD, "# Over RCON: counts what is gone from the face; returns the number of CONTROL blocks broken (PASS: 0)"]
    for b in kinds:
        read.append("scoreboard players set #gone_%s %s 0" % (b.split(":")[1], R))
    for b, ps in kinds.items():
        for x, y, z in ps:
            read.append("execute in %s unless block %d %d %d %s run scoreboard players add #gone_%s %s 1" % (dim, x, y, z, b, b.split(":")[1], R))
    read.append("scoreboard players set #controls %s 0" % R)
    for b in spec["control"]:
        read.append("scoreboard players operation #controls %s += #gone_%s %s" % (R, b.split(":")[1], R))
    read.append("return run scoreboard players get #controls %s" % R)
    P.fns["read"] = read
    return P


def r1(doc, spec):
    P = _seam_probe(doc, spec, "r1")
    for b in spec["seam"] + ["minecraft:stone"]:
        # the stat criterion names the block with a dot: minecraft.mined:minecraft.coal_ore
        P.objs[b.split(":")[1].replace("_ore", "")] = "minecraft.mined:%s" % b.replace(":", ".")
    P.fns["zero"] = [HEAD, "# as the owner: the mined counters to 0 before mining", "execute unless entity @s[tag=dpr1.m] run return 0"] + [
        "scoreboard players set @s %s 0" % O("r1", b.split(":")[1].replace("_ore", "")) for b in spec["seam"] + ["minecraft:stone"]] + ["return 1"]
    return P


def r2(doc, spec):
    P = _seam_probe(doc, spec, "r2")
    ox, oy, oz = origin(doc, "r2")
    # the parse proof's chest: the session writes the pick into it over RCON (EXP-074)
    P.build.append(setb(ox + 5, oy, oz - 3, "minecraft:chest[facing=west]"))
    return P


def f1(doc, spec):
    P, pid, dim = Probe("f1"), "f1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    top, catch0, catch1, pad = oy + 30, oy + 12, oy + 17, oy + 24
    lines, box = pen(ox, oz, 12, oy)
    build, boxes = list(lines), [box]
    mobs = {"a": ox - 8, "b": ox - 5, "c": ox - 2}
    for k, x in mobs.items():
        build += tube(x, oz, oy, top + 1)
        if k == "a":
            # the control: a floor drop-1 blocks under the spawn, no catch
            build.append(setb(x, top - spec["drop"] - 1, oz, "minecraft:stone"))
        else:
            # the checkpoint pad, in its own glass cell, two south of the tube
            build += [setb(x, pad - 1, oz + 3, "minecraft:stone")] + tube(x, oz + 3, pad, pad + 1)
            build.append(setb(x, pad, oz + 2, "minecraft:glass"))
            build.append(setb(x, pad + 1, oz + 2, "minecraft:glass"))
        boxes.append((x - 1, oy, oz - 1, x + 1, top + 1, oz + 4))
    players = {"pb": ox + 4, "pc": ox + 9}
    for k, x in players.items():
        # a 3 x 3 shaft over a water bottom: a missed catch lands in water, never on stone
        build += [fill(x - 2, oy, oz - 2, x + 2, top + 1, oz - 2, "minecraft:glass"),
                  fill(x - 2, oy, oz + 2, x + 2, top + 1, oz + 2, "minecraft:glass"),
                  fill(x - 2, oy, oz - 2, x - 2, top + 1, oz + 2, "minecraft:glass"),
                  fill(x + 2, oy, oz - 2, x + 2, top + 1, oz + 2, "minecraft:glass"),
                  fill(x - 1, oy, oz - 1, x + 1, oy + 1, oz + 1, "minecraft:water"),
                  fill(x - 1, pad - 1, oz + 3, x + 1, pad - 1, oz + 5, "minecraft:stone"),
                  fill(x - 2, pad, oz + 6, x + 2, pad + 1, oz + 6, "minecraft:glass"),
                  fill(x - 2, pad, oz + 3, x - 2, pad + 1, oz + 6, "minecraft:glass"),
                  fill(x + 2, pad, oz + 3, x + 2, pad + 1, oz + 6, "minecraft:glass")]
        boxes.append((x - 2, oy, oz - 2, x + 2, top + 1, oz + 6))
    P.build, P.boxes = build, boxes
    P.arrive = (ox + 0.5, oy, oz - 8.5, 0)
    P.consts = {"#arm": 0, "#ticks": 0}
    husk = '{Tags:["dp%s.e","dp%s.%s"],PersistenceRequired:1b,Silent:1b}'
    P.fns["mobs"] = [
        HEAD, "# Over RCON, no player: a villager drops in each tube (a PROXY: a player's fall is client-reported; MobsBeGone removes husks)",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.e,%s]" % (dim, pid, sel(union(boxes)))] + [
        "scoreboard players set %s %s 0" % (h, R) for h in
        ("#caught_b", "#caught_c", "#fd_b", "#fd_c", "#fd_b_after", "#fd_c_after")] + [
        "execute in %s run summon minecraft:villager %.1f %d %.1f %s" % (dim, x + 0.5, top, oz + 0.5, husk % (pid, pid, k))
        for k, x in mobs.items()] + [
        "scoreboard players set #arm %s 1" % ST, "scoreboard players set #ticks %s 0" % ST,
        "schedule function %s 1t replace" % F(pid, "tick"), "return 1"]

    def catch_box(x, half):
        return sel((x - half, catch0, oz - half, x + half, catch1, oz + half))

    P.fns["tick"] = [
        HEAD, "# every tick while armed, for at most 400 ticks: anything in a catch band goes to its checkpoint pad",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "scoreboard players add #ticks %s 1" % ST,
        "execute in %s as @e[tag=dp%s.b,%s] run function %s" % (dim, pid, catch_box(mobs["b"], 0), F(pid, "catch_b")),
        "execute in %s as @e[tag=dp%s.c,%s] run function %s" % (dim, pid, catch_box(mobs["c"], 0), F(pid, "catch_c")),
        "execute in %s as @a[tag=dp%s.m,%s] run function %s" % (dim, pid, catch_box(players["pb"], 1), F(pid, "catch_pb")),
        "execute in %s as @a[tag=dp%s.m,%s] run function %s" % (dim, pid, catch_box(players["pc"], 1), F(pid, "catch_pc")),
        "execute if score #ticks %s matches 400.. run scoreboard players set #arm %s 0" % (ST, ST),
        "execute if score #arm %s matches 1 run schedule function %s 1t replace" % (ST, F(pid, "tick"))]
    for k, x, res in (("b", mobs["b"], False), ("c", mobs["c"], True)):
        P.fns["catch_" + k] = [
            "# as the falling husk in %s's catch band: its fall distance (x100), then the teleport to the pad" % k,
            "scoreboard players add #caught_%s %s 1" % (k, R),
            "execute store result score #fd_%s %s run data get entity @s FallDistance 100" % (k, R)] + (
            ["effect give @s minecraft:resistance 2 4 true"] if res else []) + [
            "tp @s %.1f %d %.1f" % (x + 0.5, pad, oz + 3.5),
            "schedule function %s 2t replace" % F(pid, "after_" + k)]
        P.fns["after_" + k] = [HEAD, "execute store result score #fd_%s_after %s run data get entity @e[tag=dp%s.%s,limit=1] FallDistance 100" % (k, R, pid, k)]
    for k, x, res in (("pb", players["pb"], False), ("pc", players["pc"], True)):
        P.fns["catch_" + k] = [
            "# as the owner in the %s shaft's catch band: the same teleport the engine would make (3.5)" % k,
            "scoreboard players add #caught_%s %s 1" % (k, R),
            "execute store result score #fd_%s %s run data get entity @s FallDistance 100" % (k, R)] + (
            ["effect give @s minecraft:resistance 2 4 true"] if res else []) + [
            "tp @s %.1f %d %.1f" % (x + 0.5, pad, oz + 4.5),
            "schedule function %s 2t replace" % F(pid, "after_" + k)]
        P.fns["after_" + k] = [HEAD, "execute store result score #fd_%s_after %s run data get entity @a[tag=dp%s.m,limit=1] FallDistance 100" % (k, R, pid),
                               "execute store result score #hp_%s_after %s run data get entity @a[tag=dp%s.m,limit=1] Health 100" % (k, R, pid)]
        P.fns["drop_" + k] = [
            HEAD, "# Over RCON: execute as <owner> run function %s -- into the top of the %s shaft" % (F(pid, "drop_" + k), k),
            require_ready(pid),
            "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
            "execute store result score #hp_%s_before %s run data get entity @s Health 100" % (k, R),
            "scoreboard players set #caught_%s %s 0" % (k, R),
            "scoreboard players set #arm %s 1" % ST, "scoreboard players set #ticks %s 0" % ST,
            "schedule function %s 1t replace" % F(pid, "tick"),
            "execute in %s run tp @s %.1f %d %.1f" % (dim, x + 0.5, top, oz + 0.5),
            "return 1"]
    P.loops = ["tick", "after_b", "after_c", "after_pb", "after_pc"]
    return P


def l1(doc, spec):
    P, pid, dim = Probe("l1"), "l1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST = O(pid, "st")
    bed, surf = oy - 1, oy + spec["depth"] - 1          # bed blocks at y95; water y96..y135, 40 deep
    g = surf                                             # gantry floor level with the rim; feet at surf + 1
    build = [
        fill(ox - 4, bed, oz - 4, ox + 4, surf, oz + 4, "minecraft:stone_bricks"),
        fill(ox - 3, oy, oz - 3, ox + 3, surf, oz + 3, "minecraft:water"),
        fill(ox - 3, bed, oz - 3, ox + 3, bed, oz + 3, "minecraft:sand"),
        # a glass rail on the rim: a fall into 40 of water is the water ladder's harsh rule, not a swim
        fill(ox - 4, surf + 1, oz - 4, ox + 4, surf + 2, oz - 4, "minecraft:glass"),
        fill(ox - 4, surf + 1, oz + 4, ox + 4, surf + 2, oz + 4, "minecraft:glass"),
        fill(ox - 4, surf + 1, oz - 4, ox - 4, surf + 2, oz + 4, "minecraft:glass"),
        fill(ox + 4, surf + 1, oz - 4, ox + 4, surf + 2, oz + 4, "minecraft:glass"),
        # the gantry, north of the shaft
        fill(ox - 4, g, oz - 10, ox + 4, g, oz - 5, "minecraft:spruce_planks"),
        fill(ox - 5, g + 1, oz - 11, ox + 5, g + 2, oz - 11, "minecraft:glass"),
        fill(ox - 5, g + 1, oz - 11, ox - 5, g + 2, oz - 5, "minecraft:glass"),
        fill(ox + 5, g + 1, oz - 11, ox + 5, g + 2, oz - 5, "minecraft:glass"),
        # the beacon's pyramid in the bed, the beacon on it (it displaces the water it stands in)
        fill(ox + 1, bed, oz + 1, ox + 3, bed, oz + 3, "minecraft:iron_block"),
        setb(ox + 2, oy, oz + 2, "minecraft:beacon"),
        # lanterns, waterlogged, on the bed (the repository's rule: lanterns, never light blocks)
        setb(ox - 3, oy, oz - 3, "minecraft:lantern[waterlogged=true]"),
        setb(ox + 3, oy, oz - 3, "minecraft:lantern[waterlogged=true]"),
        setb(ox - 3, oy, oz + 3, "minecraft:lantern[waterlogged=true]"),
        # the bubble column: soul sand under the water, placed last so the water above it updates
        setb(ox - 2, bed, oz + 2, "minecraft:soul_sand")]
    P.build = build
    P.boxes = [(ox - 5, bed, oz - 11, ox + 5, surf + 2, oz + 4)]
    P.arrive = (ox + 0.5, g + 1, oz - 7.5, 0)
    P.consts = {"#arm": 0}
    sx, sz = ox - 0.5, oz - 0.5
    P.fns["spawn_at"] = ["# a macro, so the mod's command is parsed when it runs (EXP-046)",
                         "$spawnpokemonat $(x) $(y) $(z) $(props)"]
    P.fns["sleeper"] = [
        HEAD, "# Over RCON: the legendary's stand-in, dressed dormant (EXP-023/046) and glowing, on the bed",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.sl,%s]" % (dim, pid, sel(P.boxes[0])),
        "execute in %s run function %s {x:\"%.1f\",y:\"%d\",z:\"%.1f\",props:\"%s\"}" % (dim, F(pid, "spawn_at"), sx, oy, sz, spec["sleeper"]),
        "execute in %s positioned %.1f %d %.1f as @e[type=cobblemon:pokemon,tag=!dp%s.e,distance=..3,sort=nearest,limit=1] run function %s"
        % (dim, sx, oy, sz, pid, F(pid, "dress")),
        "execute in %s store result score #n %s if entity @e[tag=dp%s.sl,%s]" % (dim, O(pid, "r"), pid, sel(P.boxes[0])),
        "return run scoreboard players get #n %s" % O(pid, "r")]
    P.fns["dress"] = ["tag @s add dp%s.e" % pid, "tag @s add dp%s.sl" % pid,
                      "data merge entity @s %s" % DORMANT,
                      "effect give @s minecraft:glowing infinite 0 true"]
    P.fns["steam_on"] = [HEAD, require_ready(pid), "scoreboard players set #arm %s 1" % ST,
                         "schedule function %s 10t replace" % F(pid, "steam"), "return 1"]
    P.fns["steam_off"] = [HEAD, "scoreboard players set #arm %s 0" % ST, "schedule clear %s" % F(pid, "steam"), "return 1"]
    P.fns["steam"] = [HEAD, "execute unless score #arm %s matches 1 run return 0" % ST,
                      "execute in %s run particle minecraft:cloud %.1f %d %.1f 2 0.3 2 0.01 12 force" % (dim, ox + 0.5, surf + 1, oz + 0.5),
                      "schedule function %s 10t replace" % F(pid, "steam")]
    P.loops = ["steam"]
    return P


def l2(doc, spec):
    P, pid, dim = Probe("l2"), "l2", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    R = O(pid, "r")
    lines, box = pen(ox, oz, 14, oy, h=5)
    sd, dd = spec["shallow_depth"], spec["deep_depth"]
    s_x0, s_x1 = ox - 12, ox - 3      # shallow basin: a 1-deep shelf (x -12..-10) and the sd-deep part
    d_x0, d_x1 = ox + 3, ox + 9       # deep basin: dd deep
    top = oy + sd - 1                  # both basins' surface: y99
    build = list(lines) + [
        fill(s_x0 - 1, oy - 1, oz - 4, s_x1 + 1, top, oz + 4, "minecraft:prismarine_bricks"),
        fill(s_x0, oy, oz - 3, s_x1, top, oz + 3, "minecraft:water"),
        fill(s_x0, oy, oz - 3, s_x0 + 2, top - 1, oz + 3, "minecraft:prismarine_bricks"),
        fill(d_x0 - 1, top - dd, oz - 4, d_x1 + 1, top, oz + 4, "minecraft:dark_prismarine"),
        fill(d_x0, top - dd + 1, oz - 3, d_x1, top, oz + 3, "minecraft:water"),
        setb(s_x1 - 1, oy, oz, "minecraft:sea_lantern"),
        setb(d_x1 - 1, top - dd + 1, oz + 3, "minecraft:sea_lantern")]
    P.build = build
    P.boxes = [box, (d_x0 - 1, top - dd, oz - 4, d_x1 + 1, oy - 1, oz + 4)]
    P.arrive = (ox + 0.5, oy, oz + 0.5, 0)
    P.fns["spawn_at"] = ["# a macro, so the mod's command is parsed when it runs (EXP-046)",
                         "$spawnpokemonat $(x) $(y) $(z) $(props)"]
    exempt = _j(BLACKOUT)["claims"]["exempt_tag"]
    for k, (x, y) in {"shallow": (s_x1 - 2.5, oy), "deep": (d_x0 + 3.5, top - dd + 1)}.items():
        P.fns["wild_" + k] = [
            HEAD, "# Over RCON: a wild %s submerged in the %s basin, carrying the blackout's claims exempt tag" % (spec["wild"].split()[0], k),
            "# (data/blackout.json claims.exempt_tag), so a loss to it takes no items",
            require_ready(pid),
            "execute in %s run kill @e[tag=dp%s.w%s,%s]" % (dim, pid, k[0], sel(union(P.boxes))),
            "execute in %s run function %s {x:\"%.1f\",y:\"%d\",z:\"%.1f\",props:\"%s\"}" % (dim, F(pid, "spawn_at"), x, y, oz + 0.5, spec["wild"]),
            "execute in %s positioned %.1f %d %.1f as @e[type=cobblemon:pokemon,tag=!dp%s.e,distance=..3,sort=nearest,limit=1] run function %s"
            % (dim, x, y, oz + 0.5, pid, F(pid, "bind_" + k)),
            "execute in %s store result score #n %s if entity @e[tag=dp%s.w%s,%s]" % (dim, R, pid, k[0], sel(union(P.boxes))),
            "return run scoreboard players get #n %s" % R]
        P.fns["bind_" + k] = ["tag @s add dp%s.e" % pid, "tag @s add dp%s.w%s" % (pid, k[0]), "tag @s add %s" % exempt,
                              "data merge entity @s {PersistenceRequired:1b}"]
        # shallow: onto the 1-deep shelf, head above water; deep: onto the basin's west rim. Both face east.
        P.fns["to_" + k] = [HEAD, "# as the owner: to the %s basin" % k,
                            "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
                            "execute in %s run tp @s %.1f %d %.1f -90 30" % (dim, (s_x0 + 1.5) if k == "shallow" else (d_x0 - 0.5),
                                                                           top + 1, oz + 0.5),
                            "return 1"]
    return P


def _chain(doc, pid, P, stages, gap, prefix, timed, next_extra=(), done_title="The chain is over."):
    """The staged boss's chain (DUNGEONS.md 3.2): stage k's class spawned at the stand, the battle started 20 ticks
    later; the victory callback tags the owner; the keeper's first pass with in_battle 0 kills the stage, and the
    next stage starts `gap` ticks after that (spawn at gap - 20, start at gap)."""
    dim = doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    npc, own = "dp%s.npc" % pid, "dp%s.m" % pid
    inner = sel(P.boxes[0])
    n = len(stages)
    spawn = [HEAD, "# stage #stage's class at the stand; the battle starts 20 ticks later (go)",
             "execute in %s run kill @e[type=cobblemon:npc,tag=%s,%s]" % (dim, npc, inner)]
    for k in range(1, n + 1):
        spawn += ["execute if score #stage %s matches %d run function %s" % (ST, k, F(pid, "%sspawn_%d" % (prefix, k)))]
        P.fns["%sspawn_%d" % (prefix, k)] = [HEAD] + spawn_npc_lines(
            doc, pid, F(pid, "npc_at"), ox + 0.5, oy, oz + 3.5, stages[k - 1], 5, ["dp%s.e" % pid, npc])
    spawn += ["schedule function %s 20t replace" % F(pid, prefix + "go")]
    P.fns[prefix + "spawn_stage"] = spawn
    go = [HEAD, "execute unless score #arm %s matches 1 run return 0" % ST,
          "execute store result score #t_go %s run time query gametime" % R,
          "execute if score #stage %s matches 2.. run scoreboard players add #follow %s 1" % (ST, R),
          "execute if score #stage %s matches 2.. run scoreboard players operation #gap_last %s = #t_go %s" % (ST, R, R),
          "execute if score #stage %s matches 2.. run scoreboard players operation #gap_last %s -= #t_seen %s" % (ST, R, R)]
    if timed:
        go += ["scoreboard players operation #t0 %s = #t_go %s" % (R, R),
               "execute if score #stage %s matches 1 run scoreboard players operation #chain_t0 %s = #t_go %s" % (ST, R, R)]
    go += [start_battle_line(pid, npc, own)]
    P.fns[prefix + "go"] = go
    P.fns[prefix + "keeper"] = [
        HEAD, "# every 20 ticks while a chain runs",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "scoreboard players add #passes %s 1" % R,
        "execute as @a[tag=%s,tag=dp%s.lost] run function %s" % (own, pid, F(pid, prefix + "lost")),
        "execute as @a[tag=%s,tag=dp%s.won,limit=1] at @s run runmolang \"(q.player.in_battle == 0) ? { "
        "q.run_command('function %s'); };\" @s" % (own, pid, F(pid, prefix + "next")),
        "execute if score #arm %s matches 1 run schedule function %s 20t replace" % (ST, F(pid, prefix + "keeper"))]
    P.fns[prefix + "next"] = [
        HEAD, "# from the keeper's runmolang (queued, as the server): the owner won and is out of the battle",
        "execute unless entity @a[tag=%s,tag=dp%s.won] run return 0" % (own, pid),
        "tag @a[tag=%s] remove dp%s.won" % (own, pid)] + list(next_extra) + [
        "execute store result score #t_seen %s run time query gametime" % R,
        "execute in %s run kill @e[type=cobblemon:npc,tag=%s,%s]" % (dim, npc, inner),
        "scoreboard players add #stage %s 1" % ST,
        "execute if score #stage %s matches ..%d run title @a[tag=%s] title %s" % (ST, n, own, text("He gets up again.", "dark_red")),
        "execute if score #stage %s matches ..%d run schedule function %s %dt replace" % (ST, n, F(pid, prefix + "spawn_stage"), gap - 20),
        "execute if score #stage %s matches %d.. run function %s" % (ST, n + 1, F(pid, prefix + "done"))]
    P.fns[prefix + "lost"] = [HEAD, "# as the owner, beaten by a stage: the chain is over",
                              "tag @s remove dp%s.lost" % pid, "scoreboard players add #lost %s 1" % R,
                              "scoreboard players set #arm %s 0" % ST,
                              "execute in %s run kill @e[type=cobblemon:npc,tag=%s,%s]" % (dim, npc, inner)]
    P.fns[prefix + "done"] = [HEAD, "scoreboard players set #done %s 1" % R, "scoreboard players set #arm %s 0" % ST,
                              "title @a[tag=%s] title %s" % (own, text(done_title, "gold"))]
    P.loops += [prefix + "keeper", prefix + "spawn_stage", prefix + "go"]


def c1(doc, spec):
    P, pid, dim = Probe("c1"), "c1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    lines, box = pen(ox, oz, 8, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 2.5, 0)
    P.consts = {"#arm": 0, "#stage": 0}
    stages = []
    for k, team in enumerate(spec["stages"], 1):
        cls = "c1_s%d" % k
        stages.append(cls)
        P.files["data/%s/npcs/%s.json" % (NS, cls)] = json.dumps(npc_class("Rift Warden %d" % k, team), indent=2) + "\n"
    P.fns["npc_at"] = ["# the macro spawn (tools/arena_runtime.py venue spawn): parsed when it runs, not at load",
                       "$spawnnpcat $(x) $(y) $(z) $(cls) $(level)"]
    t1, t2 = (ox + 5.5, oy, oz + 3.5), (ox - 4.5, oy, oz + 3.5)
    P.fns["spawn_macro"] = [
        HEAD, "# Over RCON, after a PLAIN restart and no /reload: spawnnpcat from a macro line. Returns how many stand.",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.t1,%s]" % (dim, pid, sel(box))] + spawn_npc_lines(
        doc, pid, F(pid, "npc_at"), t1[0], t1[1], t1[2], stages[0], 5, ["dp%s.t1" % pid, "dp%s.e" % pid]) + [
        "execute in %s store result score #macro %s if entity @e[type=cobblemon:npc,tag=dp%s.t1,%s]" % (dim, R, pid, sel(box)),
        "return run scoreboard players get #macro %s" % R]
    P.fns["spawn_plain"] = [
        HEAD, "# Over RCON, the same with a PLAIN spawnnpcat line, parsed at load (the spawnpokemonat case, EXP-046).",
        "# Its own file: if it fails to parse at load it is dropped alone and named in the boot log.",
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.t2,%s]" % (dim, pid, sel(box)),
        "execute in %s run spawnnpcat %.1f %d %.1f %s:%s 5" % (dim, t2[0], t2[1], t2[2], NS, stages[0]),
        "execute in %s positioned %.1f %d %.1f as @e[type=cobblemon:npc,tag=!dp%s.e,distance=..1.5,sort=nearest,limit=1] run tag @s add dp%s.t2"
        % (dim, t2[0], t2[1], t2[2], pid, pid),
        "execute in %s as @e[type=cobblemon:npc,tag=dp%s.t2] run tag @s add dp%s.e" % (dim, pid, pid),
        "execute in %s store result score #plain %s if entity @e[type=cobblemon:npc,tag=dp%s.t2,%s]" % (dim, R, pid, sel(box)),
        "return run scoreboard players get #plain %s" % R]
    P.fns["clear_tests"] = [HEAD, "execute in %s run kill @e[type=cobblemon:npc,tag=dp%s.t1,%s]" % (dim, pid, sel(box)),
                            "execute in %s run kill @e[type=cobblemon:npc,tag=dp%s.t2,%s]" % (dim, pid, sel(box)), "return 1"]
    P.fns["chain"] = [
        HEAD, "# Over RCON: execute as <owner> at @s run function %s -- %d stages, %d follow-ups" % (F(pid, "chain"), len(stages), len(stages) - 1),
        require_ready(pid),
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
        "tag @s remove dp%s.won" % pid, "tag @s remove dp%s.lost" % pid] + [
        "scoreboard players set %s %s 0" % (h, R) for h in
        ("#passes", "#follow", "#gap_last", "#t_go", "#t_seen", "#refused", "#lost", "#done", "#won")] + [
        "scoreboard players set #stage %s 1" % ST, "scoreboard players set #arm %s 1" % ST,
        "function %s" % F(pid, "spawn_stage"),
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    _chain(doc, pid, P, stages, spec["gap_ticks"], "", timed=False,
           next_extra=["scoreboard players add #won %s 1" % R])
    P.files[CALLBACK % ("battle_victory", pid)] = victory_callback(
        pid, "dp%s.npc" % pid, "tag %P add dpc1.won", "tag %P add dpc1.lost")
    return P


def xt1(doc, spec):
    P, pid, dim = Probe("xt1"), "xt1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R, TK, RES = O(pid, "st"), O(pid, "r"), O(pid, "tk"), O(pid, "res")
    lines, box = pen(ox, oz, 10, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 3.5, 0)
    P.objs.update({"tk": "dummy", "res": "dummy"})
    P.consts = {"#arm": 0, "#stage": 0, "#cur": 0}
    P.fns["npc_at"] = ["$spawnnpcat $(x) $(y) $(z) $(cls) $(level)"]
    fights = []
    for cap in sorted(spec["teams"], key=int):
        for m in spec["members"]:
            fid = "c%sm%d" % (cap, m)
            cls = "xt1_%s" % fid
            fights.append((fid, cls, int(cap)))
            P.files["data/%s/npcs/%s.json" % (NS, cls)] = json.dumps(
                npc_class("Rift Timer %s" % fid, spec["teams"][cap][:m], spec["skill"][cap]), indent=2) + "\n"
    chain = []
    for k, team in enumerate(spec["chain"], 1):
        cls = "xt1_k%d" % k
        chain.append(cls)
        P.files["data/%s/npcs/%s.json" % (NS, cls)] = json.dumps(
            npc_class("Rift Boss %d" % k, team, spec["skill"][str(spec["chain_cap"])]), indent=2) + "\n"
    npc, own = "dp%s.npc" % pid, "dp%s.m" % pid
    for i, (fid, cls, cap) in enumerate(fights, 1):
        P.fns["fight/" + fid] = [
            HEAD, "# Over RCON: execute as <owner> at @s run function %s -- %s, timed from start to the victory callback"
            % (F(pid, "fight/" + fid), fid),
            require_ready(pid),
            "execute unless entity @s[tag=%s] run return 0" % own,
            "execute if score #arm %s matches 1 run return 0" % ST,
            "tag @s remove dp%s.won" % pid, "tag @s remove dp%s.lost" % pid,
            "scoreboard players set #cur %s %d" % (ST, i),
            "scoreboard players set #stage %s 1" % ST,
            "scoreboard players set #arm %s 1" % ST,
            "execute in %s run kill @e[type=cobblemon:npc,tag=%s,%s]" % (dim, npc, sel(box))] + spawn_npc_lines(
            doc, pid, F(pid, "npc_at"), ox + 0.5, oy, oz + 3.5, cls, cap, ["dp%s.e" % pid, npc]) + [
            "schedule function %s 20t replace" % F(pid, "go"),
            "schedule function %s 20t replace" % F(pid, "keeper"),
            "return 1"]
    P.fns["chain"] = [
        HEAD, "# Over RCON: execute as <owner> at @s run function %s -- the 3-stage chain at cap %d, timed whole and per stage"
        % (F(pid, "chain"), spec["chain_cap"]),
        require_ready(pid),
        "execute unless entity @s[tag=%s] run return 0" % own,
        "execute if score #arm %s matches 1 run return 0" % ST,
        "tag @s remove dp%s.won" % pid, "tag @s remove dp%s.lost" % pid,
        "scoreboard players set #cur %s %d" % (ST, len(fights) + 1),
        "scoreboard players set #stage %s 1" % ST, "scoreboard players set #arm %s 1" % ST,
        "function %s" % F(pid, "spawn_stage"),
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    # the single fights share go, keeper and next with the chain: a single fight is a one-stage chain, so next ends it
    # after its one stage by putting #stage past the last
    _chain(doc, pid, P, chain, spec["gap_ticks"], "", timed=True, done_title="Timed.",
           next_extra=["execute unless score #cur %s matches %d run scoreboard players set #stage %s 99"
                       % (ST, len(fights) + 1, ST)])
    won = [HEAD, "# as the beaten NPC, from the victory callback: the tick count is read HERE (gametime, game ticks)",
           "execute store result score #t1 %s run time query gametime" % R,
           "scoreboard players operation #dt %s = #t1 %s" % (R, R),
           "scoreboard players operation #dt %s -= #t0 %s" % (R, R)]
    lost = [HEAD, "# as the NPC that won, from the victory callback: the time to the loss, marked -1",
            "execute store result score #t1 %s run time query gametime" % R,
            "scoreboard players operation #dt %s = #t1 %s" % (R, R),
            "scoreboard players operation #dt %s -= #t0 %s" % (R, R)]
    for i, (fid, cls, cap) in enumerate(fights, 1):
        won.append("execute if score #cur %s matches %d run scoreboard players operation #%s %s = #dt %s" % (ST, i, fid, TK, R))
        won.append("execute if score #cur %s matches %d run scoreboard players set #%s %s 1" % (ST, i, fid, RES))
        lost.append("execute if score #cur %s matches %d run scoreboard players operation #%s %s = #dt %s" % (ST, i, fid, TK, R))
        lost.append("execute if score #cur %s matches %d run scoreboard players set #%s %s -1" % (ST, i, fid, RES))
    c = len(fights) + 1
    for k in range(1, len(chain) + 1):
        won.append("execute if score #cur %s matches %d if score #stage %s matches %d run scoreboard players operation #k%d %s = #dt %s"
                   % (ST, c, ST, k, k, TK, R))
    won += ["execute if score #cur %s matches %d if score #stage %s matches %d run scoreboard players operation #chain %s = #t1 %s"
            % (ST, c, ST, len(chain), TK, R),
            "execute if score #cur %s matches %d if score #stage %s matches %d run scoreboard players operation #chain %s -= #chain_t0 %s"
            % (ST, c, ST, len(chain), TK, R),
            "execute if score #cur %s matches %d if score #stage %s matches %d run scoreboard players set #chain %s 1"
            % (ST, c, ST, len(chain), RES),
            "tag @a[tag=%s] add dp%s.won" % (own, pid)]
    lost += ["execute if score #cur %s matches %d run scoreboard players set #chain %s -1" % (ST, c, RES),
             "tag @a[tag=%s] add dp%s.lost" % (own, pid)]
    P.fns["won"], P.fns["lost_cb"] = won, lost
    P.files[CALLBACK % ("battle_victory", pid)] = victory_callback(
        pid, npc, "function %s" % F(pid, "won"), "function %s" % F(pid, "lost_cb"))
    return P


def v1(doc, spec):
    P, pid, dim = Probe("v1"), "v1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST = O(pid, "st")
    rx = ox - 16                                   # the rip's plane; the walkway runs east (+x) from it
    far = rx + max(spec["marks"]) + 8
    build = [
        fill(rx - 3, oy - 1, oz - 4, far, oy - 1, oz + 4, "minecraft:smooth_stone"),
        fill(rx - 3, oy, oz - 4, far, oy, oz - 4, "minecraft:glass"),
        fill(rx - 3, oy, oz + 4, far, oy, oz + 4, "minecraft:glass"),
        fill(far, oy, oz - 4, far, oy, oz + 4, "minecraft:glass"),
        fill(rx - 3, oy, oz - 4, rx - 3, oy, oz + 4, "minecraft:glass"),
        # the frame (obsidian; the Rift palette is world-content-dev's) and its dark, non-teleporting opening
        fill(rx, oy, oz - 2, rx, oy + 6, oz + 2, "minecraft:obsidian"),
        fill(rx, oy + 1, oz - 1, rx, oy + 5, oz + 1, "minecraft:black_concrete")]
    colours = ["lime", "yellow", "red", "purple"]
    for i, d in enumerate(spec["marks"]):
        build.append(fill(rx + d, oy - 1, oz - 3, rx + d, oy - 1, oz + 3, "minecraft:%s_concrete" % colours[i % 4]))
    P.build = build
    P.boxes = [(rx - 3, oy - 1, oz - 4, far, oy + 6, oz + 4)]
    P.arrive = (rx + spec["marks"][0] + 0.5, oy, oz + 0.5, 90)
    P.consts = {"#arm": 0, "#mode": 0}
    vr = spec["display_view_range"]
    shards = [(0.6, oy + 1.0, -1.6, "minecraft:purple_stained_glass", "0.15f,1.8f,0.3f"),
              (0.6, oy + 3.4, -1.6, "minecraft:crying_obsidian", "0.2f,1.4f,0.25f"),
              (0.6, oy + 1.2, 1.4, "minecraft:purple_stained_glass", "0.15f,2.2f,0.3f"),
              (0.6, oy + 3.6, 1.4, "minecraft:crying_obsidian", "0.2f,1.2f,0.25f"),
              (0.6, oy + 5.4, -0.6, "minecraft:purple_stained_glass", "1.2f,0.15f,0.3f"),
              (0.6, oy + 0.9, -0.4, "minecraft:crying_obsidian", "0.9f,0.12f,0.3f")]
    summons = []
    for dx, y, dz, block, scale in shards:
        summons.append(
            "execute in %s run summon minecraft:block_display %.2f %.2f %.2f {Tags:[\"dp%s.e\",\"dp%s.d\"],view_range:%.1ff,"
            "brightness:{sky:15,block:15},block_state:{Name:\"%s\"},transformation:{left_rotation:[0f,0f,0f,1f],"
            "right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[%s]}}" % (dim, rx + dx, y, oz + 0.5 + dz, pid, pid, vr, block, scale))
    P.fns["dress"] = [
        HEAD, "# Over RCON: the torn edge (block displays, view_range %.1f) and the interaction filling the opening" % vr,
        require_ready(pid),
        "execute in %s run kill @e[tag=dp%s.e,%s]" % (dim, pid, sel(P.boxes[0]))] + summons + [
        "execute in %s run summon minecraft:interaction %.1f %d %.1f {width:3.0f,height:5.0f,response:1b,Tags:[\"dp%s.e\"]}"
        % (dim, rx + 1.0, oy + 1, oz + 0.5, pid),
        "execute in %s store result score #n %s if entity @e[type=minecraft:block_display,tag=dp%s.d,%s]" % (dim, O(pid, "r"), pid, sel(P.boxes[0])),
        "return run scoreboard players get #n %s" % O(pid, "r")]
    cx, cy, cz = rx + 1.0, oy + 3, oz + 0.5
    P.fns["emit"] = [
        HEAD, "# every 10 ticks while armed. #mode 0 normal; 1 force; 2 force and a plume; 3 the design as written",
        "# (normal, emitted only while a player is within 48 blocks: DUNGEONS.md 7.1)",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "execute if score #mode %s matches 0 in %s run particle minecraft:reverse_portal %.1f %d %.1f 0.2 1.6 1.2 0.05 60 normal" % (ST, dim, cx, cy, cz),
        "execute if score #mode %s matches 0 in %s run particle minecraft:portal %.1f %d %.1f 0.2 1.6 1.2 0.5 40 normal" % (ST, dim, cx, cy, cz),
        "execute if score #mode %s matches 1..2 in %s run particle minecraft:reverse_portal %.1f %d %.1f 0.2 1.6 1.2 0.05 60 force" % (ST, dim, cx, cy, cz),
        "execute if score #mode %s matches 1..2 in %s run particle minecraft:portal %.1f %d %.1f 0.2 1.6 1.2 0.5 40 force" % (ST, dim, cx, cy, cz),
        "execute if score #mode %s matches 2 in %s run particle minecraft:campfire_signal_smoke %.1f %d %.1f 0.3 1 0.3 0.01 6 force" % (ST, dim, cx, oy + 7, cz),
        "execute if score #mode %s matches 2 in %s run particle minecraft:end_rod %.1f %d %.1f 0.15 8 0.15 0 30 force" % (ST, dim, cx, oy + 14, cz),
        "execute if score #mode %s matches 3 in %s positioned %.1f %d %.1f if entity @a[distance=..48] run particle minecraft:reverse_portal ~ ~ ~ 0.2 1.6 1.2 0.05 60 normal" % (ST, dim, cx, cy, cz),
        "execute if score #mode %s matches 3 in %s positioned %.1f %d %.1f if entity @a[distance=..48] run particle minecraft:portal ~ ~ ~ 0.2 1.6 1.2 0.5 40 normal" % (ST, dim, cx, cy, cz),
        "schedule function %s 10t replace" % F(pid, "emit")]
    for m in range(4):
        P.fns["mode%d" % m] = [HEAD, require_ready(pid), "scoreboard players set #mode %s %d" % (ST, m),
                               "scoreboard players set #arm %s 1" % ST, "schedule function %s 10t replace" % F(pid, "emit"), "return 1"]
    P.fns["off"] = [HEAD, "scoreboard players set #arm %s 0" % ST, "schedule clear %s" % F(pid, "emit"), "return 1"]
    for d in spec["marks"]:
        P.fns["at%d" % d] = [HEAD, "# as the owner: onto the %d-block mark, facing the rip (west)" % d,
                             "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
                             "execute in %s run tp @s %.1f %d %.1f 90 0" % (dim, rx + d + 0.5, oy, oz + 0.5), "return 1"]
    P.loops = ["emit"]
    return P


def i2(doc, spec):
    P, pid, dim = Probe("i2"), "i2", doc["dimension"]
    s = spec["strip"]
    x0, z0, y0 = s["x0"], s["z0"], s["y0"]
    x1, z1, y1 = x0 + s["length"] - 1, z0 + s["width"] - 1, y0 + s["height"] - 1
    R = O(pid, "r")
    P.boxes = [(x0, y0, z0, x1, y1, z1)]
    P.build = []
    P.objs = {}
    fl = chunk_rows(x0, z0, x1, z1)

    def counted(raw):
        out = []
        for f in function_limits.split_fills(raw):
            out += ["execute store result score #f %s run %s" % (R, f), "scoreboard players operation #n %s += #f %s" % (R, R)]
        return out

    hull = [fill(x0, y0, z0, x1, y0, z1, "minecraft:bedrock"),             # floor
            fill(x0, y1, z0, x1, y1, z1, "minecraft:bedrock"),             # ceiling
            fill(x0, y0 + 1, z0, x1, y1 - 1, z0, "minecraft:bedrock"),     # the long walls
            fill(x0, y0 + 1, z1, x1, y1 - 1, z1, "minecraft:bedrock"),
            fill(x0, y0 + 1, z0 + 1, x0, y1 - 1, z1 - 1, "minecraft:bedrock"),   # the ends
            fill(x1, y0 + 1, z0 + 1, x1, y1 - 1, z1 - 1, "minecraft:bedrock")]
    interior = [fill(x0 + 1, y0 + 1, z0 + 1, x1 - 1, y1 - 1, z1 - 1, "minecraft:air")]
    P.fns["shell"] = [
        HEAD, "# Over RCON, timed by the session: one slot's shell re-apply, as a re-apply step would run it. Returns the",
        "# number of blocks it changed (the sum of every fill's own count).",
        "return run execute in %s run function %s" % (dim, F(pid, "shell_in"))]
    P.fns["shell_in"] = [
        HEAD, "# in %s: %d chunks in %d forceload adds, the hull, then the interior cleared" % (dim, sum(
            ((b[2] - b[0]) // 16 + 1) * ((b[3] - b[1]) // 16 + 1) for b in _merge_rows(fl)), len(_merge_rows(fl)))] + [
        "forceload add %d %d %d %d" % b for b in _merge_rows(fl)] + [
        "scoreboard objectives add %s dummy" % R,
        "scoreboard players set #n %s 0" % R] + counted(hull) + counted(interior) + [
        "scoreboard players operation #last %s = #n %s" % (R, R)] + [
        "forceload remove %d %d %d %d" % b for b in _merge_rows(fl)] + [
        "return run scoreboard players get #n %s" % R]
    dl = spec["dirty_length"]
    dirty = [fill(x0 + 1, y0 + 1, z0 + 1, x0 + dl, y1 - 1, z1 - 1, "minecraft:stone")]
    dfl = chunk_rows(x0, z0, x0 + dl, z1)
    P.fns["dirty"] = [HEAD, "# Over RCON: a dressing stand-in, the first %d blocks of the interior filled with stone" % dl,
                      "return run execute in %s run function %s" % (dim, F(pid, "dirty_in"))]
    P.fns["dirty_in"] = [HEAD] + ["forceload add %d %d %d %d" % b for b in _merge_rows(dfl)] + [
        "scoreboard objectives add %s dummy" % R, "scoreboard players set #n %s 0" % R] + counted(dirty) + [
        "forceload remove %d %d %d %d" % b for b in _merge_rows(dfl)] + [
        "return run scoreboard players get #n %s" % R]
    P.fns["clear"] = [HEAD, "# Over RCON: the strip back to air (the probe's cleanup)",
                      "return run execute in %s run function %s" % (dim, F(pid, "clear_in"))]
    P.fns["clear_in"] = [HEAD] + ["forceload add %d %d %d %d" % b for b in _merge_rows(fl)] + [
        "scoreboard objectives add %s dummy" % R, "scoreboard players set #n %s 0" % R] + counted(
        [fill(x0, y0, z0, x1, y1, z1, "minecraft:air")]) + [
        "forceload remove %d %d %d %d" % b for b in _merge_rows(fl)] + [
        "scoreboard objectives remove %s" % R, "return 1"]
    return P


def _merge_rows(fl):
    """chunk_rows gives one box per chunk row; merge vertically adjacent rows with the same x span while the box
    stays within 256 chunks (DUNGEONS.md 11.3: 'two batches' for a 2,048 x 64 strip)."""
    out = []
    for b in fl:
        if out:
            a = out[-1]
            n = ((b[2] - a[0]) // 16 + 1) * ((b[3] - a[1]) // 16 + 1)
            if a[0] == b[0] and a[2] == b[2] and a[3] + 1 == b[1] and n <= function_limits.FORCELOAD_CHUNK_LIMIT:
                out[-1] = (a[0], a[1], a[2], b[3])
                continue
        out.append(b)
    return out


def lo1(doc, spec):
    P, pid, dim = Probe("lo1"), "lo1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    ST, R = O(pid, "st"), O(pid, "r")
    CLK, SEEN, RATE = O(pid, "clk"), O(pid, "seen"), O(pid, "rate")
    lines, box = pen(ox, oz, 6, oy)
    P.build, P.boxes = lines, [box]
    P.arrive = (ox + 0.5, oy, oz - 2.5, 0)
    P.objs.update({"clk": "dummy", "seen": "dummy", "rate": "dummy"})
    P.consts = {"#arm": 0, "#own": 0, "#killmode": 0, "#20": 20}
    P.build = P.build + ["execute unless score #up %s matches 0.. run scoreboard players set #up %s 0" % (ST, ST)]
    inner = sel(box)
    P.files["data/%s/npcs/lo1_npc.json" % NS] = json.dumps(npc_class("Rift Stand", spec["npc_team"]), indent=2) + "\n"
    P.fns["npc_at"] = ["$spawnnpcat $(x) $(y) $(z) $(cls) $(level)"]
    P.fns["join"] = [
        HEAD, "# Over RCON: execute as <owner> run function %s -- a run: clock, rate, the slot owned" % F(pid, "join"),
        require_ready(pid),
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid] + [
        "scoreboard players set %s %s 0" % (h, R) for h in
        ("#pre", "#post", "#gap", "#charged", "#returns", "#freed", "#freed_at", "#dead", "#dead_at", "#timeouts")] + [
        "scoreboard players set @s %s %d" % (CLK, spec["clock_units"]),
        "scoreboard players set @s %s %d" % (RATE, spec["rate"]),
        "scoreboard players operation @s %s = #up %s" % (SEEN, ST),
        "scoreboard players set #own %s 1" % ST,
        "scoreboard players set #arm %s 1" % ST,
        "schedule function %s 20t replace" % F(pid, "keeper"),
        "return 1"]
    P.fns["keeper"] = [
        HEAD, "# every 20 ticks: the uptime counter (DUNGEONS.md 2.6), each member present, and the slot's deadline",
        "execute unless score #arm %s matches 1 run return 0" % ST,
        "scoreboard players add #up %s 20" % ST,
        "execute in %s as @a[tag=dp%s.m,%s] run function %s" % (dim, pid, inner, F(pid, "member")),
        "execute if score #own %s matches 1 unless entity @a[tag=dp%s.m] if score #up %s > #dl %s run function %s"
        % (ST, pid, ST, ST, F(pid, "free")),
        "execute if score #arm %s matches 1 run schedule function %s 20t replace" % (ST, F(pid, "keeper"))]
    P.fns["member"] = [
        "# as a member standing in the slot. The absence gap first, then the dead-run check, then the pass",
        "scoreboard players operation #g %s = #up %s" % (ST, ST),
        "scoreboard players operation #g %s -= @s %s" % (ST, SEEN),
        "scoreboard players remove #g %s 20" % ST,
        "execute if score #g %s matches 1.. run function %s" % (ST, F(pid, "charge")),
        "execute if score #own %s matches 0 run return run function %s" % (ST, F(pid, "dead")),
        "execute if score @s %s matches ..0 run return run function %s" % (CLK, F(pid, "dead")),
        "scoreboard players operation #d %s = @s %s" % (ST, RATE),
        "scoreboard players operation #d %s *= #20 %s" % (ST, ST),
        "scoreboard players operation @s %s -= #d %s" % (CLK, ST),
        "scoreboard players operation @s %s = #up %s" % (SEEN, ST),
        "# the slot's deadline in uptime ticks: #up + clock / rate",
        "scoreboard players operation #dl %s = @s %s" % (ST, CLK),
        "scoreboard players operation #dl %s /= @s %s" % (ST, RATE),
        "scoreboard players operation #dl %s += #up %s" % (ST, ST),
        "execute if score @s %s matches ..0 run function %s" % (CLK, F(pid, "timeout"))]
    P.fns["charge"] = [
        "# as a member back after an absence: gap x rate off the clock, before anything else",
        "scoreboard players operation #pre %s = @s %s" % (R, CLK),
        "scoreboard players operation #gap %s = #g %s" % (R, ST),
        "scoreboard players operation #charged %s = #g %s" % (R, ST),
        "scoreboard players operation #charged %s *= @s %s" % (R, RATE),
        "scoreboard players operation @s %s -= #charged %s" % (CLK, R),
        "scoreboard players operation #post %s = @s %s" % (R, CLK),
        "scoreboard players add #returns %s 1" % R,
        "title @s actionbar %s" % text("The rift did not wait.", "gold")]
    P.fns["free"] = [HEAD, "# the deadline passed with the member away: the slot is freed without them",
                     "scoreboard players set #own %s 0" % ST,
                     "scoreboard players set #freed %s 1" % R,
                     "scoreboard players operation #freed_at %s = #up %s" % (R, ST)]
    P.fns["dead"] = [
        "# as a member on their first pass back to a dead run (their clock at or below 0, or the slot freed)",
        "scoreboard players add #dead %s 1" % R,
        "scoreboard players operation #dead_at %s = #up %s" % (R, ST),
        "scoreboard players set #arm %s 0" % ST,
        "title @s title %s" % text("The rift closed without you", "dark_red"),
        "execute if score #killmode %s matches 1 run kill @s" % ST]
    P.fns["timeout"] = [
        "# as a member whose clock ran out while present",
        "scoreboard players add #timeouts %s 1" % R,
        "scoreboard players set #arm %s 0" % ST,
        "title @s title %s" % text("The rift closes.", "dark_red"),
        "execute if score #killmode %s matches 1 run kill @s" % ST]
    P.fns["killmode"] = [HEAD, "scoreboard players set #killmode %s 1" % ST, "return 1"]
    P.fns["resume"] = [HEAD, "# Over RCON, only if #up stopped after a restart: the keeper was not rescheduled",
                       "schedule function %s 20t replace" % F(pid, "keeper"), "return 1"]
    P.fns["battle"] = [
        HEAD, "# Over RCON: execute as <owner> at @s run function %s -- a stand to log out of mid-battle" % F(pid, "battle"),
        require_ready(pid),
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
        "execute in %s run kill @e[type=cobblemon:npc,tag=dp%s.e,%s]" % (dim, pid, inner)] + spawn_npc_lines(
        doc, pid, F(pid, "npc_at"), ox + 0.5, oy, oz + 3.5, "lo1_npc", 5, ["dp%s.e" % pid, "dp%s.npc" % pid]) + [
        "schedule function %s 20t replace" % F(pid, "go"),
        "return 1"]
    P.fns["go"] = [HEAD, start_battle_line(pid, "dp%s.npc" % pid, "dp%s.m" % pid)]
    P.loops = ["keeper", "go"]
    return P


def _sigil_components(s):
    return {"minecraft:custom_data": {"cobblers_dg_sigil": s["band"]},
            "minecraft:item_name": json.dumps({"text": s["name"], "color": s["colour"], "italic": False}),
            "minecraft:lore": [json.dumps({"text": "The rift lets you in for this.", "color": "dark_gray", "italic": True}),
                               json.dumps({"text": "For a trainer at level cap %s." % s["caps"], "color": "dark_gray", "italic": True})],
            "minecraft:rarity": "rare"}


def sg1(doc, spec):
    P, pid, dim = Probe("sg1"), "sg1", doc["dimension"]
    ox, oy, oz = origin(doc, pid)
    lines, box = pen(ox, oz, 6, oy)
    stock, crafter, out, power = (ox + 3, oy, oz + 3), (ox - 3, oy, oz + 3), (ox - 2, oy, oz + 3), (ox - 4, oy, oz + 3)
    P.build = lines + [setb(*stock, "minecraft:chest[facing=north]"),
                       setb(*crafter, "minecraft:crafter[orientation=east_up]"),
                       setb(*out, "minecraft:chest[facing=north]")]
    P.boxes = [box]
    P.arrive = (ox + 0.5, oy, oz - 2.5, 0)
    by = "# chunks-loaded-by: %s" % F(pid, "setup_in")
    s1, s2 = spec["sigils"]
    P.fns["stock"] = [
        HEAD, "# Over RCON: the stock chest. Its own file: item-with-component syntax is parsed at load (EXP-083 step 2)", by,
        "execute in %s run item replace block %d %d %d container.0 with %s[minecraft:custom_data={cobblers_dg_sigil:%d}]" % ((dim,) + stock + (s1["item"], 1)),
        "execute in %s run item replace block %d %d %d container.1 with %s" % ((dim,) + stock + (s1["item"],)),
        "execute in %s run item replace block %d %d %d container.2 with %s[minecraft:custom_data={cobblers_dg_sigil:%d}]" % ((dim,) + stock + (s1["item"], 2)),
        "execute in %s run item replace block %d %d %d container.3 with %s[minecraft:custom_data={cobblers_dg_sigil:%d}]" % ((dim,) + stock + (s2["item"], 2)),
        "return 1"]
    P.fns["count"] = [
        HEAD, "# Over RCON: how many band-1 sigils the stock chest holds by the predicate the sigil step will use. PASS: 1",
        "return run execute in %s if items block %d %d %d container.* %s[minecraft:custom_data~{cobblers_dg_sigil:1}]"
        % ((dim,) + stock + (s1["item"],))]
    ings = [i for item, n in s1["ingredients"] for i in [item] * n]
    P.fns["craft"] = [
        HEAD, "# Over RCON, no player: the crafter gets the band-1 recipe's inputs and one redstone pulse", by,
        require_ready(pid),
        "execute in %s run data remove block %d %d %d Items" % ((dim,) + out)] + [
        "execute in %s run item replace block %d %d %d container.%d with %s" % ((dim,) + crafter + (i, it)) for i, it in enumerate(ings)] + [
        "execute in %s run setblock %d %d %d minecraft:redstone_block" % ((dim,) + power),
        "schedule function %s 10t replace" % F(pid, "unpower"),
        "return 1"]
    P.fns["unpower"] = [HEAD, by, "execute in %s run setblock %d %d %d minecraft:air" % ((dim,) + power)]
    P.fns["give_owner"] = [
        HEAD, "# as the owner: a band-1 sigil, a plain sherd of the same item, a band-2-tagged sherd of the same item, and a",
        "# band-2 sigil (the design's item). Its own file, for the component syntax",
        "execute unless entity @s[tag=dp%s.m] run return 0" % pid,
        "give @s %s[minecraft:custom_data={cobblers_dg_sigil:1}] 1" % s1["item"],
        "give @s %s 1" % s1["item"],
        "give @s %s[minecraft:custom_data={cobblers_dg_sigil:2}] 1" % s1["item"],
        "give @s %s[minecraft:custom_data={cobblers_dg_sigil:2}] 1" % s2["item"],
        "return 1"]
    P.loops = ["unpower"]
    for s in spec["sigils"]:
        rid = "sg1_band%d" % s["band"]
        ings = [{"item": item} for item, n in s["ingredients"] for _ in range(n)]
        P.files["data/%s/recipe/%s.json" % (NS, rid)] = json.dumps({
            "type": "minecraft:crafting_shapeless", "category": "misc", "ingredients": ings,
            "result": {"id": s["item"], "count": 1, "components": _sigil_components(s)}}, indent=2) + "\n"
    P.files["data/%s/advancement/sg1/opt.json" % NS] = json.dumps(
        {"criteria": {"granted": {"trigger": "minecraft:impossible"}}, "requirements": [["granted"]]}, indent=2) + "\n"
    P.files["data/%s/advancement/sg1/sync.json" % NS] = json.dumps({
        "criteria": {"held": {"trigger": "minecraft:tick", "conditions": {"player": [
            {"condition": "minecraft:entity_properties", "entity": "this", "predicate": {"type_specific": {
                "type": "minecraft:player", "advancements": {"%s:sg1/opt" % NS: True}}}}]}}},
        "rewards": {"function": F(pid, "recipes")}}, indent=2) + "\n"
    P.fns["recipes"] = ["# the reward of %s:sg1/sync: DUNGEONS.md 7.4's recipe give, gated here on the owner's opt-in" % NS] + [
        "recipe give @s %s:sg1_band%d" % (NS, s["band"]) for s in spec["sigils"]]
    return P


BUILDERS = {"p1": p1, "b1": b1, "b2": b2, "b3": b3, "r1": r1, "r2": r2, "f1": f1, "l1": l1, "l2": l2, "c1": c1,
            "xt1": xt1, "v1": v1, "i2": i2, "lo1": lo1, "sg1": sg1}


def build(doc, **kw):
    bad = problems(doc, kw.get("portals_doc"), kw.get("entei_doc"))
    if bad:
        raise ProbeError("data/dungeon_probes.json: " + "; ".join(bad))
    files = {"pack.mcmeta": json.dumps({"pack": {"pack_format": PACK_FORMAT, "description":
                                                 "Cobblers: dungeon probes, STAGING ONLY (tools/dungeon_probes.py)"}},
                                       indent=2) + "\n"}
    for spec in doc["probes"]:
        P = BUILDERS[spec["id"]](doc, spec)
        fns = dict(P.fns)
        if spec["id"] != "i2":
            fns.update(common(doc, P))
        else:
            fns["setup"] = [HEAD, "# I2 needs no setup: shell, dirty and clear each force-load what they write", "return 1"]
            fns["cleanup"] = [HEAD, "return run function %s" % F("i2", "clear")]
        for name, lines in fns.items():
            rel = "data/%s/function/%s/%s.mcfunction" % (NS, spec["id"], name)
            refused = function_limits.check_lines(lines, rel)
            if refused:
                raise SystemExit("%s: %d command(s) the server would refuse (%s); nothing written"
                                 % (rel, len(refused), refused[0][2][:120]))
            files[rel] = "\n".join(lines) + "\n"
        files.update(P.files)
    return files


def write(files, out):
    out = Path(out)
    if out.exists():
        shutil.rmtree(out)
    for rel, body in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8", newline="\n")


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--data", default=str(DATA))
    p.add_argument("--out", default=str(DEFAULT_OUT))
    a = p.parse_args(argv)
    files = build(load(a.data))
    write(files, a.out)
    print("cobblers_dg_probes: %d files -> %s (STAGING ONLY: install by hand into the staging world's datapacks/)"
          % (len(files), a.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
