"""Generate the EXP-001 F4 Relic Island placement function and plan preview."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import random
import shutil


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "world/source/events/f4-relic-island.json"
DEFAULT_FUNCTION = ROOT / (
    "modpack/datapacks/cobblers_campaign/data/cobblers/function/"
    "exp_001/f4_relic_island/place.mcfunction"
)
DEFAULT_PREVIEW = ROOT / "world/source/events/f4-relic-island-plan.svg"
DEFAULT_TEMPLATE_SOURCE = ROOT / "world/structures/campaign/f4/pallet_house_large2.nbt"
DEFAULT_TEMPLATE_OUTPUT = ROOT / (
    "modpack/datapacks/cobblers_campaign/data/cobblers/structure/"
    "f4/pallet_house_large2.nbt"
)


def _fill(x1: int, y1: int, z1: int, x2: int, y2: int, z2: int, block: str) -> str:
    return f"fill ~{x1} ~{y1} ~{z1} ~{x2} ~{y2} ~{z2} {block}"


def _set(x: int, y: int, z: int, block: str) -> str:
    return f"setblock ~{x} ~{y} ~{z} {block}"


def _island_commands(seed: int) -> list[str]:
    rng = random.Random(seed)
    commands = [
        "# Generated by tools/generate_f4_relic_island.py",
        "# Execute positioned at the island center with ~0 at sea level.",
        "forceload add ~-42 ~-35 ~42 ~35",
    ]
    rx, rz = 35, 29
    jitters = {z: rng.choice((-2, -1, 0, 0, 0, 1, 2)) for z in range(-rz, rz + 1)}
    for z in range(-rz, rz + 1):
        curve = math.sqrt(max(0.0, 1.0 - (z / rz) ** 2))
        width = max(2, round(rx * curve) + jitters[z])
        commands.append(_fill(-width, -6, z, width, -3, z, "minecraft:stone"))
        if width > 3:
            commands.append(_fill(-width + 2, -2, z, width - 2, -1, z, "minecraft:gravel"))
        if width > 6:
            commands.append(_fill(-width + 4, 0, z, width - 4, 0, z, "minecraft:sand"))
        if abs(z) <= 23 and width > 10:
            inner = width - 8
            commands.append(_fill(-inner, 1, z, inner, 2, z, "minecraft:dirt"))
            commands.append(_fill(-inner, 3, z, inner, 3, z, "minecraft:grass_block"))
        if abs(z) <= 17 and width > 14:
            inner = width - 12
            commands.append(_fill(-inner, 4, z, inner, 4, z, "minecraft:grass_block"))
    return commands


def _donor_commands() -> list[str]:
    return [
        "",
        "# MIT donor: CobblemonCityTowns 1.0 Pallet Town large house 2.",
        "# The donor is copied as cobblers:f4/pallet_house_large2; no donor worldgen is enabled.",
        "place template cobblers:f4/pallet_house_large2 ~-6 ~5 ~-5 none none 1.0 64929",
        "# Resolve the donor's three jigsaws into their declared final blocks.",
        _set(-6, 5, -2, "minecraft:dirt_path"),
        _set(-1, 5, -2, "minecraft:jungle_planks"),
        _set(0, 5, 0, "minecraft:jungle_planks"),
        "# Replace the donor loot-table reference with the EXP-001 placeholder cache.",
        "data remove block ~-1 ~6 ~2 LootTable",
        "data remove block ~-1 ~6 ~2 Items",
        "loot insert ~-1 ~6 ~2 loot cobblers:chests/f4_relic_island_placeholder",
        "# Minimal worldshift damage: the southeast roof edge was torn away.",
        _fill(3, 11, 2, 5, 13, 4, "minecraft:air"),
        _set(2, 11, 3, "minecraft:mangrove_slab[type=bottom,waterlogged=false]"),
        "",
        "# Interrupted path, broken fence and debris point back toward Pallet.",
        _fill(-7, 5, -3, -13, 5, 1, "minecraft:dirt_path"),
        _set(-8, 5, -5, "minecraft:barrel[facing=up,open=false]"),
        _fill(-13, 6, -8, -13, 6, -3, "minecraft:birch_fence"),
        _fill(-13, 6, 3, -13, 6, 6, "minecraft:birch_fence"),
        _set(-18, 1, -8, "minecraft:oak_planks"),
        _set(-20, 1, -7, "minecraft:oak_slab[type=top,waterlogged=false]"),
        _set(-22, 1, -5, "minecraft:oak_trapdoor[facing=west,half=bottom,open=false,powered=false,waterlogged=false]"),
        _set(-25, 0, 3, "minecraft:oak_slab[type=top,waterlogged=true]"),
        _set(-28, 0, 7, "minecraft:oak_planks"),
        "",
        "# Lone tree and worldshift scar.",
        _fill(18, 4, 6, 18, 10, 6, "minecraft:oak_log"),
        _fill(15, 9, 3, 21, 12, 9, "minecraft:oak_leaves[persistent=true]"),
        _fill(17, 12, 5, 19, 14, 7, "minecraft:oak_leaves[persistent=true]"),
        _fill(-24, 3, 7, -17, 3, 13, "minecraft:calcite"),
        _fill(-22, 4, 9, -19, 4, 11, "minecraft:amethyst_block"),
        _set(-20, 5, 10, "minecraft:amethyst_cluster[facing=up,waterlogged=false]"),
        "forceload remove ~-42 ~-35 ~42 ~35",
        'tellraw @a[distance=..96] {"text":"A stranded piece of another world settles into place.","color":"gray","italic":true}',
    ]

def _preview(config: dict) -> str:
    anchor = config["placement"]["anchor"]
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650">
<rect width="900" height="650" fill="#2d6475"/>
<path d="M0 205 Q180 170 330 215 T610 190 T900 220 V0 H0Z" fill="#87a565"/>
<path d="M0 220 Q180 185 330 230 T610 205 T900 235" fill="none" stroke="#d9c084" stroke-width="28"/>
<ellipse cx="450" cy="440" rx="150" ry="105" fill="#d9c084"/>
<ellipse cx="450" cy="430" rx="124" ry="81" fill="#789a58"/>
<rect x="400" y="355" width="100" height="90" fill="#eee4cf" stroke="#49382d" stroke-width="8"/>
<polygon points="385,360 450,315 515,360" fill="#a44232" stroke="#49382d" stroke-width="7"/>
<path d="M450 355 L450 245" stroke="#9d8157" stroke-width="12" stroke-dasharray="22 14"/>
<path d="M362 455 L330 485" stroke="#d8d0bd" stroke-width="13"/>
<circle cx="548" cy="445" r="28" fill="#446b39"/><rect x="542" y="443" width="12" height="48" fill="#6b4a2e"/>
<text x="450" y="55" text-anchor="middle" font-family="serif" font-size="30" fill="white">F4 Pallet Coast — EXP-001</text>
<text x="450" y="285" text-anchor="middle" font-family="sans-serif" font-size="18" fill="white">broken dock sightline · 145 blocks</text>
<text x="450" y="570" text-anchor="middle" font-family="serif" font-size="27" fill="white">Relic Island — The Stranded Home</text>
<text x="450" y="600" text-anchor="middle" font-family="sans-serif" font-size="16" fill="#dcecef">F4-local anchor {anchor['x']}, {anchor['y']}, {anchor['z']} · prototype plan, not final coast art</text>
</svg>'''


def generate(
    source: Path,
    function_path: Path,
    preview_path: Path,
    template_source: Path,
    template_output: Path,
) -> dict[str, str | int]:
    config = json.loads(source.read_text(encoding="utf-8"))
    seed = int(hashlib.sha256(config["id"].encode()).hexdigest()[:8], 16)
    commands = _island_commands(seed) + _donor_commands()
    function_path.parent.mkdir(parents=True, exist_ok=True)
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    template_output.parent.mkdir(parents=True, exist_ok=True)
    function_path.write_text("\n".join(commands) + "\n", encoding="utf-8", newline="\n")
    preview_path.write_text(_preview(config), encoding="utf-8", newline="\n")
    shutil.copyfile(template_source, template_output)
    return {
        "commands": len([line for line in commands if line and not line.startswith("#")]),
        "function_sha256": hashlib.sha256(function_path.read_bytes()).hexdigest(),
        "preview_sha256": hashlib.sha256(preview_path.read_bytes()).hexdigest(),
        "template_sha256": hashlib.sha256(template_output.read_bytes()).hexdigest(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--function", type=Path, default=DEFAULT_FUNCTION)
    parser.add_argument("--preview", type=Path, default=DEFAULT_PREVIEW)
    parser.add_argument("--template-source", type=Path, default=DEFAULT_TEMPLATE_SOURCE)
    parser.add_argument("--template-output", type=Path, default=DEFAULT_TEMPLATE_OUTPUT)
    args = parser.parse_args()
    result = generate(
        args.source,
        args.function,
        args.preview,
        args.template_source,
        args.template_output,
    )
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
