#!/usr/bin/env python
"""Build the torn-off islet that Relic Island is supposed to stand on.

`data/towns.json` records relic_island at (1092, 5532) with ground y35.3 and a footprint whose slope reads
"mean 0.0, max 0.0" -- flat, because it is FLAT SEABED, 26.7 blocks under the sea. The site search that produced it
treated a level sea floor as level ground. There is no islet there and nothing near to re-site onto: the land
either side is the mainland (x1031-1499, where Pallet is) and a separate mass to the west (x850-997), 103 blocks
off at the nearest. The event wants a Pallet house on a fragment torn off and dropped in the sea, so the island has
to be built.

It is built as commands rather than painted into the heightmap, for the same reason the cavern and the world tree
are: everything authored here is regenerated by a tool after a terrain re-export, and an islet is one small object.

  python tools/islet.py --source-root <root> [--apply]
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np

import terrain as T
import function_limits

ROOT = Path(__file__).resolve().parent.parent
CENTRE = (1092, 5532)
RADIUS = 30                 # to roughly the waterline
TOP = 68                    # a low crown, 6 over the sea
SEED = 20260916


def island_top(bed, sea, seed=SEED):
    """Island surface y over a (2R+1) square, and the radius field. NaN where the column stays seabed."""
    n = 2 * RADIUS + 1
    zz, xx = np.mgrid[0:n, 0:n].astype(np.float64)
    u, v = xx - RADIUS, zz - RADIUS
    ang = np.arctan2(v, u)
    # an outline that is not a circle: three harmonics, so it reads as a torn fragment rather than a dish
    wob = 4.6 * np.cos(2 * ang + 0.9) + 3.1 * np.cos(3 * ang + 2.6) + 2.0 * np.cos(5 * ang + 5.1)
    r = np.hypot(u, v * 1.06) + wob
    t = np.clip(1.0 - r / RADIUS, 0.0, 1.0)
    rng = np.random.default_rng(seed)
    noise = rng.normal(0.0, 1.0, (n, n))
    for _ in range(3):                                  # smooth the noise so it is relief, not speckle
        q = np.pad(noise, 1, mode="edge")
        noise = 0.36 * noise + 0.16 * (q[:-2, 1:-1] + q[2:, 1:-1] + q[1:-1, :-2] + q[1:-1, 2:])
    top = (sea - 4) + (TOP - (sea - 4)) * np.power(t, 0.62) + 3.2 * np.tanh(noise * 2.2) * t
    top = np.where(t <= 0, np.nan, np.rint(top))
    return top, r


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    T.add_common_args(p)
    p.add_argument("--apply", action="store_true")
    p.add_argument("--server", default=None, help="server directory for --apply; needs the coordination lock")
    a = p.parse_args(argv)
    heights, world = T.load_from_args(a)
    sea = int(T.sea_level(world))
    cx, cz = CENTRE
    bed = heights[cz - RADIUS:cz + RADIUS + 1, cx - RADIUS:cx + RADIUS + 1].astype(float)
    top, r = island_top(bed, sea)
    live = ~np.isnan(top)
    above = live & (top > sea)
    print("seabed under the site y%.1f..%.1f, sea level y%d" % (bed.min(), bed.max(), sea))
    print("island: %d columns, %d of them above water (%.2f ha), crown y%.0f"
          % (live.sum(), above.sum(), above.sum() / 1e4 * 1.0, np.nanmax(top)))
    blocks = int(np.nansum(np.clip(top - np.floor(bed), 0, None)))
    print("fill: about %d blocks" % blocks)

    cmds = ["# Relic Island: the islet the outpost stands on (tools/islet.py)"]
    n = 2 * RADIUS + 1
    for j in range(n):
        i = 0
        while i < n:
            if not live[j, i]:
                i += 1
                continue
            b_, t_ = int(math.floor(bed[j, i])), int(top[j, i])
            k = i
            while k + 1 < n and live[j, k + 1] and int(math.floor(bed[j, k + 1])) == b_ and int(top[j, k + 1]) == t_:
                k += 1
            x0, x1, z = cx - RADIUS + i, cx - RADIUS + k, cz - RADIUS + j
            if t_ > b_:
                cmds.append("fill %d %d %d %d %d %d minecraft:stone replace #minecraft:air" % (x0, b_ + 1, z, x1, t_, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:stone replace minecraft:water" % (x0, b_ + 1, z, x1, t_, z))
            # a shore of sand through the tide line, grass above it, dirt just under the cap
            lo, hi = max(b_ + 1, sea - 2), min(t_, sea + 2)
            if hi >= lo:
                cmds.append("fill %d %d %d %d %d %d minecraft:sand" % (x0, lo, z, x1, hi, z))
            if t_ > sea + 2:
                cmds.append("fill %d %d %d %d %d %d minecraft:dirt" % (x0, max(b_ + 1, t_ - 3), z, x1, t_ - 1, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:grass_block" % (x0, t_, z, x1, t_, z))
            i = k + 1
    out = ROOT / "build" / "islet" / "relic_island.mcfunction"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(function_limits.ensure_loaded(cmds)) + "\n", encoding="utf-8")
    print("wrote %s (%d commands)" % (out.relative_to(ROOT), len(cmds) - 1))

    rep = {"centre": list(CENTRE), "radius": RADIUS, "sea_level": sea,
           "columns": int(live.sum()), "columns_above_water": int(above.sum()),
           "crown_y": int(np.nanmax(top)), "blocks": blocks,
           "seabed_y": [float(bed.min()), float(bed.max())],
           "why": "the recorded site is flat seabed 26.7 blocks under the sea; nothing within 103 blocks is an islet"}
    (ROOT / "derived" / "sites" / "relic_island.json").write_text(json.dumps(rep, indent=1), encoding="utf-8")

    if not a.apply:
        print("(dry run -- pass --apply to build it)")
        return
    import time
    import runtime_guard
    rcon, PW = runtime_guard.rcon(a.server)
    box = (cx - RADIUS - 8, cz - RADIUS - 8, cx + RADIUS + 8, cz + RADIUS + 8)
    print(rcon.run(["forceload add %d %d %d %d" % box], PW, timeout=600)[0].strip()[:70])
    time.sleep(20)
    o = rcon.run(cmds[1:], PW, timeout=3600)
    bad = [x.strip() for x in o if "Success" not in x and "No blocks" not in x]
    print("replies not OK: %d %s" % (len(bad), bad[:3]))
    rcon.run(["forceload remove %d %d %d %d" % box], PW, timeout=600)


if __name__ == "__main__":
    main()
