#!/usr/bin/env python
"""The level-cap catch block: a ball thrown at a Pokemon over the thrower's RCT level cap breaks free, from
data/level_cap.json, as the world pack build/datapacks/cobblers_levelcap.

The trap it closes (docs/STATE.md "The level-cap trap"; EXP-035 row 13): rctmod stops experience at the cap but not
catching, and refuses every trainer battle while a party member is over the cap, so a player who catches something
strong is locked out of the next gym. The owner, 2026-09-28: block catching above the cap entirely.

How (docs/research/notes/level-cap-catch-block.md, every hook read in source, the chain not yet run):

  data/cobblemon/callbacks/poke_ball_capture_calculated/cobblers_level_cap.molang
      after the ball's own maths: a player's throw tags the target entity and runs, as the thrower and at the thrower,
      cobblers:levelcap/check; if the thrower then carries the tag cobblers.overcap, the shakes are set to 0 (it
      breaks free) and the tag is cleared. MoLang cannot read a score, so the tag carries the answer back.
  cobblers:levelcap/check
      the cap from `rctmod player get level_cap @s` (its result is the cap), the target's Pokemon.Level, the
      comparison (strictly over, as rctmod's own refusal), the message. A cap or level it cannot read (0) allows it.

Callbacks fire only from data/cobblemon/callbacks/<event>/, under a cobblers_ file name (.claude/rules/datapacks.md).
The rctmod line is a macro: a mod's command written plainly in a function may be parsed at server start before it is
usable, as `spawnpokemonat` is (EXP-046); a macro line is parsed when it runs.

  python tools/levelcap_pack.py      # -> build/datapacks/cobblers_levelcap (world-local: a callback acts on its own)
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "level_cap.json"
OUT = ROOT / "build" / "datapacks" / "cobblers_levelcap"
NS = "cobblers"
TARGET, OVER = "cobblers.lc_target", "cobblers.overcap"
CAP, LV = "cobblers.lc_cap", "cobblers.lc_lv"


def files(doc):
    msg = json.dumps({"text": doc["message"], "color": doc.get("message_color", "red")})
    return {
        "data/cobblemon/callbacks/poke_ball_capture_calculated/cobblers_level_cap.molang": "\n".join([
            "'Generated by tools/levelcap_pack.py from data/level_cap.json. A ball a player throws at a Pokemon over their RCT';",
            "'level cap breaks free (the owner, 2026-09-28). The answer comes back as a tag: MoLang cannot read a score.';",
            "t.th = q.thrower;",
            "t.th.is_player ? {",
            "  t.pk = q.pokemon;",
            "  t.pk.add_tag('%s');" % TARGET,
            "  q.run_command('execute as ' + t.th.uuid + ' at @s run function %s:levelcap/check {x:\"\"}');" % NS,
            "  t.th.has_tag('%s') ? {" % OVER,
            "    q.set_shakes(0);",
            "    t.th.remove_tag('%s');" % OVER,
            "  };",
            "};",
            ""]),
        "data/%s/function/levelcap/check.mcfunction" % NS: "\n".join([
            "# as and at the thrower, from the poke_ball_capture_calculated callback: is the target over my cap?",
            "tag @s remove %s" % OVER,
            "$execute store result score @s %s run rctmod player get level_cap @s$(x)" % CAP,
            "scoreboard players set @s %s 0" % LV,
            "execute store result score @s %s run data get entity @e[type=cobblemon:pokemon,tag=%s,limit=1,sort=nearest] Pokemon.Level"
            % (LV, TARGET),
            "tag @e[type=cobblemon:pokemon,tag=%s] remove %s" % (TARGET, TARGET),
            "# strictly over, as rctmod's own refusal counts; a cap or a level that did not read (0) lets the catch through",
            "execute if score @s %s matches 1.. if score @s %s matches 1.. if score @s %s > @s %s run tag @s add %s"
            % (CAP, LV, LV, CAP, OVER),
            "execute if entity @s[tag=%s] run tellraw @s %s" % (OVER, msg),
            ""]),
        "data/%s/function/levelcap/load.mcfunction" % NS: "\n".join([
            "scoreboard objectives add %s dummy" % CAP,
            "scoreboard objectives add %s dummy" % LV,
            ""]),
        "data/minecraft/tags/function/load.json": json.dumps({"values": ["%s:levelcap/load" % NS]}) + "\n",
        "pack.mcmeta": json.dumps({"pack": {"pack_format": 48, "description":
                                   "Cobblers: no catching over the level cap (tools/levelcap_pack.py)"}}, indent=2) + "\n",
    }


def main():
    doc = json.loads(DATA.read_text(encoding="utf-8"))
    if OUT.exists():
        shutil.rmtree(OUT)
    for rel, text in files(doc).items():
        p = OUT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
