#!/usr/bin/env python
"""Turn a settlement's placements (data/placements.json) into a datapack function that builds it in the world.

For each building: a pad levelled at the median ground under its footprint (dirt fills hollows, air clears
the volume), /place template with the rotation that turns its entrance to the requested facing, every jigsaw
block replaced by its final state (a template placed by command keeps its jigsaws), and donor loot tables
removed. Then paths (dirt path replacing the grass surface, plants cleared above), the route's first stretch
along the routed leg, the waystone, and the world spawn.

Rotation follows Minecraft's StructureTemplate transform about the placement origin:
  none (x, z) | clockwise_90 (-z, x) | 180 (-x, -z) | counterclockwise_90 (z, -x)
so the command position is the requested footprint corner minus the rotated template's minimum corner.

  python tools/place_town.py hometown --out build/datapacks/cobblers_towns [--install <server>/datapacks]
  then in game or over RCON: /reload, /function cobblers:towns/hometown
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
from pathlib import Path

import numpy as np

import nbt
import terrain as T

ROOT = Path(__file__).resolve().parent.parent
DIRS = ["north", "east", "south", "west"]
ROT = ["none", "clockwise_90", "180", "counterclockwise_90"]
ORIENT_DIR = {"west": "west", "east": "east", "north": "north", "south": "south"}
PLANTS = ["minecraft:short_grass", "minecraft:tall_grass", "minecraft:fern", "minecraft:large_fern", "#minecraft:flowers",
          "minecraft:sweet_berry_bush", "minecraft:dead_bush", "minecraft:leaf_litter", "minecraft:bush"]


def rotate(x, z, rot):
    return {"none": (x, z), "clockwise_90": (-z, x), "180": (-x, -z), "counterclockwise_90": (z, -x)}[rot]


def template_info(path):
    _, doc = nbt.load(path)
    pal = doc["palette"]
    size = doc["size"]
    jigsaws, loot, entrance = [], [], None
    for b in doc["blocks"]:
        p = pal[b["state"]]
        n = b.get("nbt") or {}
        if p["Name"] == "minecraft:jigsaw":
            jigsaws.append((b["pos"], n.get("final_state") or "minecraft:air", (p.get("Properties") or {}).get("orientation", "")))
            if entrance is None and n.get("final_state") in ("minecraft:dirt_path", "minecraft:stone") and not (p.get("Properties") or {}).get("orientation", "").startswith("up"):
                entrance = (p.get("Properties") or {})["orientation"].split("_")[0]
        if n.get("LootTable"):
            loot.append(b["pos"])
    return {"size": size, "jigsaws": jigsaws, "loot": loot, "entrance": entrance}


def rotation_for(entrance, facing):
    k = (DIRS.index(facing) - DIRS.index(entrance)) % 4
    return ROT[k]


def footprint(size, rot):
    sx, _, sz = size
    corners = [rotate(x, z, rot) for x in (0, sx - 1) for z in (0, sz - 1)]
    xs, zs = [c[0] for c in corners], [c[1] for c in corners]
    return min(xs), min(zs), max(xs) - min(xs) + 1, max(zs) - min(zs) + 1


def build(settlement, doc, heights, legs_doc=None):
    s = doc["settlements"][settlement]
    cmds = ["# Generated by tools/place_town.py from data/placements.json (%s). Re-run to rebuild." % settlement]
    report = {"buildings": [], "roads": {}}
    boxes = []
    pad_y_at = {}
    for p in [q for q in doc["placements"] if q.get("settlement") == settlement]:
        info = template_info(ROOT / p["file"])
        rot = rotation_for(info["entrance"] or "west", p["facing"])
        if p.get("rotation") and p["rotation"] != rot:
            raise SystemExit("%s: rotation %s in data does not turn its %s entrance to face %s (needs %s)"
                             % (p["id"], p["rotation"], info["entrance"], p["facing"], rot))
        mnx, mnz, w, d = footprint(info["size"], rot)
        x0, z0 = p["position"]["x"], p["position"]["z"]
        x1, z1 = x0 + w - 1, z0 + d - 1
        for other in boxes:
            if not (x1 < other[1] or x0 > other[3] or z1 < other[2] or z0 > other[4]):
                raise SystemExit("%s overlaps %s" % (p["id"], other[0]))
        boxes.append((p["id"], x0, z0, x1, z1))
        ground = heights[z0:z1 + 1, x0:x1 + 1]
        y = int(round(float(np.median(ground))))
        px, pz = x0 - mnx, z0 - mnz
        h = info["size"][1]
        m = 2
        cmds += [
            "forceload add %d %d %d %d" % (x0 - 16, z0 - 16, x1 + 16, z1 + 16),
            "fill %d %d %d %d %d %d minecraft:dirt replace #minecraft:replaceable" % (x0 - m, y - 6, z0 - m, x1 + m, y - 1, z1 + m),
            "fill %d %d %d %d %d %d minecraft:grass_block" % (x0 - m, y, z0 - m, x1 + m, y, z1 + m),
            "fill %d %d %d %d %d %d minecraft:air" % (x0 - m, y + 1, z0 - m, x1 + m, y + h + 3, z1 + m),
            "place template %s %d %d %d %s none 1.0 0" % (p["template"], px, y + 1, pz, rot),
        ]
        for (jx, jy, jz), final, _ in info["jigsaws"]:
            rx, rz = rotate(jx, jz, rot)
            state = final if final != "minecraft:structure_void" else "minecraft:air"
            cmds.append("setblock %d %d %d %s" % (px + rx, y + 1 + jy, pz + rz, state))
        for (lx, ly, lz) in info["loot"]:
            rx, rz = rotate(lx, lz, rot)
            cmds.append("data remove block %d %d %d LootTable" % (px + rx, y + 1 + ly, pz + rz))
        cmds.append("forceload remove %d %d %d %d" % (x0 - 16, z0 - 16, x1 + 16, z1 + 16))
        for zz in range(z0 - m, z1 + m + 1):
            for xx in range(x0 - m, x1 + m + 1):
                pad_y_at[(xx, zz)] = y
        report["buildings"].append({"id": p["id"], "template": p["template"], "rotation": rot, "facing": p["facing"],
                                    "footprint": [x0, z0, x1, z1], "pad_y": y, "ground_range": [round(float(ground.min()), 1), round(float(ground.max()), 1)],
                                    "command_position": [px, y + 1, pz]})

    def surface(x, z):
        return pad_y_at.get((x, z), int(round(float(heights[z, x]))))

    def lay(points, width, material, rid):
        cols = set()
        half = width // 2
        for (ax, az), (bx, bz) in zip(points, points[1:]):
            n = int(max(abs(bx - ax), abs(bz - az))) + 1
            for i in range(n):
                t = i / max(n - 1, 1)
                cx, cz = round(ax + (bx - ax) * t), round(az + (bz - az) * t)
                for dx in range(-half, half + 1):
                    for dz in range(-half, half + 1):
                        cols.add((cx + dx, cz + dz))
        # group columns into short runs along x for compact commands
        by_row = {}
        for x, z in cols:
            by_row.setdefault(z, []).append(x)
        count = 0
        for z, xs in sorted(by_row.items()):
            xs.sort()
            run = [xs[0]]
            for x in xs[1:] + [None]:
                if x is not None and x == run[-1] + 1 and len(run) < 24:
                    run.append(x)
                    continue
                ys = [surface(xx, z) for xx in run]
                lo, hi = min(ys) - 3, max(ys) + 3
                cmds.append("fill %d %d %d %d %d %d %s replace minecraft:grass_block" % (run[0], lo, z, run[-1], hi, z, material))
                for plant in PLANTS:
                    cmds.append("fill %d %d %d %d %d %d minecraft:air replace %s" % (run[0], lo + 3, z, run[-1], hi + 3, z, plant))
                count += len(run)
                if x is not None:
                    run = [x]
        report["roads"][rid] = count

    allx = [b[1] for b in boxes] + [b[3] for b in boxes]
    allz = [b[2] for b in boxes] + [b[4] for b in boxes]
    cmds.append("forceload add %d %d %d %d" % (min(allx) - 40, min(allz) - 40, max(allx) + 40, max(allz) + 40))
    for r in s["roads"]:
        pts = r.get("polyline")
        if r.get("follow_leg"):
            leg = next(l for l in legs_doc["legs"] if "%s->%s" % (l["from"], l["to"]) == r["follow_leg"])
            poly = np.array(leg["polyline"], float)
            start = np.array(r["from"], float)
            i0 = int(np.argmin(np.hypot(*(poly - start).T)))
            pts, total = [list(map(int, start))], 0.0
            for q in poly[i0 + 1:]:
                total += math.dist(pts[-1], q)
                pts.append([int(q[0]), int(q[1])])
                if total >= r["length_blocks"]:
                    break
            report["route_points"] = pts
        lay(pts, r["width"], r["surface"], r["id"])
    wx, wz = s["waystone"]["position"]
    wy = surface(wx, wz) + 1
    cmds += ["setblock %d %d %d waystones:waystone[half=lower,facing=%s]" % (wx, wy, wz, s["waystone"]["facing"]),
             "setblock %d %d %d waystones:waystone[half=upper,facing=%s]" % (wx, wy + 1, wz, s["waystone"]["facing"])]
    sx, sz = s["spawn"]
    sy = surface(sx, sz) + 1
    cmds.append("setworldspawn %d %d %d" % (sx, sy, sz))
    cmds.append("forceload remove %d %d %d %d" % (min(allx) - 40, min(allz) - 40, max(allx) + 40, max(allz) + 40))
    report["waystone"] = [wx, wy, wz]
    report["spawn"] = [sx, sy, sz]
    report["commands"] = len(cmds)
    return cmds, report


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    T.add_common_args(p)
    p.add_argument("settlement")
    p.add_argument("--placements", default=str(ROOT / "data" / "placements.json"))
    p.add_argument("--legs", default=str(ROOT / "derived" / "routes" / "critical_legs.json"))
    p.add_argument("--install", default=None, help="copy the datapack into this datapacks folder")
    a = p.parse_args(argv)
    out = Path(a.out or ROOT / "build" / "datapacks" / "cobblers_towns")
    heights, world = T.load_from_args(a)
    doc = json.loads(Path(a.placements).read_text(encoding="utf-8"))
    legs = json.loads(Path(a.legs).read_text(encoding="utf-8")) if Path(a.legs).exists() else None
    cmds, report = build(a.settlement, doc, heights, legs)
    fn = out / "data" / "cobblers" / "function" / "towns" / ("%s.mcfunction" % a.settlement)
    fn.parent.mkdir(parents=True, exist_ok=True)
    (out / "pack.mcmeta").write_text(json.dumps({"pack": {"pack_format": 48, "description": "Cobblers: settlement placement functions (tools/place_town.py)"}}, indent=2) + "\n", encoding="utf-8")
    fn.write_text("\n".join(cmds) + "\n", encoding="utf-8")
    rep = ROOT / "derived" / "towns" / ("%s_placement.json" % a.settlement)
    rep.parent.mkdir(parents=True, exist_ok=True)
    rep.write_text(json.dumps(dict(report, provenance=T.provenance(world, Path(a.world))), indent=1), encoding="utf-8")
    print(json.dumps({k: v for k, v in report.items() if k != "route_points"}, indent=1))
    if a.install:
        dest = Path(a.install) / out.name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(out, dest)
        print("installed", dest)


if __name__ == "__main__":
    main()
