#!/usr/bin/env python
"""Put a box of a disposable world back to the ground the heightmap says it has.

Placement tools take their ground from the heightmap (tools/ground.py), never from the world. On a fresh
export the two agree at 99.85% of columns. On a disposable world that has been built on, dug into and
rebuilt, they no longer agree: the town areas of `spawnproof` were cut and filled by street prep, cleared
and refilled by hand, and rebuilt several times, so a building seated on the heightmap's ground found the
world's ground a block or two lower under some of its edges and left gaps there.

Rather than let a placement tool read that drifted world, this puts the box back to heightmap ground
first, which is what a re-export does for the whole map: dirt to five below the surface, grass on it, air
above to the height given. Then prep and building run on the ground they were planned for.

  python tools/restore_ground.py gym1_town --out <datapack dir>
  then: /reload, /function cobblers:restore/<settlement>

For a DISPOSABLE world only. It overwrites everything in the box above the ground, buildings included.

Ownership: generated output. It writes ground from the heightmap; it never reads a world.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import function_limits
import ground as G
import place_town

ROOT = Path(__file__).resolve().parent.parent


def commands(settlement, source_root, headroom=48, margin=24):
    doc = json.loads((ROOT / "data" / "placements.json").read_text(encoding="utf-8"))
    g = G.for_settlement(settlement, source_root, doc)
    if g.kind == "cavern_floor":
        return cavern_commands(settlement, g, headroom)
    x0, z0, x1, z1 = place_town.settlement_bounds(settlement, doc, margin=margin)
    grid = g.box(x0, z0, x1, z1)
    # Water is left exactly as it is. The box around Misty's town takes in Lake Viltri, and "air from the
    # ground up" over a lake bed drains the lake. Any column the painted water model marks wet is skipped,
    # so lakes, rivers and the sea keep their water and only dry ground is put back.
    from elder_trees import painted_water
    wet_full = painted_water(g.heights, g.world)
    wet = wet_full[z0 - g.oz:z1 - g.oz + 1, x0 - g.ox:x1 - g.ox + 1]
    cmds = ["# Generated by tools/restore_ground.py: %s back to heightmap ground (disposable worlds only)" % settlement]
    cmds += place_town.forceload_commands((x0, z0, x1, z1), "add")
    skipped = 0
    for iz in range(grid.shape[0]):
        z = z0 + iz
        row = grid[iz]
        dry = ~wet[iz]
        skipped += int((~dry).sum())
        start = 0
        for ix in range(1, len(row) + 1):
            if ix < len(row) and row[ix] == row[start] and dry[ix] == dry[start]:
                continue
            if dry[start]:
                h = int(row[start])
                a, b = x0 + start, x0 + ix - 1
                cmds.append("fill %d %d %d %d %d %d minecraft:dirt" % (a, h - 5, z, b, h - 1, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:grass_block" % (a, h, z, b, h, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:air" % (a, h + 1, z, b, h + headroom, z))
            start = ix
    cmds.insert(1, "# %d wet columns left as they are" % skipped)
    cmds += place_town.forceload_commands((x0, z0, x1, z1), "remove")
    return cmds, (x0, z0, x1, z1)


def cavern_commands(settlement, g, headroom):
    """A town on the cavern floor is restored only where its plan builds, and never up into the roof.

    The whole-box restore every other town gets would clear the cavern's own cherry trees and the light strung
    between them for 24 blocks round the town, and 48 blocks of headroom reaches the roof where the cavern is low.
    So the rects the town plan occupies (its streets' cells, the plaza, every lot and anchor, one block round each)
    are put back to the cavern floor, with air up to two blocks under the roof at most. The plan keeps its lots and
    streets clear of the trees and the light strings, so nothing of the cavern's own is touched.
    """
    plan = json.loads((ROOT / "derived" / "towns" / ("%s_plan.json" % settlement)).read_text(encoding="utf-8"))
    (cx0, cz0, cx1, cz1), ceiling = g.ceiling["box"], g.ceiling["grid"]
    cols = set()
    rects = [a["rect"] for a in plan["anchors"]] + [l["rect"] for l in plan["lots"]]
    if plan.get("plaza"):
        rects.append(plan["plaza"]["rect"])
    for x0, z0, x1, z1 in rects:
        cols |= {(x, z) for x in range(x0 - 1, x1 + 2) for z in range(z0 - 1, z1 + 2)}
    for st in plan["streets"].values():
        for z, _y, xa, xb in st["cells"]:
            cols |= {(x, zz) for x in range(xa - 1, xb + 2) for zz in (z - 1, z, z + 1)}
    # the town's one surface piece (the gate at the meltwater mouth) is not on the cavern floor and is not restored
    # here: it is an earthwork on heightmap ground, rebuilt by its own commands
    cols = {c for c in cols if cx0 <= c[0] <= cx1 and cz0 <= c[1] <= cz1}
    cmds = ["# Generated by tools/restore_ground.py: %s back to the cavern floor where its plan builds (disposable worlds only)"
            % settlement]
    by_row = {}
    for x, z in cols:
        by_row.setdefault(z, []).append(x)
    xs_all = [c[0] for c in cols]; zs_all = [c[1] for c in cols]
    box = (min(xs_all), min(zs_all), max(xs_all), max(zs_all))
    cmds += place_town.forceload_commands(box, "add")
    for z in sorted(by_row):
        xs = sorted(by_row[z])
        key = lambda x: (g(x, z), min(g(x, z) + headroom, int(ceiling[z - cz0, x - cx0]) - 2))
        start = 0
        for i in range(1, len(xs) + 1):
            if i < len(xs) and xs[i] == xs[i - 1] + 1 and key(xs[i]) == key(xs[start]):
                continue
            h, top = key(xs[start])
            a, b = xs[start], xs[i - 1]
            cmds.append("fill %d %d %d %d %d %d minecraft:dirt" % (a, h - 3, z, b, h - 1, z))
            cmds.append("fill %d %d %d %d %d %d minecraft:grass_block" % (a, h, z, b, h, z))
            if top > h:
                cmds.append("fill %d %d %d %d %d %d minecraft:air" % (a, h + 1, z, b, top, z))
            start = i
    cmds += place_town.forceload_commands(box, "remove")
    return cmds, box


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("settlement")
    p.add_argument("--source-root", default=os.environ.get("COBBLERS_SOURCE_ROOT"))
    p.add_argument("--out", default=str(ROOT / "build" / "datapacks" / "cobblers_restore"))
    p.add_argument("--headroom", type=int, default=48,
                   help="blocks of air above the ground; the League stands 159 tall, so it needs about 170")
    a = p.parse_args(argv)
    cmds, box = commands(a.settlement, a.source_root, headroom=a.headroom)
    refused = function_limits.check_lines(cmds, a.settlement)
    if refused:
        raise SystemExit("%d command(s) the server would refuse" % len(refused))
    out = Path(a.out)
    fn = out / "data" / "cobblers" / "function" / "restore" / ("%s.mcfunction" % a.settlement)
    fn.parent.mkdir(parents=True, exist_ok=True)
    (out / "pack.mcmeta").write_text(json.dumps(
        {"pack": {"pack_format": 48, "description": "Cobblers: restore ground from the heightmap (disposable worlds)"}}) + "\n",
        encoding="utf-8", newline="\n")
    fn.write_text("\n".join(cmds) + "\n", encoding="utf-8", newline="\n")
    print("wrote %s: %d commands over %s" % (fn, len(cmds), box))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
