#!/usr/bin/env python
"""Put a box of a disposable world back to the ground the heightmap says it has.

Placement tools take their ground from the heightmap (tools/ground.py), never from the world. On a fresh
export the two agree at 99.85% of columns. On a disposable world that has been built on, dug into and
rebuilt, they no longer agree: the town areas of `spawnproof` were cut and filled by street prep, cleared
and refilled by hand, and rebuilt several times, so a building seated on the heightmap's ground found the
world's ground a block or two lower under some of its edges and left gaps there.

Rather than let a placement tool read that drifted world, this puts the box back to heightmap ground
first, which is what a re-export does for the whole map: dirt to five below the surface, grass on it, air
above to the height given. Then prep and building run on the ground they were planned for.

  python tools/restore_ground.py gym1_town --out <datapack dir>
  then: /reload, /function cobblers:restore/<settlement>

For a DISPOSABLE world only. It overwrites everything in the box above the ground, buildings included.

Ownership: generated output. It writes ground from the heightmap; it never reads a world.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import function_limits
import ground as G
import place_town

ROOT = Path(__file__).resolve().parent.parent


def commands(settlement, source_root, headroom=48, margin=24):
    doc = json.loads((ROOT / "data" / "placements.json").read_text(encoding="utf-8"))
    x0, z0, x1, z1 = place_town.settlement_bounds(settlement, doc, margin=margin)
    g = G.load(source_root)
    grid = g.box(x0, z0, x1, z1)
    # Water is left exactly as it is. The box around Misty's town takes in Lake Viltri, and "air from the
    # ground up" over a lake bed drains the lake. Any column the painted water model marks wet is skipped,
    # so lakes, rivers and the sea keep their water and only dry ground is put back.
    from elder_trees import painted_water
    wet_full = painted_water(g.heights, g.world)
    wet = wet_full[z0 - g.oz:z1 - g.oz + 1, x0 - g.ox:x1 - g.ox + 1]
    cmds = ["# Generated by tools/restore_ground.py: %s back to heightmap ground (disposable worlds only)" % settlement]
    cmds += place_town.forceload_commands((x0, z0, x1, z1), "add")
    skipped = 0
    for iz in range(grid.shape[0]):
        z = z0 + iz
        row = grid[iz]
        dry = ~wet[iz]
        skipped += int((~dry).sum())
        start = 0
        for ix in range(1, len(row) + 1):
            if ix < len(row) and row[ix] == row[start] and dry[ix] == dry[start]:
                continue
            if dry[start]:
                h = int(row[start])
                a, b = x0 + start, x0 + ix - 1
                cmds.append("fill %d %d %d %d %d %d minecraft:dirt" % (a, h - 5, z, b, h - 1, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:grass_block" % (a, h, z, b, h, z))
                cmds.append("fill %d %d %d %d %d %d minecraft:air" % (a, h + 1, z, b, h + headroom, z))
            start = ix
    cmds.insert(1, "# %d wet columns left as they are" % skipped)
    cmds += place_town.forceload_commands((x0, z0, x1, z1), "remove")
    return cmds, (x0, z0, x1, z1)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("settlement")
    p.add_argument("--source-root", default=os.environ.get("COBBLERS_SOURCE_ROOT"))
    p.add_argument("--out", default=str(ROOT / "build" / "datapacks" / "cobblers_restore"))
    a = p.parse_args(argv)
    cmds, box = commands(a.settlement, a.source_root)
    refused = function_limits.check_lines(cmds, a.settlement)
    if refused:
        raise SystemExit("%d command(s) the server would refuse" % len(refused))
    out = Path(a.out)
    fn = out / "data" / "cobblers" / "function" / "restore" / ("%s.mcfunction" % a.settlement)
    fn.parent.mkdir(parents=True, exist_ok=True)
    (out / "pack.mcmeta").write_text(json.dumps(
        {"pack": {"pack_format": 48, "description": "Cobblers: restore ground from the heightmap (disposable worlds)"}}) + "\n",
        encoding="utf-8", newline="\n")
    fn.write_text("\n".join(cmds) + "\n", encoding="utf-8", newline="\n")
    print("wrote %s: %d commands over %s" % (fn, len(cmds), box))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
