#!/usr/bin/env python
"""The Celebi asleep in Route 1's world-tree sapling, from data/sapling_celebi.json.

EXP-023 candidate A: a Pokemon entity with the flags that experiment proved (not catchable, not battleable, immobile,
asleep, unlabelled, never despawning). The one thing it could not give is damage immunity: Cobblemon ignores
Invulnerable and a sword killed it. So the branch is walled in barrier blocks, invisible and solid: a melee hit, an
arrow or a thrown ball stops at the barrier, and the Celebi is still seen through it.

Cobblemon's spawn command does nothing when a function runs it (measured on staging 2026-09-25: `spawnpokemonat` from
the console spawned the Celebi, the same line in a function spawned nothing, and vanilla `summon` refuses
cobblemon:pokemon). So the Celebi is summoned over RCON by the re-application (placement_steps, tools/reapply.py R14C),
and the pack does what functions can:

  celebi/shell      the barrier blocks round the branch (they replace air only)
  celebi/dress_new  the flags, the tag, the branch and the heading, on the Celebi just summoned
  celebi/keeper     every period_ticks while a player is within player_radius: remove a second Celebi (a load race)
                    and put it back on its branch if anything moved it

  python tools/sapling_celebi.py                 # -> build/datapacks/cobblers_celebi (a world pack: it runs on its own)
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "sapling_celebi.json"
OUT = ROOT / "build" / "datapacks" / "cobblers_celebi"
TAG = "cobblers_celebi"
OBJ = "cobblers.celebi"


def load(path=DATA):
    d = json.loads(Path(path).read_text(encoding="utf-8"))
    if d.get("schema") != "cobblers.sapling-celebi/1":
        raise SystemExit("%s: schema must be cobblers.sapling-celebi/1" % path)
    return d


def _at(d):
    return "%s %s %s" % tuple(d["position"])


def shell_box(d):
    """(x0, y0, z0, x1, y1, z1): the barrier box, the Celebi's block and the one above it left open inside it."""
    x, y, z = (int(v // 1) for v in d["position"])
    return x - 1, y - 1, z - 1, x + 1, y + 2, z + 1


def placement_steps(d):
    """The re-application's actions: load the branch, wall it, summon the Celebi over RCON if none stands there
    (tagged or not, so a run never stacks a second), dress it, release the chunk."""
    x, _y, z = (int(v // 1) for v in d["position"])
    at = _at(d)
    return [("cmd", "forceload add %d %d" % (x, z)), ("wait", 3),
            ("fn", "cobblers:celebi/shell"),
            ("cmd", "execute unless entity @e[tag=%s] positioned %s unless entity @e[type=cobblemon:pokemon,distance=..3] "
                    "run spawnpokemonat %s %s level=%d %s" % (TAG, at, at, d["species"], d["level"], " ".join(d["spawn_properties"]))),
            ("wait", 1),
            ("fn", "cobblers:celebi/dress_new"),
            ("cmd", "forceload remove %d %d" % (x, z))]


def files(d):
    at = _at(d)
    yaw = d["yaw"]
    k = d["keeper"]
    nbt = ",".join("%s:%s" % (key, v) for key, v in d["nbt"].items())
    x, y, z = (int(v // 1) for v in d["position"])
    x0, y0, z0, x1, y1, z1 = shell_box(d)
    out = {
        "celebi/load": ["scoreboard objectives add %s dummy" % OBJ,
                        "schedule function cobblers:celebi/keeper %dt replace" % k["period_ticks"]],
        "celebi/shell": ["# Generated by tools/sapling_celebi.py: barriers round the branch; the Celebi's own column stays open",
                         "# chunks-loaded-by: tools/reapply.py R14C (forceload add over RCON before this runs)",
                         "fill %d %d %d %d %d %d minecraft:barrier replace minecraft:air" % (x0, y0, z0, x1, y1, z1),
                         "fill %d %d %d %d %d %d minecraft:air replace minecraft:barrier" % (x, y, z, x, y + 1, z)],
        "celebi/dress_new": ["execute positioned %s as @e[type=cobblemon:pokemon,tag=!%s,distance=..2,limit=1,sort=nearest] "
                             "run function cobblers:celebi/dress" % (at, TAG)],
        "celebi/dress": ["data merge entity @s {%s}" % nbt,
                         "tag @s add %s" % TAG,
                         "tp @s %s %s 0" % (at, yaw)],
        "celebi/keeper": ["execute positioned %s if entity @a[distance=..%d] run function cobblers:celebi/keep"
                          % (at, k["player_radius"]),
                          "schedule function cobblers:celebi/keeper %dt replace" % k["period_ticks"]],
        "celebi/keep": ["execute store result score #n %s if entity @e[tag=%s]" % (OBJ, TAG),
                        "execute if score #n %s matches 2.. run kill @e[tag=%s,limit=1,sort=random]" % (OBJ, TAG),
                        "execute as @e[tag=%s] positioned %s unless entity @s[distance=..%s] run tp @s %s %s 0"
                        % (TAG, at, k["home_tolerance"], at, yaw)],
    }
    return {"data/cobblers/function/%s.mcfunction" % n: "\n".join(v) + "\n" for n, v in out.items()} | {
        "data/minecraft/tags/function/load.json": json.dumps({"values": ["cobblers:celebi/load"]}, indent=2) + "\n",
        "pack.mcmeta": json.dumps({"pack": {"pack_format": 48, "description": "Cobblers: the sleeping Celebi in the Route 1 "
                                            "sapling (tools/sapling_celebi.py)"}}, indent=2) + "\n"}


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--out", default=str(OUT))
    a = p.parse_args(argv)
    d = load()
    out = Path(a.out)
    if out.exists():
        shutil.rmtree(out)
    for rel, text in files(d).items():
        f = out / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s: a %s at %s, walled in %s, kept every %d ticks"
          % (out, d["species"], d["position"], shell_box(d), d["keeper"]["period_ticks"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
