#!/usr/bin/env python
"""Render data/spawn_blocks.json as the owner's placing list: which block brings which species.

The owner, 2026-10-05: "give me all the spawns, id like to just place most things down to help with spawns". Each
block a loaded spawn condition names (directly or through a tag), with the species whose spawn needs it and whether
the block must be the one the Pokemon stands on (neededBaseBlocks) or merely near it (neededNearbyBlocks). Sorted
by how many species a block brings. data/spawn_blocks.json is generated from the server's jars and datapacks by
tools/spawn_blocks.py; re-run that first if the mod set changed.

  python tools/spawn_blocks_list.py              # -> docs/world-building/SPAWN_BLOCKS_LIST.md
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "spawn_blocks.json"
OUT = ROOT / "docs" / "world-building" / "SPAWN_BLOCKS_LIST.md"
REF = re.compile(r"^(?P<species>.+?) \[(?P<via>[^,]+), (?P<field>needed\w+), (?P<source>[^\]]+)\]$")


def rows(doc):
    """[(block, {species: set(fields)}, set(tags))] for every block, most species first."""
    out = []
    for block, refs in doc["blocks"].items():
        species, via = {}, set()
        for r in refs:
            m = REF.match(r)
            if not m:
                species.setdefault(r, set())
                continue
            species.setdefault(m["species"], set()).add("on" if m["field"] == "neededBaseBlocks" else "near")
            if m["via"].startswith("#"):
                via.add(m["via"])
        out.append((block, species, via))
    return sorted(out, key=lambda r: (-len(r[1]), r[0]))


def render(doc):
    lines = ["# Spawn blocks: which block brings which Pokemon",
             "",
             "Generated by `tools/spawn_blocks_list.py` from `data/spawn_blocks.json` (itself generated by "
             "`tools/spawn_blocks.py` from the server's %d mod jars and %d datapacks). Do not edit by hand."
             % (doc["scope"].get("mod_jars", 0), doc["scope"].get("datapacks", 0)),
             "",
             "**on** = the Pokemon must spawn standing on the block (`neededBaseBlocks`); **near** = the block must be "
             "nearby (`neededNearbyBlocks`). A block only helps where the species' other conditions (biome, height, "
             "light, sky, time) also hold, and only outside a Habitat Block's replaced pool. `herd` is a herd spawn "
             "entry, not a species.",
             "",
             "| Block | Brings | Stops (an anticondition: the block nearby prevents the spawn) | Via tag |",
             "|---|---|---|---|"]
    fmt = lambda items: ", ".join("%s (%s)" % (s, "/".join(sorted(f))) if f else s for s, f in items)  # noqa: E731
    for block, species, via in rows(doc):
        anti = " (anticondition)"
        brings = sorted((s, f) for s, f in species.items() if not s.endswith(anti))
        stops = sorted((s[:-len(anti)], f) for s, f in species.items() if s.endswith(anti))
        lines.append("| `%s` | %s | %s | %s |" % (block, fmt(brings), fmt(stops), ", ".join(sorted(via))))
    return "\n".join(lines) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--data", default=str(SRC))
    p.add_argument("--out", default=str(OUT))
    a = p.parse_args(argv)
    doc = json.loads(Path(a.data).read_text(encoding="utf-8"))
    Path(a.out).write_text(render(doc), encoding="utf-8", newline="\n")
    print("wrote %s: %d blocks" % (a.out, len(doc["blocks"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
